"""
Canonical Phrases for Voice Intent Embedding Classifier
Natural language training phrases per intent and language for semantic similarity matching.
Expands keyword-based patterns into full utterances that capture colloquial variation.
"""

from app.services.voice.models import VoiceIntent

CANONICAL_PHRASES: dict[str, dict[str, list[str]]] = {
    VoiceIntent.NAVIGATION: {
        "en": ["take me to the home page", "go to the main screen", "back to home",
               "show me the channels", "open movies section", "go to series",
               "I want to listen to radio", "open the podcast page",
               "bring up audiobooks", "navigate to live TV"],
        "he": ["קח אותי לעמוד הראשי", "חזור לדף הבית", "תעבור לערוצים",
               "פתח את הסרטים", "תראה לי סדרות", "תעביר אותי לרדיו",
               "אני רוצה פודקאסטים", "פתח ספרי שמע",
               "עבור לשידור חי", "חזרה הביתה"],
        "es": ["llévame a la pantalla principal", "ir al inicio", "volver atrás",
               "abrir los canales", "ir a películas", "mostrar las series",
               "quiero escuchar radio", "abrir los podcasts",
               "ir a audiolibros", "volver al menú principal"],
    },
    VoiceIntent.PLAYBACK: {
        "en": ["pause the video", "can you pause this", "hold on pause it",
               "play it now", "start playing", "resume where I left off",
               "stop the playback", "continue playing", "press play", "unpause this"],
        "he": ["תעצור את הסרטון", "תשהה רגע", "תמשיך לנגן", "תפעיל את זה",
               "עצור הכל", "תנגן מההתחלה", "השהה בבקשה",
               "המשך מאיפה שעצרתי", "תתחיל לנגן", "נגן את זה"],
        "es": ["pausa el video", "detén la reproducción", "reproduce esto",
               "continúa donde lo dejé", "empieza a reproducir", "para todo",
               "reanuda la reproducción", "ponle pausa", "dale play", "pon play"],
    },
    VoiceIntent.SEARCH: {
        "en": ["search for comedies", "show me funny movies", "find me a drama",
               "I want something funny to watch", "do you have action films",
               "is there anything new", "find documentaries about nature",
               "show me what you have", "where can I find thrillers",
               "any good movies tonight"],
        "he": ["חפש לי קומדיות", "תראה לי סרטי אקשן", "מצא לי דרמה טובה",
               "יש לכם משהו חדש", "איפה הסרטים הכי טובים",
               "אני מחפש סדרה מצחיקה", "הצג דוקומנטרים", "מה יש לצפות",
               "תמצא לי סרט מתח", "חפש סרטים ישראליים"],
        "es": ["busca comedias", "encuentra películas de acción", "muéstrame dramas",
               "tienen algo nuevo", "buscar documentales de naturaleza",
               "quiero ver algo divertido", "hay películas de terror",
               "mostrar lo que tienen", "encontrar series de ciencia ficción",
               "buscar películas románticas"],
    },
    VoiceIntent.SCROLL: {
        "en": ["scroll down a bit", "go up please", "show me more", "next page",
               "go to the previous one", "keep scrolling", "scroll to the top",
               "move down", "take me further down", "go back up"],
        "he": ["גלול למטה", "תעלה למעלה", "תראה לי עוד", "עבור להבא",
               "חזור לקודם", "תמשיך לגלול", "תגלול עד למעלה",
               "תרד למטה", "עוד קצת למטה", "תחזור למעלה"],
        "es": ["desplazar hacia abajo", "sube un poco", "muéstrame más",
               "siguiente página", "ir al anterior", "sigue desplazando",
               "ir hasta arriba", "bajar más", "página siguiente", "volver arriba"],
    },
    VoiceIntent.CONTROL: {
        "en": ["turn the volume up", "make it louder", "mute the sound",
               "it is too quiet", "change the language", "I need help",
               "unmute please", "lower the volume", "switch audio language",
               "turn it down a notch"],
        "he": ["תגביר את הקול", "זה שקט מדי", "תשתיק את הצליל",
               "תחזק את זה", "שנה שפה", "אני צריך עזרה",
               "תבטל השתקה", "תנמיך קול", "תעביר לשפה אחרת",
               "עזור לי בבקשה"],
        "es": ["sube el volumen", "está muy bajo", "silencia el sonido",
               "ponlo más fuerte", "cambiar el idioma", "necesito ayuda",
               "quitar silencio", "baja el volumen", "cambiar idioma de audio",
               "puedes ayudarme"],
    },
    VoiceIntent.KIDS: {
        "en": ["put on something for kids", "show children content", "play cartoons",
               "find animated movies", "kids mode please",
               "my daughter wants to watch something", "show me cartoons",
               "anything safe for children", "family friendly content",
               "play something for the little ones"],
        "he": ["תשים משהו לילדים", "תראה תוכן ילדים", "תפעיל קרטון",
               "מצא סרטים מצוירים", "הבת שלי רוצה לצפות במשהו",
               "יש משהו לקטנים", "פתח את אזור הילדים", "תשים אנימציה",
               "תוכן בטוח לילדים", "סרטונים לילדים קטנים"],
        "es": ["pon algo para niños", "mostrar contenido infantil",
               "reproducir dibujos animados", "buscar películas animadas",
               "modo niños por favor", "mi hija quiere ver algo",
               "muéstrame caricaturas", "contenido para la familia",
               "algo seguro para niños", "abrir la sección infantil"],
    },
    VoiceIntent.CONTENT_QUERY: {
        "en": ["what is this movie about", "tell me about this show",
               "give me details on this", "what am I watching",
               "who stars in this film", "when was this released",
               "how long is this episode", "what genre is this",
               "show info about this content", "what rating does this have"],
        "he": ["מה זה הסרט הזה", "ספר לי על הסדרה", "תן לי פרטים",
               "על מה אני צופה", "מי משחק בסרט הזה", "מתי זה יצא",
               "כמה זמן הפרק", "מאיזה ז'אנר זה",
               "מידע על התוכן הזה", "מה הדירוג של זה"],
        "es": ["de qué trata esta película", "cuéntame sobre esta serie",
               "dame detalles de esto", "qué estoy viendo",
               "quién actúa en esta película", "cuándo se estrenó",
               "cuánto dura este episodio", "de qué género es",
               "información de este contenido", "qué calificación tiene"],
    },
    VoiceIntent.DISPLAY_CHANNELS: {
        "en": ["show me all the channels", "open the channel list",
               "what channels are available", "display the channel guide",
               "bring up the TV channels", "list all live channels",
               "let me see the channels", "open channel grid",
               "which channels do you have", "show live TV channels"],
        "he": ["הראה לי את כל הערוצים", "פתח רשימת ערוצים",
               "אילו ערוצים יש", "הצג את לוח השידורים",
               "תראה ערוצי טלוויזיה", "רשימת כל הערוצים",
               "תפתח את הערוצים", "מה הערוצים שיש לכם",
               "הראה ערוצים חיים", "פתח את מדריך הערוצים"],
        "es": ["muéstrame todos los canales", "abrir la lista de canales",
               "qué canales hay disponibles", "mostrar la guía de canales",
               "ver los canales de televisión", "listar todos los canales",
               "déjame ver los canales", "abrir cuadrícula de canales",
               "qué canales tienen", "mostrar canales en vivo"],
    },
    VoiceIntent.WEB_SEARCH: {
        "en": ["search the web for this", "look it up online",
               "google that for me", "do a web search", "search online for recipes",
               "find this on the internet", "look up the latest news online",
               "can you search that online", "web search for weather",
               "search the internet for this topic"],
        "he": ["חפש את זה באינטרנט", "תחפש ברשת", "תגגל את זה",
               "חפש לי באינטרנט", "תמצא את זה אונליין",
               "חפש באינטרנט מתכונים", "תחפש חדשות ברשת",
               "חיפוש ברשת על הנושא הזה", "גוגל בבקשה", "תבדוק באינטרנט"],
        "es": ["busca eso en internet", "búscalo en la web", "googlea eso",
               "haz una búsqueda web", "buscar en línea recetas",
               "encontrar esto en internet", "buscar las últimas noticias en línea",
               "puedes buscar eso en la web", "buscar en internet el clima",
               "búsqueda web sobre este tema"],
    },
    VoiceIntent.PLAYLIST: {
        "en": ["add this to my playlist", "put this in my queue",
               "remove this from my list", "clear my playlist",
               "play my playlist", "show me what is in my list",
               "save this for later", "add to my watchlist",
               "take this off my playlist", "start playing my queue"],
        "he": ["הוסף את זה לרשימה שלי", "שים את זה בתור",
               "הסר מהרשימה שלי", "נקה את הרשימה",
               "נגן את הרשימה שלי", "מה יש ברשימה שלי",
               "שמור לצפייה מאוחר יותר", "תוסיף לרשימת הצפייה",
               "תוריד את זה מהפלייליסט", "תתחיל לנגן את התור שלי"],
        "es": ["agregar esto a mi lista", "poner esto en mi cola",
               "quitar esto de mi lista", "vaciar mi lista de reproducción",
               "reproducir mi playlist", "mostrar qué hay en mi lista",
               "guardar para después", "añadir a mi lista de seguimiento",
               "eliminar esto del playlist", "empezar mi cola de reproducción"],
    },
    VoiceIntent.CHAT: {
        "en": ["hey how are you doing", "what can you do", "tell me a joke",
               "I am bored", "what time is it", "who are you",
               "thanks for the help", "good morning",
               "what is new today", "can we just talk"],
        "he": ["היי מה נשמע", "מה אתה יכול לעשות", "ספר לי בדיחה",
               "משעמם לי", "מה השעה", "מי אתה",
               "תודה על העזרה", "בוקר טוב", "מה חדש היום", "בוא נדבר סתם"],
        "es": ["hola cómo estás", "qué puedes hacer", "cuéntame un chiste",
               "estoy aburrido", "qué hora es", "quién eres",
               "gracias por la ayuda", "buenos días",
               "qué hay de nuevo hoy", "podemos solo hablar"],
    },
}

TOTAL_PHRASE_COUNT: int = sum(
    len(phrases)
    for intent_langs in CANONICAL_PHRASES.values()
    for phrases in intent_langs.values()
)
