import Foundation

// MARK: - Interactive Subtitles

/// A subtitle cue with timing and optional word-level data.
struct SubtitleCue: Codable, Sendable, Identifiable {
    let id: String?
    let startTime: Double?
    let endTime: Double?
    let text: String?
    let textNikud: String?
    let textShoresh: String?
    let textHeblish: String? // Hebrew with English words mixed in
    let textEngrew: String? // English with Hebrew words mixed in
    let words: [SubtitleWord]?
    let hasShoreshVersion: Bool?
    let hasHeblishVersion: Bool?
    let hasEngrewVersion: Bool?
    let isAutoGenerated: Bool?
    let source: String?

    var stableId: String {
        id ?? "\(startTime ?? 0)-\(endTime ?? 0)"
    }
}

/// A single word within a subtitle cue for tap-to-translate.
struct SubtitleWord: Codable, Sendable, Identifiable {
    let id: String?
    let word: String?
    let start: Double?
    let end: Double?
    let isHebrew: Bool?

    var stableId: String {
        id ?? "\(word ?? "")-\(start ?? 0)"
    }
}

/// Response from GET /api/v1/content/{id}/subtitles/cues
struct SubtitleCuesResponse: Codable, Sendable {
    let cues: [SubtitleCue]?
    let language: String?
    let hasNikud: Bool?
}

/// Translation result for a tapped subtitle word.
struct TranslationResult: Decodable, Sendable {
    let word: String?
    let translation: String?
    let transliteration: String?
    let partOfSpeech: String?
    let example: String?
    let exampleTranslation: String?
}

/// Response from GET /api/v1/content/{id}/subtitles/preferences
struct SubtitlePreferencesResponse: Decodable, Sendable {
    let contentId: String?
    let language: String?
}

/// Request body for PUT /api/v1/content/{id}/subtitles/preferences
struct SubtitlePreferencesUpdate: Encodable, Sendable {
    let contentId: String
    let language: String
}

/// Response from GET /api/v1/subtitles/preferences (all user preferences)
struct AllSubtitlePreferencesResponse: Decodable, Sendable {
    let preferences: [SubtitlePreferenceItem]?
    let total: Int?
}

/// A single subtitle preference item within the global preferences list.
struct SubtitlePreferenceItem: Decodable, Sendable {
    let contentId: String?
    let preferredLanguage: String?
    let lastUsedAt: String?
}

// MARK: - Subtitle Modes

/// Hebrew subtitle display modes
enum SubtitleHebrewMode: String, Sendable, CaseIterable {
    case standard
    case nikud
    case shoresh
    case heblish

    var displayName: String {
        switch self {
        case .standard: return "Standard"
        case .nikud: return "Nikud"
        case .shoresh: return "Shoresh"
        case .heblish: return "Heblish"
        }
    }

    var description: String {
        switch self {
        case .standard: return "Regular Hebrew subtitles"
        case .nikud: return "Hebrew with vowel marks for pronunciation"
        case .shoresh: return "Root letters highlighted for vocabulary learning"
        case .heblish: return "Hebrew with English words mixed in"
        }
    }
}

/// English subtitle display modes
enum SubtitleEnglishMode: String, Sendable, CaseIterable {
    case standard
    case engrew

    var displayName: String {
        switch self {
        case .standard: return "Standard"
        case .engrew: return "Engrew"
        }
    }

    var description: String {
        switch self {
        case .standard: return "Regular English subtitles"
        case .engrew: return "English with Hebrew words transliterated"
        }
    }
}

// MARK: - External Subtitle Import

/// Response from POST /api/v1/subtitles/{id}/fetch-external
struct ExternalSubtitleImportResponse: Decodable, Sendable {
    let message: String?
    let imported: [ImportedTrack]?
    let skipped: [String]?
    let failed: [FailedTrack]?
}

/// A single imported subtitle track from OpenSubtitles
struct ImportedTrack: Decodable, Sendable {
    let language: String
    let languageName: String?
    let cueCount: Int?
    let trackId: String?
}

/// A subtitle track that failed to import from OpenSubtitles
struct FailedTrack: Decodable, Sendable {
    let language: String
    let reason: String?
}
