#!/bin/bash
# generate-local-config.sh
# Detects the Mac's local IP and writes Configuration/Local.xcconfig
# so that Debug builds point to this machine's backend.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$PROJECT_DIR/Configuration"
OUTPUT_FILE="$CONFIG_DIR/Local.xcconfig"

mkdir -p "$CONFIG_DIR"

LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || true)

if [ -z "$LOCAL_IP" ]; then
    LOCAL_IP="localhost"
    echo "No network detected on en0, falling back to localhost"
fi

cat > "$OUTPUT_FILE" <<EOF
// Local.xcconfig - Auto-generated by scripts/generate-local-config.sh
// This file is gitignored. Re-run the script to update.
DEV_HOST = $LOCAL_IP
EOF

echo "Wrote $OUTPUT_FILE with DEV_HOST = $LOCAL_IP"
