"""
Avatar Mesh Model.

Stores 3D mesh data generated by Ready Player Me from child video selfies.
Meshes are rigged glTF (.glb) files with blend shapes for lip-sync animation.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional

from beanie import Document, Indexed
from pydantic import BaseModel, Field


class MeshStatus(str, Enum):
    """3D mesh generation lifecycle."""

    PENDING = "pending"
    GENERATING = "generating"
    RIGGING = "rigging"
    READY = "ready"
    FAILED = "failed"


class MeshBlendShape(BaseModel):
    """A single blend shape target on the 3D mesh."""

    name: str = Field(..., description="Blend shape name (e.g. 'mouthOpen')")
    default_weight: float = Field(
        default=0.0, ge=0.0, le=1.0,
        description="Default weight for this blend shape",
    )


class AvatarMesh(Document):
    """
    3D avatar mesh generated by Ready Player Me.

    Stores the rigged glTF binary (.glb) in GCS along with
    blend shape metadata for real-time lip-sync animation.
    """

    avatar_id: Indexed(str, unique=True)
    user_id: Indexed(str)
    profile_id: str

    # Ready Player Me tracking
    rpm_render_id: Optional[str] = None

    # GCS storage paths
    glb_gcs_path: Optional[str] = None
    thumbnail_gcs_path: Optional[str] = None

    # Mesh metadata
    blend_shapes: List[MeshBlendShape] = Field(default_factory=list)
    bone_count: int = Field(default=0, ge=0)
    vertex_count: int = Field(default=0, ge=0)

    # Lifecycle
    status: MeshStatus = MeshStatus.PENDING
    credits_charged: int = Field(default=0, ge=0)
    error_message: Optional[str] = None

    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "avatar_meshes"
        indexes = [
            [("user_id", 1), ("profile_id", 1)],
        ]

    @property
    def is_ready(self) -> bool:
        return self.status == MeshStatus.READY and self.glb_gcs_path is not None

    @property
    def blend_shape_names(self) -> List[str]:
        return [bs.name for bs in self.blend_shapes]
