"""ComprehensionReport - Phase 3 post-session assembly-only report (D-05, D-07).

1:1 with ComprehensionSession by comprehension_session_id. Assembly-only
aggregate of ScoredExchange data (NO LLM involvement per D-05 / PITFALLS #4).
Stored result, not computed-on-demand — generated by ARQ worker on session
completion with 3-try retry + [3,9,27]s backoff (D-06).

Denormalizes partner_id + user_id + profile_id + content_id + character_name
from the source ComprehensionSession to enable org-scoped reads without a
cross-collection join.
"""
from datetime import datetime
from typing import List, Literal, Optional

from beanie import Document
from pydantic import BaseModel, Field
from pymongo import ASCENDING, IndexModel

ReportStatus = Literal["generated", "generation_failed"]


class ReportTurn(BaseModel):
    """Single turn aggregated into the report (assembly-only, D-05)."""

    turn_index: int = Field(..., ge=0, description="Ordinal in session.exchanges")
    question_text: str = Field(..., description="Verbatim character question")
    student_answer: str = Field(..., description="Verbatim student answer")
    numeric_score: int = Field(
        ..., ge=0, le=3, description="Authoritative post-override numeric score",
    )
    rationale: str = Field(
        ..., description="Authoritative post-override rationale",
    )
    adapt_level: str = Field(..., description="AdaptLevel at time of turn")
    moment_timestamp: float = Field(..., description="Seconds into video")
    override_applied: bool = Field(
        ..., description="True if any teacher override exists on source exchange",
    )
    original_numeric_score: int = Field(
        ..., ge=0, le=3, description="Rubric score prior to any override",
    )
    original_rationale: str = Field(
        ..., description="Rubric rationale prior to any override",
    )


class ComprehensionReport(Document):
    """Assembly-only aggregate report for a completed ComprehensionSession.

    1:1 with ComprehensionSession via comprehension_session_id unique index.
    Report is upserted by the ARQ worker; re-generation replaces the document
    in place. Histograms (high/med/low counts) are computed from the original
    rubric bands, NOT post-override bands, so the pre/post delta is preserved.
    """

    comprehension_session_id: str = Field(
        ..., description="ComprehensionSession.id (1:1)",
    )
    partner_id: str = Field(..., description="Org scoping — denormalised from session")
    user_id: str = Field(...)
    profile_id: str = Field(...)
    content_id: str = Field(...)
    character_name: str = Field(...)
    turn_count: int = Field(..., ge=0)
    avg_score: float = Field(..., ge=0.0, le=3.0)
    high_count: int = Field(..., ge=0)
    med_count: int = Field(..., ge=0)
    low_count: int = Field(..., ge=0)
    turns: List[ReportTurn] = Field(default_factory=list)
    status: ReportStatus = Field(default="generated")
    generation_attempts: int = Field(default=0, ge=0)
    last_error: Optional[str] = Field(default=None)
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "comprehension_reports"
        indexes = [
            IndexModel(
                [("comprehension_session_id", ASCENDING)],
                unique=True,
                name="session_report_unique",
            ),
            "partner_id",
            [("partner_id", 1), ("generated_at", -1)],
        ]
