"""
Magic Mirror Greeting Model.

Stores personalized daily Hebrew greetings generated by the child's avatar.
Greetings include vocabulary of the day and are rendered with the child's voice
and a Creatify lip-sync video for animated greeting playback.
"""

from datetime import datetime, timezone
from typing import Optional

from beanie import Document, Indexed
from pydantic import Field


class MagicMirrorGreeting(Document):
    """
    Personalized daily greeting from the child's 3D avatar.

    Cached with configurable expiry to avoid regeneration costs.
    """

    user_id: Indexed(str)
    profile_id: str

    # Greeting content
    greeting_text_he: str = Field(
        default="", description="Hebrew greeting text",
    )
    greeting_text_en: str = Field(
        default="", description="English greeting text",
    )

    # Generated audio + lip-sync
    greeting_audio_gcs_path: Optional[str] = None
    lipsync_video_gcs_path: Optional[str] = Field(
        default=None,
        description="GCS path to Creatify lip-sync video (MP4)",
    )

    # Vocabulary of the day
    vocabulary_of_the_day: str = Field(
        default="",
        description="Hebrew word of the day with transliteration",
    )

    # Lifecycle
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    expires_at: Optional[datetime] = None

    class Settings:
        name = "magic_mirror_greetings"
        indexes = [
            [("user_id", 1), ("profile_id", 1)],
            [("expires_at", 1)],
        ]

    @property
    def is_expired(self) -> bool:
        if not self.expires_at:
            return False
        now = datetime.now(timezone.utc)
        expires = self.expires_at
        if expires.tzinfo is None:
            expires = expires.replace(tzinfo=timezone.utc)
        return now > expires
