"""
Phrase Breakdown Model.

Stores TikTok-style Hebrew phrase breakdowns with cultural context,
origin, usage examples, and fun facts. Generated by Claude AI and cached.
"""

from datetime import datetime, timezone
from typing import List, Optional

from beanie import Document
from pydantic import BaseModel, Field
from pymongo import ASCENDING, IndexModel


class UsageExample(BaseModel):
    """Example of phrase usage in context."""

    hebrew: str = Field(..., description="Hebrew example sentence")
    transliteration: str = Field(..., description="Transliteration for learners")
    english: str = Field(..., description="English translation")
    context: str = Field(..., description="Usage context (formal/casual/slang)")


class PhraseBreakdown(Document):
    """
    Cached TikTok-style phrase breakdown.

    Each breakdown explains a Hebrew phrase/slang with:
    - Word-by-word decomposition
    - Cultural origin story
    - Usage examples
    - Fun facts
    """

    phrase: str = Field(..., min_length=1, max_length=200)
    phrase_normalized: str = Field(
        ..., description="Lowercase, stripped version for dedup"
    )

    transliteration: str = Field(..., description="Latin-script pronunciation")
    literal_translation: str = Field(..., description="Word-by-word literal meaning")
    meaning: str = Field(..., description="Actual meaning in English")
    meaning_he: str = Field(..., description="Explanation in simple Hebrew")

    origin: str = Field(
        ..., description="Cultural/linguistic origin (Arabic, Yiddish, military, etc.)"
    )
    origin_he: str = Field(..., description="Origin explanation in Hebrew")

    usage_level: str = Field(
        ...,
        pattern="^(everyday|casual|slang|formal|literary|archaic)$",
        description="How commonly the phrase is used",
    )

    examples: List[UsageExample] = Field(
        default_factory=list, description="Usage examples in context"
    )

    fun_fact: Optional[str] = Field(
        None, description="Interesting trivia about the phrase (English)"
    )
    fun_fact_he: Optional[str] = Field(
        None, description="Interesting trivia in Hebrew"
    )

    related_phrases: List[str] = Field(
        default_factory=list, description="Related phrase IDs"
    )

    tags: List[str] = Field(
        default_factory=list, description="Categorization tags"
    )

    source_content_id: Optional[str] = Field(
        None, description="Content where phrase was first encountered"
    )

    lookup_count: int = Field(default=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "phrase_breakdowns"
        indexes = [
            IndexModel([("phrase_normalized", ASCENDING)], unique=True),
            "tags",
            "usage_level",
            "source_content_id",
            IndexModel([("lookup_count", -1)]),
            IndexModel([("created_at", -1)]),
        ]


class PhraseBreakdownResponse(BaseModel):
    """API response for a phrase breakdown."""

    phrase: str
    transliteration: str
    literal_translation: str
    meaning: str
    meaning_he: str
    origin: str
    origin_he: str
    usage_level: str
    examples: List[UsageExample]
    fun_fact: Optional[str] = None
    fun_fact_he: Optional[str] = None
    related_phrases: List[str] = []
    tags: List[str] = []

    class Config:
        from_attributes = True


class PhraseBreakdownRequest(BaseModel):
    """Request to break down a Hebrew phrase."""

    phrase: str = Field(..., min_length=1, max_length=200)
    source_content_id: Optional[str] = Field(
        None, description="Content ID where phrase appears"
    )
    target_language: str = Field(
        default="en", pattern="^(en|es|he)$"
    )
