steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bayit-backend-production'
      - '--image=gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=8000'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--update-secrets=CSRF_ENABLED=csrf-enabled:latest'

images:
  - 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
  
timeout: '1800s'
