steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:1'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:1'
      - 'backend/'
    id: 'build-image'

  # Push to Container Registry (BUILD_ID tag)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:$BUILD_ID'
    id: 'push-build-id-image'

  # Push to Container Registry (latest tag)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:1'
    id: 'push-latest-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bayit-plus-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bayit-plus-backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'
      - '--cpu-boost'
      - '--set-env-vars'
      - 'API_V1_PREFIX=/api/v1,STORAGE_TYPE=gcs,DEBUG=false'
      - '--set-secrets'
      - 'SECRET_KEY=bayit-secret-key:latest,MONGODB_URL=mongodb-url:latest,MONGODB_DB_NAME=mongodb-db-name:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,STRIPE_PRICE_BASIC=stripe-price-basic:latest,STRIPE_PRICE_PREMIUM=stripe-price-premium:latest,STRIPE_PRICE_FAMILY=stripe-price-family:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GOOGLE_REDIRECT_URI=google-redirect-uri:latest,ELEVENLABS_API_KEY=elevenlabs-api-key:latest,TWILIO_ACCOUNT_SID=bayit-twilio-account-sid:latest,TWILIO_AUTH_TOKEN=bayit-twilio-auth-token:latest,TWILIO_PHONE_NUMBER=bayit-twilio-phone-number:latest,GCS_BUCKET_NAME=gcs-bucket-name:latest,BACKEND_CORS_ORIGINS=backend-cors-origins:latest,OPENSUBTITLES_API_KEY=opensubtitles-api-key:latest,LIBRARIAN_DAILY_AUDIT_CRON=bayit-librarian-daily-audit-cron:latest,LIBRARIAN_DAILY_AUDIT_TIME=bayit-librarian-daily-audit-time:latest,LIBRARIAN_DAILY_AUDIT_MODE=bayit-librarian-daily-audit-mode:latest,LIBRARIAN_DAILY_AUDIT_COST=bayit-librarian-daily-audit-cost:latest,LIBRARIAN_DAILY_AUDIT_STATUS=bayit-librarian-daily-audit-status:latest,LIBRARIAN_DAILY_AUDIT_DESCRIPTION=bayit-librarian-daily-audit-description:latest,LIBRARIAN_WEEKLY_AUDIT_CRON=bayit-librarian-weekly-audit-cron:latest,LIBRARIAN_WEEKLY_AUDIT_TIME=bayit-librarian-weekly-audit-time:latest,LIBRARIAN_WEEKLY_AUDIT_MODE=bayit-librarian-weekly-audit-mode:latest,LIBRARIAN_WEEKLY_AUDIT_COST=bayit-librarian-weekly-audit-cost:latest,LIBRARIAN_WEEKLY_AUDIT_STATUS=bayit-librarian-weekly-audit-status:latest,LIBRARIAN_WEEKLY_AUDIT_DESCRIPTION=bayit-librarian-weekly-audit-description:latest,LIBRARIAN_MAX_ITERATIONS=bayit-librarian-max-iterations:latest,LIBRARIAN_DEFAULT_BUDGET_USD=bayit-librarian-default-budget-usd:latest,LIBRARIAN_MIN_BUDGET_USD=bayit-librarian-min-budget-usd:latest,LIBRARIAN_MAX_BUDGET_USD=bayit-librarian-max-budget-usd:latest,LIBRARIAN_BUDGET_STEP_USD=bayit-librarian-budget-step-usd:latest,LIBRARIAN_REPORTS_LIMIT=bayit-librarian-reports-limit:latest,LIBRARIAN_ACTIONS_LIMIT=bayit-librarian-actions-limit:latest,LIBRARIAN_ACTIVITY_PAGE_SIZE=bayit-librarian-activity-page-size:latest,LIBRARIAN_ID_TRUNCATE_LENGTH=bayit-librarian-id-truncate-length:latest,LIBRARIAN_MODAL_MAX_HEIGHT=bayit-librarian-modal-max-height:latest'
      - '--service-account=624470113582-compute@developer.gserviceaccount.com'
    id: 'deploy-cloud-run'

# Substitutions for flexibility (can be overridden in trigger)
substitutions:
  _REGION: 'us-east1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '1'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
