#!/bin/bash
# Regenerate local.properties signing config from Google Cloud Secret Manager.
# Run this on any new machine before building a release AAB.
#
# Usage: ./scripts/sync-gcloud-secrets.sh

set -euo pipefail

PROJECT_ID="olorin-auth"
KEYSTORE_PATH="$HOME/.android/bayit-upload.jks"
LOCAL_PROPS="$(dirname "$0")/../local.properties"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

command -v gcloud &>/dev/null || { echo -e "${RED}gcloud CLI not found${NC}"; exit 1; }

echo -e "${YELLOW}Fetching Bayit+ Android signing secrets from GCloud ($PROJECT_ID)...${NC}"

fetch() {
  gcloud secrets versions access latest \
    --secret="$1" --project="$PROJECT_ID" 2>/dev/null
}

KEYSTORE_PASSWORD=$(fetch BAYIT_ANDROID_KEYSTORE_PASSWORD)
KEY_ALIAS=$(fetch BAYIT_ANDROID_KEY_ALIAS)
KEYSTORE_B64=$(fetch BAYIT_ANDROID_KEYSTORE_B64)

# Restore the keystore file
mkdir -p "$(dirname "$KEYSTORE_PATH")"
echo "$KEYSTORE_B64" | base64 --decode -o "$KEYSTORE_PATH"
echo -e "${GREEN}Keystore restored -> $KEYSTORE_PATH${NC}"

# Write local.properties (preserving existing sdk.dir and non-signing props)
SDK_DIR="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
cat > "$LOCAL_PROPS" <<EOF
## Generated by sync-gcloud-secrets.sh -- do not edit manually
sdk.dir=$SDK_DIR

## Release signing (upload key for Google Play)
bayit.keystore.path=$KEYSTORE_PATH
bayit.keystore.password=$KEYSTORE_PASSWORD
bayit.key.alias=$KEY_ALIAS
bayit.key.password=$KEYSTORE_PASSWORD
EOF

echo -e "${GREEN}local.properties written${NC}"
echo -e "${GREEN}Ready to build: ./gradlew bundleRelease${NC}"
