/* eslint-disable require-jsdoc, max-classes-per-file, @typescript-eslint/no-unused-vars */
/** Declaration file generated by dts-gen */

declare module '@appfabric/ui-data-layer/client' {
  import type { Sandbox } from '@appfabric/sandbox-spec';

  interface RUMMetadata {
    type: string;
    rid?: string;
    xm?: string;
    stm?: string;
    cln?: string;
    x: 'p' | 'f';
    ert?: string;
  }

  class GraphqlClient {
    constructor(t: any, r: any);

    mutation(e: any, t: any, r: any): any;

    query(e: any, t: any, r: any): any;

    static AuthConstants: {
      BROWSER_AUTH: string;
      COOKIE_ONLY_AUTH: string;
      OAUTH2: string;
      PRIVATE_AUTH: string;
      SIMPLE_AUTH: string;
    };
  }

  class RestClient {
    constructor(config: {
      baseUrl: string;
      authType?: (typeof RestClient.AuthConstants)[keyof typeof RestClient.AuthConstants];
      apiKey?: string;
      csrfToken?: string;
      sandbox?: Sandbox;
      fetchOptions?: RequestInit & {
        rumPath?: string;
        queryParams?: Record<string, string>;
      };
      companyId?: string;
      userId?: string;
      timeout?: number;
      noRetry?: boolean;
      retryDelays?: number;
      dispatchNetworkErrorEvent?: boolean;
      debugLogFunc?: (message: string) => void;
      pluginId?: string;
      onRequestStart?: (action: string) => void;
      onRequestEnd?: (action: string, metadata: RUMMetadata) => void;
      excludeIntuitPluginIdHeader?: boolean;
      generateIntuitTid?: boolean;
    });

    doDelete(e: any, ...args: any[]): Promise<Response>;

    get(e: any, ...args: any[]): Promise<Response>;

    patch(e: any, t: any, ...args: any[]): Promise<Response>;

    post(e: any, t: any, ...args: any[]): Promise<Response>;

    put(e: any, t: any, ...args: any[]): Promise<Response>;

    static AuthConstants: {
      COOKIE_ONLY_AUTH: 'cookie_only_auth';
      BROWSER_AUTH: 'browser_auth';
      OAUTH2: 'oauth2';
      PRIVATE_AUTH: 'private_auth';
      SIMPLE_AUTH: 'simple_auth';
    };
  }
}

/* eslint-enable require-jsdoc, max-classes-per-file, @typescript-eslint/no-unused-vars */
