steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args: ['build', '--no-cache', '-f', './backend/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bayit-plus-backend'
      - '--image=gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=300'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'

      # Startup optimization - CPU boost for faster cold start
      - '--cpu-boost'

      # Environment Variables (Non-Sensitive) - use update-env-vars to avoid conflicts
      - '--update-env-vars=ENVIRONMENT=production'
      - '--update-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--update-env-vars=LOG_LEVEL=INFO'
      - '--update-env-vars=DEBUG=false'

      # Librarian Daily Audit Configuration
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_CRON=0 2 * * *'
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_TIME=2:00 AM Israel Time'
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_MODE=Rule-based'
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_COST=~$0.01/day'
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_STATUS=ENABLED'
      - '--update-env-vars=LIBRARIAN_DAILY_AUDIT_DESCRIPTION=Scans recent content and random 10% sample. Auto-fixes safe issues.'

      # Librarian Weekly Audit Configuration
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_CRON=0 3 * * 0'
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_TIME=Sundays 3:00 AM Israel Time'
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_MODE=AI Agent'
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_COST=~$0.50/week'
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_STATUS=ENABLED'
      - '--update-env-vars=LIBRARIAN_WEEKLY_AUDIT_DESCRIPTION=Claude decides what to check and fix. Sends email only for major issues.'

      # Librarian Limits
      - '--update-env-vars=LIBRARIAN_MAX_ITERATIONS=50'
      - '--update-env-vars=LIBRARIAN_DEFAULT_BUDGET_USD=10.0'
      - '--update-env-vars=LIBRARIAN_MIN_BUDGET_USD=0.1'
      - '--update-env-vars=LIBRARIAN_MAX_BUDGET_USD=20.0'
      - '--update-env-vars=LIBRARIAN_BUDGET_STEP_USD=0.5'

      # Librarian Pagination
      - '--update-env-vars=LIBRARIAN_REPORTS_LIMIT=10'
      - '--update-env-vars=LIBRARIAN_ACTIONS_LIMIT=50'
      - '--update-env-vars=LIBRARIAN_ACTIVITY_PAGE_SIZE=10'

      # Librarian UI Settings
      - '--update-env-vars=LIBRARIAN_ID_TRUNCATE_LENGTH=8'
      - '--update-env-vars=LIBRARIAN_MODAL_MAX_HEIGHT=600'

      # WebAuthn Configuration (Production Values)
      - '--update-env-vars=WEBAUTHN_RP_ID=bayit.tv'
      - '--update-env-vars=WEBAUTHN_RP_NAME=Bayit Plus'

      # Secrets from Google Secret Manager
      - '--update-secrets=WEBAUTHN_ORIGIN=bayit-webauthn-origin:latest'
      - '--update-secrets=SECRET_KEY=bayit-backend-secret-key:latest'
      - '--update-secrets=MONGODB_URI=bayit-mongodb-uri:latest'
      - '--update-secrets=CSRF_ENABLED=csrf-enabled:latest'
      - '--update-secrets=ANTHROPIC_API_KEY=bayit-anthropic-api-key:latest'
      - '--update-secrets=OPENAI_API_KEY=bayit-openai-api-key:latest'
      - '--update-secrets=ELEVENLABS_API_KEY=bayit-elevenlabs-api-key:latest'
      - '--update-secrets=BACKEND_CORS_ORIGINS=bayit-backend-cors-origins:latest'
      - '--update-secrets=FRONTEND_URL=bayit-frontend-url:latest'
      - '--update-secrets=FRONTEND_WEB_URL=bayit-frontend-web-url:latest'
      - '--update-secrets=GCS_BUCKET_NAME=bayit-gcs-bucket-name:latest'
      - '--update-secrets=TMDB_API_KEY=bayit-tmdb-api-key:latest'
      - '--update-secrets=CHROMECAST_RECEIVER_APP_ID=bayit-chromecast-receiver-id:latest'

      # Casting Feature Configuration
      - '--update-env-vars=CAST_ENABLE_AIRPLAY=true'
      - '--update-env-vars=CAST_ENABLE_CHROMECAST=true'

images:
  - 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/bayit-backend:latest'

substitutions:
  _REGION: 'us-east1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'

timeout: '2400s'
