steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:latest']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bayit-backend-production'
      - '--image=gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=300'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--update-secrets=CSRF_ENABLED=csrf-enabled:latest'

images:
  - 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/bayit-backend:latest'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'

timeout: '2400s'
