steps:
  # Run tests before building
  - name: "python:3.11-slim"
    entrypoint: bash
    args:
      - "-c"
      - |
        cd backend
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction
        poetry run pytest tests/ -v --tb=short -x
    id: "run-tests"
    waitFor: ["-"]

  # Build and push using Kaniko (handles auth automatically)
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--dockerfile=backend/Dockerfile"
      - "--context=dir://backend"
      - "--destination=us-east1-docker.pkg.dev/$PROJECT_ID/bayit-plus/backend:$BUILD_ID"
      - "--destination=us-east1-docker.pkg.dev/$PROJECT_ID/bayit-plus/backend:${_ENVIRONMENT}"
      - "--destination=us-east1-docker.pkg.dev/$PROJECT_ID/bayit-plus/backend:latest"
      - "--cache=true"
      - "--cache-ttl=24h"
    id: "build-and-push"
    waitFor: ["run-tests"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    waitFor: ["build-and-push"]
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "us-east1-docker.pkg.dev/$PROJECT_ID/bayit-plus/backend:$BUILD_ID"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "${_MEMORY}"
      - "--cpu"
      - "${_CPU}"
      - "--timeout"
      - "300"
      - "--max-instances"
      - "${_MAX_INSTANCES}"
      - "--min-instances"
      - "${_MIN_INSTANCES}"
      - "--concurrency"
      - "80"
      - "--port"
      - "8080"
      - "--cpu-boost"
      - "--set-env-vars"
      - "API_V1_PREFIX=/api/v1,STORAGE_TYPE=gcs,DEBUG=false,GCP_PROJECT_ID=bayit-plus,SPEECH_TO_TEXT_PROVIDER=elevenlabs,LIVE_TRANSLATION_PROVIDER=google,CDN_BASE_URL=https://cdn.bayit.tv,GCS_UPLOAD_TIMEOUT_SECONDS=600,GCS_UPLOAD_CHUNK_SIZE_MB=8,GCS_UPLOAD_MAX_RETRIES=5,GCS_UPLOAD_RETRY_INITIAL_DELAY_SECONDS=1.0,GCS_UPLOAD_RETRY_MAX_DELAY_SECONDS=60.0,KIDS_CONTENT_CACHE_TTL_MINUTES=15,KIDS_CONTENT_MIN_RELEVANCE_SCORE=0.3,KIDS_CONTENT_SAFE_SEARCH_ENABLED=true,KIDS_CONTENT_DEFAULT_AGE_MAX=12,SENTRY_ENVIRONMENT=${_ENVIRONMENT},SENTRY_TRACES_SAMPLE_RATE=0.2,LOG_LEVEL=INFO,CORRELATION_ID_HEADER=X-Correlation-ID,REQUEST_TIMEOUT_WARNING_MS=5000,OLORIN_DUBBING_ENABLED=false,OLORIN_SEMANTIC_SEARCH_ENABLED=false,OLORIN_CULTURAL_CONTEXT_ENABLED=false,OLORIN_RECAP_ENABLED=false,PODCAST_TRANSLATION_ENABLED=true,PODCAST_TRANSLATION_POLL_INTERVAL=300,PODCAST_TRANSLATION_MAX_CONCURRENT=2,PINECONE_ENVIRONMENT=us-east-1-aws,PINECONE_INDEX_NAME=olorin-content,EMBEDDING_MODEL=text-embedding-3-small,EMBEDDING_DIMENSIONS=1536,DUBBING_MAX_CONCURRENT_SESSIONS=100,DUBBING_SESSION_TIMEOUT_MINUTES=120,DUBBING_TARGET_LATENCY_MS=2000,RECAP_MAX_CONTEXT_TOKENS=8000,RECAP_WINDOW_DEFAULT_MINUTES=15,RECAP_SUMMARY_MAX_TOKENS=300,CULTURAL_REFERENCE_CACHE_TTL_HOURS=24,CULTURAL_DETECTION_MIN_CONFIDENCE=0.7,PARTNER_DEFAULT_RATE_LIMIT_RPM=60,PARTNER_WEBHOOK_TIMEOUT_SECONDS=10.0"
      - "--set-secrets"
      - "SECRET_KEY=bayit-secret-key:latest,MONGODB_URL=mongodb-url:latest,MONGODB_DB_NAME=mongodb-db-name:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,STRIPE_PRICE_BASIC=stripe-price-basic:latest,STRIPE_PRICE_PREMIUM=stripe-price-premium:latest,STRIPE_PRICE_FAMILY=stripe-price-family:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GOOGLE_REDIRECT_URI=google-redirect-uri:latest,ELEVENLABS_API_KEY=elevenlabs-api-key:latest,ELEVENLABS_HEBREW_VOICE_ID=elevenlabs-hebrew-voice-id:latest,ELEVENLABS_ENGLISH_VOICE_ID=elevenlabs-english-voice-id:latest,OPENAI_API_KEY=bayit-openai-api-key:latest,TWILIO_ACCOUNT_SID=bayit-twilio-account-sid:latest,TWILIO_AUTH_TOKEN=bayit-twilio-auth-token:latest,TWILIO_PHONE_NUMBER=bayit-twilio-phone-number:latest,GCS_BUCKET_NAME=gcs-bucket-name:latest,BACKEND_CORS_ORIGINS=backend-cors-origins:latest,OPENSUBTITLES_API_KEY=opensubtitles-api-key:latest,ALLOWED_AUDIO_DOMAINS=bayit-allowed-audio-domains:latest,LIBRARIAN_DAILY_AUDIT_CRON=bayit-librarian-daily-audit-cron:latest,LIBRARIAN_DAILY_AUDIT_TIME=bayit-librarian-daily-audit-time:latest,LIBRARIAN_DAILY_AUDIT_MODE=bayit-librarian-daily-audit-mode:latest,LIBRARIAN_DAILY_AUDIT_COST=bayit-librarian-daily-audit-cost:latest,LIBRARIAN_DAILY_AUDIT_STATUS=bayit-librarian-daily-audit-status:latest,LIBRARIAN_DAILY_AUDIT_DESCRIPTION=bayit-librarian-daily-audit-description:latest,LIBRARIAN_WEEKLY_AUDIT_CRON=bayit-librarian-weekly-audit-cron:latest,LIBRARIAN_WEEKLY_AUDIT_TIME=bayit-librarian-weekly-audit-time:latest,LIBRARIAN_WEEKLY_AUDIT_MODE=bayit-librarian-weekly-audit-mode:latest,LIBRARIAN_WEEKLY_AUDIT_COST=bayit-librarian-weekly-audit-cost:latest,LIBRARIAN_WEEKLY_AUDIT_STATUS=bayit-librarian-weekly-audit-status:latest,LIBRARIAN_WEEKLY_AUDIT_DESCRIPTION=bayit-librarian-weekly-audit-description:latest,LIBRARIAN_MAX_ITERATIONS=bayit-librarian-max-iterations:latest,LIBRARIAN_DEFAULT_BUDGET_USD=bayit-librarian-default-budget-usd:latest,LIBRARIAN_MIN_BUDGET_USD=bayit-librarian-min-budget-usd:latest,LIBRARIAN_MAX_BUDGET_USD=bayit-librarian-max-budget-usd:latest,LIBRARIAN_BUDGET_STEP_USD=bayit-librarian-budget-step-usd:latest,LIBRARIAN_REPORTS_LIMIT=bayit-librarian-reports-limit:latest,LIBRARIAN_ACTIONS_LIMIT=bayit-librarian-actions-limit:latest,LIBRARIAN_ACTIVITY_PAGE_SIZE=bayit-librarian-activity-page-size:latest,LIBRARIAN_ID_TRUNCATE_LENGTH=bayit-librarian-id-truncate-length:latest,LIBRARIAN_MODAL_MAX_HEIGHT=bayit-librarian-modal-max-height:latest,SERIES_LINKER_TITLE_SIMILARITY_THRESHOLD=bayit-series-linker-title-similarity:latest,SERIES_LINKER_AUTO_LINK_CONFIDENCE_THRESHOLD=bayit-series-linker-auto-link-confidence:latest,SERIES_LINKER_AUTO_LINK_BATCH_SIZE=bayit-series-linker-batch-size:latest,SERIES_LINKER_DUPLICATE_RESOLUTION_STRATEGY=bayit-series-linker-duplicate-strategy:latest,SERIES_LINKER_CREATE_MISSING_SERIES=bayit-series-linker-create-missing:latest,JEWISH_NEWS_CACHE_TTL_MINUTES=bayit-jewish-news-cache-ttl:latest,JEWISH_NEWS_SYNC_INTERVAL_MINUTES=bayit-jewish-news-sync-interval:latest,JEWISH_NEWS_REQUEST_TIMEOUT_SECONDS=bayit-jewish-news-timeout:latest,HEBCAL_API_BASE_URL=bayit-hebcal-api-url:latest,SEFARIA_API_BASE_URL=bayit-sefaria-api-url:latest,JEWISH_CALENDAR_CACHE_TTL_HOURS=bayit-jewish-calendar-cache-ttl:latest,COMMUNITY_SEARCH_RADIUS_MILES=bayit-community-search-radius:latest,COMMUNITY_DEFAULT_REGION=bayit-community-default-region:latest,US_JEWISH_REGIONS=bayit-us-jewish-regions:latest,COMMUNITY_SCRAPE_INTERVAL_HOURS=bayit-community-scrape-interval:latest,YUTORAH_RSS_URL=bayit-yutorah-rss-url:latest,CHABAD_MULTIMEDIA_RSS_URL=bayit-chabad-multimedia-rss-url:latest,TORAHANYTIME_RSS_URL=bayit-torahanytime-rss-url:latest,PICOVOICE_ACCESS_KEY=picovoice-access-key:latest,TMDB_API_KEY=tmdb-api-key:latest,TMDB_API_TOKEN=tmdb-api-token:latest,SENTRY_DSN=sentry-dsn:latest,PINECONE_API_KEY=olorin-pinecone-api-key:latest,PARTNER_API_KEY_SALT=olorin-partner-api-key-salt:latest"
    id: "deploy-cloud-run"

  # Health check after deployment
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    waitFor: ["deploy-cloud-run"]
    args:
      - "-c"
      - |
        set -e
        echo "Waiting for service to be ready..."
        sleep 30

        # Get service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Service URL: $SERVICE_URL"

        # Health check with retries
        MAX_RETRIES=5
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if curl -sf "$SERVICE_URL/health" -o /dev/null; then
            echo "Health check passed!"
            exit 0
          fi
          RETRY_COUNT=$((RETRY_COUNT + 1))
          echo "Health check attempt $RETRY_COUNT failed, retrying in 10s..."
          sleep 10
        done

        echo "Health check failed after $MAX_RETRIES attempts"

        # Get previous revision for potential rollback
        PREV_REVISION=$(gcloud run revisions list \
          --service=${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(name)' \
          --limit=2 | tail -1)

        if [ -n "$PREV_REVISION" ]; then
          echo "Rolling back to previous revision: $PREV_REVISION"
          gcloud run services update-traffic ${_SERVICE_NAME} \
            --region=${_REGION} \
            --to-revisions=$PREV_REVISION=100
          echo "Rollback completed"
        fi

        exit 1
    id: "health-check"

# Substitutions for flexibility (can be overridden in trigger)
substitutions:
  _REGION: "us-east1"
  _MEMORY: "2Gi"
  _CPU: "2"
  _MAX_INSTANCES: "10"
  _MIN_INSTANCES: "1"
  _ENVIRONMENT: "production"
  _SERVICE_NAME: "bayit-plus-backend"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
