/**
 * SubtitleLanguageList Component
 * List of available subtitle languages
 */

import { View, Text, Pressable, ActivityIndicator, StyleSheet } from 'react-native'
import { useTranslation } from 'react-i18next'
import { z } from 'zod'
import { platformClass, platformStyle } from '@/utils/platformClass'
import { SubtitleTrack, getLanguageInfo } from '@/types/subtitle'

// Zod schema for props
const SubtitleLanguageListPropsSchema = z.object({
  availableLanguages: z.array(z.any()),
  currentLanguage: z.string().nullable(),
  enabled: z.boolean(),
  isLoading: z.boolean(),
  onLanguageSelect: z.function().args(z.string()).returns(z.void()),
  onDisable: z.function().args().returns(z.void()),
})

export type SubtitleLanguageListProps = z.infer<typeof SubtitleLanguageListPropsSchema>

export default function SubtitleLanguageList({
  availableLanguages,
  currentLanguage,
  enabled,
  isLoading,
  onLanguageSelect,
  onDisable,
}: SubtitleLanguageListProps) {
  const { t } = useTranslation()

  // Validate props in development
  if (process.env.NODE_ENV === 'development') {
    SubtitleLanguageListPropsSchema.parse({
      availableLanguages,
      currentLanguage,
      enabled,
      isLoading,
      onLanguageSelect,
      onDisable,
    })
  }

  const stopPropagation = (e: any) => {
    e.stopPropagation()
    e.preventDefault()
  }

  const handleLanguagePress = (language: string) => (e: any) => {
    e?.stopPropagation?.()
    onLanguageSelect(language)
  }

  const handleDisablePress = (e: any) => {
    e?.stopPropagation?.()
    onDisable()
  }

  return (
    <>
      {/* Off option */}
      <Pressable
        onPress={handleDisablePress}
        onClick={stopPropagation}
        onMouseDown={stopPropagation}
        className={platformClass('flex-row items-center justify-between p-3 rounded-lg border bg-black/20')}
        style={({ pressed }) => [
          !enabled ? styles.optionActive : styles.optionInactive,
          { opacity: pressed ? 0.7 : 1 },
        ]}
      >
        <Text className="text-sm font-medium" style={[!enabled ? styles.textActive : styles.textInactive]}>
          {t('subtitles.off')}
        </Text>
        {!enabled && <View className="w-2 h-2 rounded-full bg-purple-500 ml-2" />}
      </Pressable>

      {/* Available languages */}
      {isLoading ? (
        <View className="flex-row items-center justify-center p-6 gap-2">
          <ActivityIndicator size="small" color="#8b5cf6" />
          <Text className="text-zinc-400 text-sm">
            {t('common.loading', 'Loading...')}
          </Text>
        </View>
      ) : availableLanguages.length > 0 ? (
        availableLanguages.map((track: SubtitleTrack) => {
          const langInfo = getLanguageInfo(track.language)
          const isActive = track.language === currentLanguage

          return (
            <Pressable
              key={track.id}
              onPress={handleLanguagePress(track.language)}
              onClick={stopPropagation}
              onMouseDown={stopPropagation}
              className={platformClass('flex-row items-center justify-between p-3 rounded-lg border bg-black/20 mt-1')}
              style={({ pressed }) => [
                isActive ? styles.optionActive : styles.optionInactive,
                { opacity: pressed ? 0.7 : 1 },
              ]}
            >
              <Text className="text-xl mr-2">{langInfo?.flag || '🌐'}</Text>
              <View className="flex-1">
                <Text className="text-sm font-medium" style={[isActive ? styles.textActive : styles.textInactive]}>
                  {track.language_name}
                </Text>
                {track.is_auto_generated && (
                  <Text className="text-zinc-400 text-xs mt-0.5">
                    {t('subtitles.autoGenerated')}
                  </Text>
                )}
              </View>
              {isActive && <View className="w-2 h-2 rounded-full bg-purple-500 ml-2" />}
            </Pressable>
          )
        })
      ) : (
        <View
          onClick={stopPropagation}
          onMouseDown={stopPropagation}
          onMouseUp={stopPropagation}
          className={platformClass(
            'flex-row items-center p-3 rounded-lg border border-white/10 bg-black/20 cursor-default'
          )}
          style={platformStyle({
            web: { pointerEvents: 'none', userSelect: 'none' },
            native: {},
          })}
        >
          <Text className="text-xl mr-2">🚫</Text>
          <Text className="text-zinc-400 text-sm font-medium">
            {t('subtitles.none', 'None')}
          </Text>
        </View>
      )}
    </>
  )
}

const styles = StyleSheet.create({
  optionActive: {
    borderColor: '#c084fc',
    backgroundColor: 'rgba(168, 85, 247, 0.2)',
  },
  optionInactive: {
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  textActive: {
    color: '#a855f7',
    fontWeight: '600',
  },
  textInactive: {
    color: '#a1a1aa',
  },
});
