/**
 * SubtitleLanguageList Component
 * List of available subtitle languages
 */

import { View, Text, Pressable, ActivityIndicator, StyleSheet } from 'react-native'
import { useTranslation } from 'react-i18next'
import { z } from 'zod'
import { colors, spacing, borderRadius } from '@bayit/shared/theme'
import { SubtitleTrack, getLanguageInfo } from '@/types/subtitle'

// Zod schema for props
const SubtitleLanguageListPropsSchema = z.object({
  availableLanguages: z.array(z.any()),
  currentLanguage: z.string().nullable(),
  enabled: z.boolean(),
  isLoading: z.boolean(),
  onLanguageSelect: z.function().args(z.string()).returns(z.void()),
  onDisable: z.function().args().returns(z.void()),
})

export type SubtitleLanguageListProps = z.infer<typeof SubtitleLanguageListPropsSchema>

export default function SubtitleLanguageList({
  availableLanguages,
  currentLanguage,
  enabled,
  isLoading,
  onLanguageSelect,
  onDisable,
}: SubtitleLanguageListProps) {
  const { t } = useTranslation()

  // Validate props in development
  if (process.env.NODE_ENV === 'development') {
    SubtitleLanguageListPropsSchema.parse({
      availableLanguages,
      currentLanguage,
      enabled,
      isLoading,
      onLanguageSelect,
      onDisable,
    })
  }

  const stopPropagation = (e: any) => {
    e.stopPropagation()
    e.preventDefault()
  }

  const handleLanguagePress = (language: string) => (e: any) => {
    e?.stopPropagation?.()
    onLanguageSelect(language)
  }

  const handleDisablePress = (e: any) => {
    e?.stopPropagation?.()
    onDisable()
  }

  return (
    <>
      {/* Off option */}
      <Pressable
        onPress={handleDisablePress}
        onClick={stopPropagation}
        onMouseDown={stopPropagation}
        style={({ pressed }) => [
          styles.option,
          !enabled ? styles.optionActive : styles.optionInactive,
          { opacity: pressed ? 0.7 : 1 },
        ]}
      >
        <Text style={[styles.optionText, !enabled ? styles.textActive : styles.textInactive]}>
          {t('subtitles.off')}
        </Text>
        {!enabled && <View style={styles.activeIndicator} />}
      </Pressable>

      {/* Available languages */}
      {isLoading ? (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={styles.loadingText}>
            {t('common.loading', 'Loading...')}
          </Text>
        </View>
      ) : availableLanguages.length > 0 ? (
        availableLanguages.map((track: SubtitleTrack) => {
          const langInfo = getLanguageInfo(track.language)
          const isActive = track.language === currentLanguage

          return (
            <Pressable
              key={track.id}
              onPress={handleLanguagePress(track.language)}
              onClick={stopPropagation}
              onMouseDown={stopPropagation}
              style={({ pressed }) => [
                styles.option,
                styles.languageOption,
                isActive ? styles.optionActive : styles.optionInactive,
                { opacity: pressed ? 0.7 : 1 },
              ]}
            >
              <Text style={styles.flagText}>{langInfo?.flag || '🌐'}</Text>
              <View style={styles.languageInfo}>
                <Text style={[styles.languageName, isActive ? styles.textActive : styles.textInactive]}>
                  {track.language_name}
                </Text>
                {track.is_auto_generated && (
                  <Text style={styles.autoText}>
                    {t('subtitles.autoGenerated')}
                  </Text>
                )}
              </View>
              {isActive && <View style={styles.activeIndicator} />}
            </Pressable>
          )
        })
      ) : (
        <View
          onClick={stopPropagation}
          onMouseDown={stopPropagation}
          onMouseUp={stopPropagation}
          style={styles.emptyOption}
        >
          <Text style={styles.flagText}>🚫</Text>
          <Text style={styles.emptyText}>
            {t('subtitles.none', 'None')}
          </Text>
        </View>
      )}
    </>
  )
}

const styles = StyleSheet.create({
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md - 4,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    backgroundColor: colors.glass,
  },
  languageOption: {
    marginTop: spacing.xs,
  },
  optionActive: {
    borderColor: colors.primaryLight,
    backgroundColor: colors.glassPurpleLight,
  },
  optionInactive: {
    borderColor: colors.glassBorderWhite,
  },
  optionText: {
    fontSize: 14,
    fontWeight: '500',
  },
  textActive: {
    color: colors.primary,
    fontWeight: '600',
  },
  textInactive: {
    color: colors.textSecondary,
  },
  activeIndicator: {
    width: 8,
    height: 8,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    marginLeft: spacing.sm,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg + spacing.sm,
    gap: spacing.sm,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: 14,
  },
  flagText: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  languageInfo: {
    flex: 1,
  },
  languageName: {
    fontSize: 14,
    fontWeight: '500',
  },
  autoText: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  emptyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md - 4,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorderWhite,
    backgroundColor: colors.glass,
    cursor: 'default',
    pointerEvents: 'none',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '500',
  },
});
