/**
 * Lucide React Shims for React Native (tvOS)
 *
 * Re-exports lucide-react-native icons for components that import from 'lucide-react'.
 * This allows web components to work on tvOS without modification.
 *
 * NOTE: All icons use lucide-react-native - NO emojis allowed per Olorin guidelines.
 */

// Re-export from lucide-react-native
export {
  Search,
  Menu,
  X,
  Shield,
  Home,
  Tv,
  Film,
  Radio,
  Mic,
  Star,
  User,
  Settings,
  Play,
  Pause,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Heart,
  Clock,
  Calendar,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  SkipForward,
  SkipBack,
  Loader,
  Check,
  AlertCircle,
  Info,
  MessageCircle,
  Send,
  Trash2,
  Edit2,
  Plus,
  Minus,
  Globe,
  Sun,
  Moon,
  Download,
  Upload,
  Share2,
  Copy,
  ExternalLink,
  Bookmark,
  List,
  Grid,
  Filter,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Bell,
  BellOff,
  Mail,
  Phone,
  MapPin,
  Zap,
  Award,
  Gift,
  Sparkles,
  Coffee,
  Book,
  Headphones,
  Camera,
  Image,
  Video,
  Music,
  Folder,
  File,
  Archive,
  Tag,
  Hash,
  AtSign,
  BookOpen,
  Mic2,
  LogOut,
  Baby,
  Circle,
  Subtitles,
  Monitor,
  Shuffle,
  Minimize2,
  Maximize2,
  Grid3x3,
  Sidebar,
} from 'lucide-react-native';

// Default export for backward compatibility
export default {
  Search: require('lucide-react-native').Search,
  Menu: require('lucide-react-native').Menu,
  X: require('lucide-react-native').X,
  Shield: require('lucide-react-native').Shield,
  Home: require('lucide-react-native').Home,
  Tv: require('lucide-react-native').Tv,
  Film: require('lucide-react-native').Film,
  Radio: require('lucide-react-native').Radio,
  Mic: require('lucide-react-native').Mic,
  Star: require('lucide-react-native').Star,
  User: require('lucide-react-native').User,
  Settings: require('lucide-react-native').Settings,
  Play: require('lucide-react-native').Play,
  Pause: require('lucide-react-native').Pause,
};
