steps:
  # NOTE: This file is for manual builds from the backend/ directory.
  # For automated deployments, use the root cloudbuild.yaml instead.
  # The Git trigger "Deploy-After-Push" is configured to use root cloudbuild.yaml.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID', '-f', 'Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=300'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--port=8080'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--update-secrets=CSRF_ENABLED=csrf-enabled:latest'

images:
  - 'gcr.io/$PROJECT_ID/bayit-backend:$BUILD_ID'

timeout: '1800s'

substitutions:
  _SERVICE_NAME: 'bayit-plus-backend'
  _REGION: 'us-east1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
