/** Navigation and button styles for TVVoiceDemo - split from TVVoiceDemo.styles.ts */
import { StyleSheet } from 'react-native';

export const navStyles = StyleSheet.create({
  samplesContainer: {
    width: '100%',
    marginBottom: 30,
  },
  samplesTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#A855F7',
    marginBottom: 16,
    textAlign: 'center',
  },
  sampleCommand: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    padding: 16,
    marginBottom: 12,
    gap: 12,
  },
  sampleCommandFocused: {
    backgroundColor: 'rgba(168, 85, 247, 0.3)',
    borderColor: '#A855F7',
    transform: [{ scale: 1.05 }],
  },
  sampleIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(168, 85, 247, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: '#A855F7',
    textAlign: 'center',
    lineHeight: 40,
  },
  sampleText: {
    fontSize: 22,
    fontWeight: '500',
    color: '#FFFFFF',
    flex: 1,
  },
  tryButton: {
    backgroundColor: '#A855F7',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'transparent',
    paddingVertical: 16,
    paddingHorizontal: 40,
  },
  tryButtonFocused: {
    backgroundColor: '#C084FC',
    borderColor: '#FFFFFF',
    transform: [{ scale: 1.05 }],
  },
  tryButtonText: {
    fontSize: 28,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 30,
    left: 60,
    right: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 20,
  },
  skipButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#AAAAAA',
    paddingVertical: 14,
  },
  skipButtonFocused: {
    borderColor: '#A855F7',
    backgroundColor: 'rgba(168, 85, 247, 0.2)',
  },
  skipButtonText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#AAAAAA',
    textAlign: 'center',
  },
  nextButton: {
    flex: 1,
    backgroundColor: '#A855F7',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    paddingVertical: 14,
  },
  nextButtonFocused: {
    backgroundColor: '#C084FC',
    borderColor: '#FFFFFF',
  },
  nextButtonText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  doneButton: {
    flex: 1,
    backgroundColor: '#A855F7',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    paddingVertical: 14,
  },
  doneButtonFocused: {
    backgroundColor: '#C084FC',
    borderColor: '#FFFFFF',
  },
  doneButtonText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
});
