"""Tests for Jinja2 template engine."""

import pytest
from jinja2 import TemplateNotFound
from olorin_email.template.engine import TemplateEngine, RenderedEmail


def test_render_simple_template_succeeds(email_settings, template_dir):
    """Test rendering a simple template with context."""
    email_settings.EMAIL_TEMPLATE_DIRS = [template_dir]
    engine = TemplateEngine(email_settings)
    result = engine.render("simple.html.j2", {"name": "John", "message": "Welcome!"})

    assert isinstance(result, RenderedEmail)
    assert "Hello John" in result.html
    assert "Welcome!" in result.html


def test_plain_text_generation_from_html(email_settings, template_dir):
    """Test that plain text is generated by stripping HTML tags."""
    email_settings.EMAIL_TEMPLATE_DIRS = [template_dir]
    engine = TemplateEngine(email_settings)
    result = engine.render("simple.html.j2", {"name": "John", "message": "Test"})

    assert "Hello John" in result.plain_text
    assert "Test" in result.plain_text
    assert "<html>" not in result.plain_text
    assert "<h1>" not in result.plain_text


def test_text_direction_detection(email_settings, template_dir):
    """Test RTL and LTR direction detection for various languages."""
    email_settings.EMAIL_TEMPLATE_DIRS = [template_dir]
    engine = TemplateEngine(email_settings)

    # RTL languages
    for lang in ["he", "ar", "fa"]:
        result = engine.render("i18n.html.j2", {"lang": lang})
        assert "dir='rtl'" in result.html

    # LTR languages
    for lang in ["en", "es", "fr"]:
        result = engine.render("i18n.html.j2", {"lang": lang})
        assert "dir='ltr'" in result.html


def test_translate_function_passthrough(email_settings, template_dir):
    """Test that t() function works as passthrough by default."""
    email_settings.EMAIL_TEMPLATE_DIRS = [template_dir]
    engine = TemplateEngine(email_settings)
    result = engine.render("i18n.html.j2", {"lang": "en"})

    assert "welcome" in result.html


def test_custom_translate_function(email_settings, template_dir):
    """Test that custom translation function is used."""
    email_settings.EMAIL_TEMPLATE_DIRS = [template_dir]

    def translate(key: str) -> str:
        return {"welcome": "Bienvenue"}.get(key, key)

    engine = TemplateEngine(email_settings, translate_fn=translate)
    result = engine.render("i18n.html.j2", {"lang": "fr"})

    assert "Bienvenue" in result.html


def test_adding_template_directory(email_settings, tmp_path):
    """Test adding a template directory at runtime."""
    engine = TemplateEngine(email_settings)

    new_dir = tmp_path / "new_templates"
    new_dir.mkdir()
    (new_dir / "runtime.html.j2").write_text("<html>{{ content }}</html>")

    engine.add_template_dir(str(new_dir))
    result = engine.render("runtime.html.j2", {"content": "Dynamic"})

    assert "Dynamic" in result.html


def test_adding_nonexistent_directory_logs_warning(email_settings, caplog):
    """Test that adding non-existent directory logs warning."""
    engine = TemplateEngine(email_settings)
    engine.add_template_dir("/nonexistent/path")

    assert "Cannot add non-existent template directory" in caplog.text


def test_rendering_nonexistent_template_raises_error(email_settings):
    """Test that rendering non-existent template raises error."""
    engine = TemplateEngine(email_settings)

    with pytest.raises(TemplateNotFound):
        engine.render("nonexistent.html.j2", {})


def test_html_to_plain_text_conversions(email_settings):
    """Test HTML to plain text conversion edge cases."""
    engine = TemplateEngine(email_settings)

    # BR tags to newlines
    assert engine._html_to_plain_text("Line 1<br>Line 2") == "Line 1\nLine 2"

    # Paragraph tags to double newlines
    plain = engine._html_to_plain_text("<p>Para 1</p><p>Para 2</p>")
    assert "Para 1\n\nPara 2" in plain

    # Remove all tags
    assert engine._html_to_plain_text("<strong>Bold</strong> <em>italic</em>") == "Bold italic"

    # Consolidate excessive newlines
    plain = engine._html_to_plain_text("<p>A</p>\n\n\n\n<p>B</p>")
    assert "\n\n\n" not in plain


def test_get_text_direction_comprehensive(email_settings):
    """Test text direction for multiple languages."""
    engine = TemplateEngine(email_settings)

    # RTL languages
    for lang in ["he", "ar", "fa", "ur", "yi"]:
        assert engine._get_text_direction(lang) == "rtl"

    # LTR languages
    for lang in ["en", "es", "fr", "de", "zh", "ja"]:
        assert engine._get_text_direction(lang) == "ltr"
