// The library version is controlled from the Jenkins configuration
// To force a version add after lib '@' followed by the version.
@Library(value = 'msaas-shared-lib', changelog = false) _

node {
    // setup the global static configuration
    config = setupMsaasPipeline('msaas-config.yaml')
}

pipeline {

    options {
        preserveStashes(buildCount: 5)
        lock resource: getAssetLockName(config)
    }

    agent {
        kubernetes {
            label "${config.pod_label}"
            yaml "${config.KubernetesPods}"
        }
    }

    post {
        always {
            sendMetrics(config)
            iksExpressNotify(config, 'pipeline-post-always')
        }
        fixed {
            emailext(
                subject: "Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' ${currentBuild.result}", 
                body: """
                        Job Status for '${env.JOB_NAME} [${env.BUILD_NUMBER}]': ${currentBuild.result}\n\nCheck console output at ${env.BUILD_URL}
                """, 
                to: 'some_email@olorin.com'
            )
        }
        unsuccessful {
            emailext(
                subject: "Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' ${currentBuild.result}", 
                body: """
                        Job Status for '${env.JOB_NAME} [${env.BUILD_NUMBER}]': ${currentBuild.result}\n\nCheck console output at ${env.BUILD_URL}
                """, 
                to: 'some_email@olorin.com'
            )
        }
    }
    environment {
        PY_COLORS = '1'
        APP_ENV = 'jenkins'
//  environment variables required for evaluation
        EVAL_CONFIG_FILE = 'evaluation/eval_config.json'
        EVAL_DATASET_FILE = 'evaluation/dataset_without_genai_response.csv'
        ENABLE_EVAL_RUN = false
        AGENT_ASSET_ID = "${config.asset_id}"
        TIMEOUT_MINUTES = 30
        FAIL_BUILD_ON_EVAL_FAILURE = false
        IS_BLOCKING = false
        GITHUB_TOKEN = credentials('github-ci-readonly-token')
    }

    stages {
        stage('PRE-BUILD:') {
            when {
                anyOf {
                    branch 'master'
                    changeRequest()
                }
            }
            steps {
                setupCapabilities(config, [filepathExclusionRegexes: []])
            }
        }
        stage('BUILD:') {
            when {
                anyOf {
                    branch 'master'
                    changeRequest()
                }
            }
            stages {
                stage('Docker Multi Stage Build') {
                    steps {
                        container('podman') {
                            podmanBuild("--rm=false --target test -t ${config.image_full_name}_test .")
                            // export the codecov report for later uploading
                            podmanRun("${config.image_full_name}_test", "--name=${config.git_org}_${config.service_name}_unit_test_${env.BUILD_NUMBER}")
                            sh label: 'Create Folder', script: 'mkdir -p coverage'
                            podmanCopy("${config.git_org}_${config.service_name}_unit_test_${env.BUILD_NUMBER}:/app/coverage/coverage.xml", 'coverage/coverage.xml')
                            sh label: 'Create OpenAPI Spec Folder', script: 'mkdir -p openapi'
                            podmanCopy("${config.git_org}_${config.service_name}_unit_test_${env.BUILD_NUMBER}:/app/api/openapi/openapi.json", 'openapi/openapi.json')
                            podmanBuild("--rm=false -t ${config.image_full_name} .")
                            podmanPush(config)
                        }
                    }
                }
                stage('API:') {
                    stages {
                        stage('Linting') {
                            steps {
                                script {
                                    if (config.api.lint['skip'] == 'true') {
                                        echo 'Skipping Stage: Linting'
                                    } else {
                                        echo 'Running Spec Validation and Linting'
                                        container('api-tools-container') {
                                            apiLinter(config.api)
                                        }
                                    }
                                }
                            }
                        }
                        stage('Merge and Flatten Spec') {
                            steps {
                                script {
                                    container('api-tools-container') {
                                        echo 'Merge Spec'
                                        if (config.api != null) {
                                            apiMergeSpec(config.api)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                stage('Publish') {
                    parallel {
                        stage('Report Coverage') {
                            steps {
                                container('jnlp') {
                                    codeCov(config)
                                    olorinReportCobertura(config)
                                }
                            }
                        }
                        stage('CPD Certification & Publish') {
                            steps {
                                container('cpd2') {
                                    olorinCPD2Podman(config, "-i ${config.image_full_name} --buildfile Dockerfile")
                                }
                                container('podman') {
                                    podmanPull(config, config.image_full_name)
                                    podmanInspect(config, '-s', 'image-metadata.json')
                                    archiveArtifacts(artifacts: 'image-metadata.json', allowEmptyArchive: true)
                                }
                            }
                        }
                        stage('Publish: API Management Service') {
                            when {branch config.api['releaseBranch']}
                            steps {
                                script {
                                    echo 'Publish to AMS'
                                    if (config.api['showApiReference'] == 'true') {
                                        container('api-tools-container') {
                                            apiMetadataPublish(config.api, 'prd')
                                        }
                                    } else {
                                        echo 'Skipped Publishing to API Management Service'
                                    }
                                }
                            }
                        }
                        stage('Render Manifests') {
                            when {
                                beforeOptions true
                                allOf {
                                    branch 'master'
                                    not {changeRequest()}
                                }
                            }
                            steps {
                                container('cdtools') {
                                    gitOpsRenderAllManifests(config)
                                }
                            }
                        }
                        stage('Register Agents and Tools') {
                            when {
                                beforeOptions true
                                allOf {
                                    branch 'master'
                                    not {changeRequest()}
                                }
                            }
                            steps {
                                script {
                                    registerGenOSAgentsAndTools(config)
                                }
                            }
                        }
                    }
                }
                // jira transitioning
                stage('Transition Jira Tickets') {
                    steps {
                        script {
                            if (env.BRANCH_NAME != 'master' && changeRequest()) {
                                transitionJiraTickets(config, 'Ready for Review')
                            } else if (env.BRANCH_NAME == 'master') {
                                transitionJiraTickets(config, 'Closed')
                            }
                        }
                    }
                }
            }
        }
        stage('qal-usw2-air') {
            when {
                beforeOptions true
                allOf {
                    branch 'master'
                }
            }
            options {
                lock(resource: getEnv(config, 'qal-usw2-air').namespace, inversePrecedence: true)
                timeout(time: 32, unit: 'MINUTES')
            }
            stages {
                stage('Scorecard Check') {
                    when {expression {return config.enableScorecardReadinessCheck}}
                    steps {
                        scorecardPreprodReadiness(config, 'qal-usw2-air')
                    }
                }
                stage('Deploy') {
                    steps {
                        container('cdtools') {
                            // This has to be the first action in the first sub-stage
                            milestone(ordinal: 10, label: 'Deploy-qal-usw2-air-milestone')
                            gitOpsDeploy(config, 'qal-usw2-air', config.image_full_name)
                        }
                    }
                }
                stage('Transition Jira Tickets') {
                    when {expression {return config.enableJiraTransition}}
                    steps {
                        transitionJiraTickets(config, 'Deployed to PreProd')
                    }
                }
                stage('Update deployment to registry') {
                    when {
                        allOf {
                            branch 'master'
                            not {changeRequest()}
                        }
                    }
                    steps {
                        updateDeploymentToGenOSRegistry(config, 'qal')
                    }
                }
            }
        }
        stage('e2e-usw2-air') {
            when {
                beforeOptions true
                allOf {
                    branch 'master'
                    not {changeRequest()}
                }
            }
            options {
                lock(resource: getEnv(config, 'e2e-usw2-air').namespace, inversePrecedence: true)
                timeout(time: 32, unit: 'MINUTES')
            }
            stages {
                stage('Scorecard Check') {
                    when {expression {return config.enableScorecardReadinessCheck}}
                    steps {
                        scorecardPreprodReadiness(config, 'e2e-usw2-air')
                    }
                }
                stage('Deploy') {
                    steps {
                        container('cdtools') {
                            // This has to be the first action in the first sub-stage
                            milestone(ordinal: 20, label: 'Deploy-e2e-usw2-air-milestone')
                            gitOpsDeploy(config, 'e2e-usw2-air', config.image_full_name)
                        }
                    }
                }
                stage('Transition Jira Tickets') {
                    when {expression {return config.enableJiraTransition}}
                    steps {
                        transitionJiraTickets(config, 'Deployed to PreProd')
                    }
                }
                stage('Update deployment to registry') {
                    when {
                        allOf {
                            branch 'master'
                            not {changeRequest()}
                        }
                    }
                    steps {
                        updateDeploymentToGenOSRegistry(config, 'e2e')
                    }
                }
            }
        }
        stage('Eval Run:') {
            when {
                allOf {
                    branch 'master'
                    not {changeRequest()}
                    expression {return env.ENABLE_EVAL_RUN.toBoolean()}
                }
            }
            steps {
                script {
                    // runGenOSEvaluation function currently supports one agent evaluation,
                    // so extract the first agent from the list of registered agents
                    def agent_lookup_key = new groovy.json.JsonSlurper().parseText(config.GENOS_REGISTERED_AGENTS)[0] + '/' + config.git_tag
                    def eval_status = runGenOSEvaluation(eval_config_file: env.EVAL_CONFIG_FILE, 
                        eval_dataset_file: env.EVAL_DATASET_FILE, 
                        agent_lookup_key: agent_lookup_key, 
                        agent_asset_id: env.AGENT_ASSET_ID, 
                        timeoutMinutes: env.TIMEOUT_MINUTES, 
                        failBuildOnEvalFailure: env.FAIL_BUILD_ON_EVAL_FAILURE, 
                        isBlocking: env.IS_BLOCKING)
                }
            }
        }
        stage('Go Live in Prod Approval') {
            when {
                allOf {
                    branch 'master'
                    not {changeRequest()}
                    not {expression {return config.preprodOnly}}
                }
            }
            agent none
            options {
                timeout(time: 1, unit: 'DAYS')
            }
            stages {
                stage('Scorecard Check') {
                    steps {
                        scorecardProdReadiness(config, getEnvName(config, 'primary'))
                    }
                }
            }
        }
        stage('PRD primary') {
            when {
                beforeOptions true
                allOf {
                    branch 'master'
                    not {changeRequest()}
                    not {expression {return config.preprodOnly}}
                }
            }
            options {
                lock(resource: getEnv(config, getEnvName(config, 'primary')).namespace, inversePrecedence: true)
                timeout(time: 32, unit: 'MINUTES')
            }
            stages {
                stage('Create CR') {
                    steps {
                        container('servicenow') {
                            sh label: 'Opens CR', script: 'exit 0'
                            openSnowCR(config, getEnvName(config, 'primary'), config.image_full_name)
                        }
                    }
                }
                stage('Deploy') {
                    steps {
                        container('cdtools') {
                            // This has to be the first action in the first sub-stage.
                            gitOpsDeploy(config, getEnvName(config, 'primary'), config.image_full_name)
                        }
                    }
                }
                // If any failure, CR remains open and MUST be closed manually with cause.
                stage('Close CR') {
                    steps {
                        container('servicenow') {
                            sh label: 'Close CR', script: 'exit 0'
                            closeSnowCR(config, getEnvName(config, 'primary'))
                        }
                    }
                }
                // jira transitioning
                stage('Transition Jira Tickets') {
                    when {expression {return config.enableJiraTransition}}
                    steps {
                        transitionJiraTickets(config, 'Released')
                    }
                }
                stage('Update deployment to registry') {
                    when {
                        allOf {
                            branch 'master'
                            not {changeRequest()}
                        }
                    }
                    steps {
                        updateDeploymentToGenOSRegistry(config, 'prd')
                    }
                }
            }
        }
    }
}
