"""
Snowflake schema constants for ALL 333 columns in TRANSACTIONS_ENRICHED table.
This ensures complete compliance with the actual schema structure.

Generated from: Tx Table Schema.csv
Total columns: 333
"""

from typing import Dict, Set


# Metadata Fields (26 columns)
BIN_CREATED_TIME = "BIN_CREATED_TIME"  # TIMESTAMP_NTZ(9)
BIN_UPLOADED_TO_SNOWFLAKE = "BIN_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
CALCULATED_PROPS_UPLOADED_TO_SNOWFLAKE = "CALCULATED_PROPS_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE = "EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
ENRICHED_TXS_UPLOADED_TO_SNOWFLAKE = "ENRICHED_TXS_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
EVENT_TYPE = "EVENT_TYPE"  # VARCHAR(16777216)
HLR_CREATED_TIME = "HLR_CREATED_TIME"  # TIMESTAMP_NTZ(9)
HLR_UPLOADED_TO_SNOWFLAKE = "HLR_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_DISPUTE_UPLOADED_TO_SNOWFLAKE = "LAST_DISPUTE_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE = "LAST_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_MAXMIND_MIN_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE = "LAST_MAXMIND_MIN_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_NSURE_INITIATED_REFUND_UPLOADED_TO_SNOWFLAKE = "LAST_NSURE_INITIATED_REFUND_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_REPORTED_ATTACK_UPLOADED_TO_SNOWFLAKE = "LAST_REPORTED_ATTACK_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
LAST_RETRY_UPLOADED_TO_SNOWFLAKE = "LAST_RETRY_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
MAXMIND_CREATED_TIME = "MAXMIND_CREATED_TIME"  # TIMESTAMP_NTZ(9)
MAXMIND_UPLOADED_TO_SNOWFLAKE = "MAXMIND_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
MERCHANT_LAST_DECISION_UPLOADED_TO_SNOWFLAKE = "MERCHANT_LAST_DECISION_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
MODEL_MANAGER_TX_FEATURES_UPLOADED_TO_SNOWFLAKE = "MODEL_MANAGER_TX_FEATURES_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
NSURE_LAST_DECISION_UPLOADED_TO_SNOWFLAKE = "NSURE_LAST_DECISION_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
RECIPIENT_EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE = "RECIPIENT_EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
SMTPV_BUYER_EMAIL_CREATED_TIME = "SMTPV_BUYER_EMAIL_CREATED_TIME"  # TIMESTAMP_NTZ(9)
SMTPV_BUYER_EMAIL_UPLOADED_TO_SNOWFLAKE = "SMTPV_BUYER_EMAIL_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
TABLE_RECORD_CREATED_AT = "TABLE_RECORD_CREATED_AT"  # VARCHAR(26)
TABLE_RECORD_UPDATED_AT = "TABLE_RECORD_UPDATED_AT"  # VARCHAR(26)
TX_REFUND_UPLOADED_TO_SNOWFLAKE = "TX_REFUND_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)
TX_UPLOADED_TO_SNOWFLAKE = "TX_UPLOADED_TO_SNOWFLAKE"  # TIMESTAMP_NTZ(9)

# Identity Fields (44 columns)
ALL_RECIPIENT_EMAILS = "ALL_RECIPIENT_EMAILS"  # ARRAY
ALL_RECIPIENT_EMAILS_NORMALIZED = "ALL_RECIPIENT_EMAILS_NORMALIZED"  # ARRAY
BUYER_EMAIL_DOMAIN = "BUYER_EMAIL_DOMAIN"  # VARCHAR(16777216)
BUYER_EMAIL_SMTPV_RESPONSE = "BUYER_EMAIL_SMTPV_RESPONSE"  # VARIANT
DATE_OF_BIRTH = "DATE_OF_BIRTH"  # TIMESTAMP_NTZ(9)
DAYS_FROM_FIRST_EMAIL_SEEN_TO_TX = "DAYS_FROM_FIRST_EMAIL_SEEN_TO_TX"  # NUMBER(24,6)
DAYS_FROM_FIRST_PAYPAL_EMAIL_SEEN_TO_TX = "DAYS_FROM_FIRST_PAYPAL_EMAIL_SEEN_TO_TX"  # NUMBER(24,6)
DAYS_FROM_FIRST_RECIPIENT_EMAIL_SEEN_TO_TX = "DAYS_FROM_FIRST_RECIPIENT_EMAIL_SEEN_TO_TX"  # NUMBER(24,6)
DISTANCE_PHONE_PRODUCT__MODEL_FEATURE = "DISTANCE_PHONE_PRODUCT__MODEL_FEATURE"  # FLOAT
EMAIL = "EMAIL"  # VARCHAR(16777216)
EMAIL_DATA_THIRD_PARTY_RISK_SCORE = "EMAIL_DATA_THIRD_PARTY_RISK_SCORE"  # FLOAT
EMAIL_FIRST_SEEN = "EMAIL_FIRST_SEEN"  # TIMESTAMP_NTZ(9)
EMAIL_NORMALIZED = "EMAIL_NORMALIZED"  # VARCHAR(16777216)
EMAIL_VALIDATION_ADDITIONAL_DATA = "EMAIL_VALIDATION_ADDITIONAL_DATA"  # OBJECT
EMAIL_VALIDATION_CREATED = "EMAIL_VALIDATION_CREATED"  # TIMESTAMP_NTZ(9)
FIRST_NAME = "FIRST_NAME"  # VARCHAR(16777216)
FIRST_RECIPIENT_EMAIL = "FIRST_RECIPIENT_EMAIL"  # VARCHAR(16777216)
FIRST_RECIPIENT_PHONE = "FIRST_RECIPIENT_PHONE"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_FIRST_NAME = "FIRST_USER_COMPLETED_KYC_FIRST_NAME"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_LAST_NAME = "FIRST_USER_COMPLETED_KYC_LAST_NAME"  # VARCHAR(16777216)
FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATE_OF_BIRTH = "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATE_OF_BIRTH"  # VARCHAR(16777216)
HLR_PHONE_COUNTRY_CODE = "HLR_PHONE_COUNTRY_CODE"  # VARCHAR(16777216)
IS_DELIVERY_METHOD_EMAIL_ONLY = "IS_DELIVERY_METHOD_EMAIL_ONLY"  # NUMBER(1,0)
IS_DISPOSABLE_EMAIL = "IS_DISPOSABLE_EMAIL"  # NUMBER(38,0)
IS_EMAIL_VERIFIED_BY_THIRD_PARTY = "IS_EMAIL_VERIFIED_BY_THIRD_PARTY"  # NUMBER(38,0)
IS_EMAIL_VERIFIED__MODEL_FEATURE = "IS_EMAIL_VERIFIED__MODEL_FEATURE"  # NUMBER(38,0)
IS_FREEMAIL = "IS_FREEMAIL"  # NUMBER(38,0)
IS_PERSONAL_EMAIL = "IS_PERSONAL_EMAIL"  # NUMBER(38,0)
IS_RECIPIENT_EMAIL_DISPOSABLE = "IS_RECIPIENT_EMAIL_DISPOSABLE"  # NUMBER(38,0)
IS_RECIPIENT_EMAIL_FREEMAIL = "IS_RECIPIENT_EMAIL_FREEMAIL"  # NUMBER(38,0)
IS_RECIPIENT_EMAIL_PERSONAL = "IS_RECIPIENT_EMAIL_PERSONAL"  # NUMBER(38,0)
IS_RECIPIENT_EMAIL_VALID = "IS_RECIPIENT_EMAIL_VALID"  # NUMBER(38,0)
IS_RECIPIENT_EMAIL_VERIFIED_BY_THIRD_PARTY = "IS_RECIPIENT_EMAIL_VERIFIED_BY_THIRD_PARTY"  # NUMBER(38,0)
IS_VALID_EMAIL = "IS_VALID_EMAIL"  # NUMBER(38,0)
LAST_NAME = "LAST_NAME"  # VARCHAR(16777216)
PAYPAL_EMAIL = "PAYPAL_EMAIL"  # VARCHAR(16777216)
PAYPAL_EMAIL_FIRST_SEEN = "PAYPAL_EMAIL_FIRST_SEEN"  # TIMESTAMP_NTZ(9)
PERSONAL_INFO_EMAIL_TO_RECIPIENT_EMAIL_LOCAL_PARTS_DISTANCE = "PERSONAL_INFO_EMAIL_TO_RECIPIENT_EMAIL_LOCAL_PARTS_DISTANCE"  # FLOAT
PHONE_COUNTRY_CODE = "PHONE_COUNTRY_CODE"  # VARCHAR(16777216)
PHONE_NUMBER = "PHONE_NUMBER"  # VARCHAR(16777216)
RECIPIENT_EMAIL_FIRST_SEEN = "RECIPIENT_EMAIL_FIRST_SEEN"  # TIMESTAMP_NTZ(9)
RECIPIENT_EMAIL_VALIDATION_ADDITIONAL_DATA = "RECIPIENT_EMAIL_VALIDATION_ADDITIONAL_DATA"  # OBJECT
RECIPIENT_EMAIL_VALIDATION_CREATED = "RECIPIENT_EMAIL_VALIDATION_CREATED"  # TIMESTAMP_NTZ(9)
UNIQUE_USER_ID = "UNIQUE_USER_ID"  # VARCHAR(16777216)

# Transaction Fields (11 columns)
AUTHORIZATION_STAGE = "AUTHORIZATION_STAGE"  # VARCHAR(16777216)
BUYER_RETRY_TX_ID = "BUYER_RETRY_TX_ID"  # VARCHAR(16777216)
NSURE_RETRY_TX_ID = "NSURE_RETRY_TX_ID"  # VARCHAR(16777216)
NSURE_UNIQUE_TX_ID = "NSURE_UNIQUE_TX_ID"  # VARCHAR(16777216)
ORIGINAL_TX_ID = "ORIGINAL_TX_ID"  # VARCHAR(16777216)
STORE_FIRST_TX_TIMESTAMP = "STORE_FIRST_TX_TIMESTAMP"  # NUMBER(38,0)
STORE_ID = "STORE_ID"  # VARCHAR(16777216)
SURROGATE_APP_TX_ID = "SURROGATE_APP_TX_ID"  # VARCHAR(16777216)
TX_DATETIME = "TX_DATETIME"  # TIMESTAMP_NTZ(9)
TX_ID_KEY = "TX_ID_KEY"  # VARCHAR(16777216)
TX_TIMESTAMP_MS = "TX_TIMESTAMP_MS"  # NUMBER(38,0)

# Payment Fields (38 columns)
BIN = "BIN"  # VARCHAR(16777216)
BIN_ADDITIONAL_DATA = "BIN_ADDITIONAL_DATA"  # OBJECT
BIN_COUNTRY_CODE = "BIN_COUNTRY_CODE"  # VARCHAR(16777216)
BIN_RISKY_GMV = "BIN_RISKY_GMV"  # FLOAT
CARD_BRAND = "CARD_BRAND"  # VARCHAR(16777216)
CARD_CATEGORY = "CARD_CATEGORY"  # VARCHAR(16777216)
CARD_HOLDER_NAME = "CARD_HOLDER_NAME"  # VARCHAR(16777216)
CARD_ISSUER = "CARD_ISSUER"  # VARCHAR(16777216)
CARD_ISSUER_NORMALIZED = "CARD_ISSUER_NORMALIZED"  # VARCHAR(16777216)
CARD_TYPE = "CARD_TYPE"  # VARCHAR(16777216)
DAYS_FROM_FIRST_PAYMENT_METHOD_ATTEMPT_TO_TX = "DAYS_FROM_FIRST_PAYMENT_METHOD_ATTEMPT_TO_TX"  # FLOAT
DISTANCE_PAYMENT_METHOD_PRODUCT__MODEL_FEATURE = "DISTANCE_PAYMENT_METHOD_PRODUCT__MODEL_FEATURE"  # FLOAT
FIRST_PAYMENT_METHOD_ATTEMPT_DATETIME = "FIRST_PAYMENT_METHOD_ATTEMPT_DATETIME"  # TIMESTAMP_NTZ(9)
GROUP_NEW_PAYMENT_METHODS_GMV_IN_LAST_DAY = "GROUP_NEW_PAYMENT_METHODS_GMV_IN_LAST_DAY"  # FLOAT
GROUP_NEW_PAYMENT_METHODS_TXS_IN_LAST_DAY = "GROUP_NEW_PAYMENT_METHODS_TXS_IN_LAST_DAY"  # FLOAT
IS_CARD_COMMERCIAL = "IS_CARD_COMMERCIAL"  # NUMBER(38,0)
IS_CARD_PREPAID = "IS_CARD_PREPAID"  # NUMBER(38,0)
IS_NEW_PAYMENT_METHOD__MODEL_FEATURE = "IS_NEW_PAYMENT_METHOD__MODEL_FEATURE"  # NUMBER(38,0)
IS_PAYPAL_ADDRESS_CONFIRMED = "IS_PAYPAL_ADDRESS_CONFIRMED"  # NUMBER(38,0)
IS_PROCESSOR_REJECTED_DUE_TO_FRAUD = "IS_PROCESSOR_REJECTED_DUE_TO_FRAUD"  # NUMBER(38,0)
IS_PROCESSOR_REPORTED_STOLEN_CARD = "IS_PROCESSOR_REPORTED_STOLEN_CARD"  # NUMBER(38,0)
LAST_FOUR = "LAST_FOUR"  # VARCHAR(16777216)
PAID_AMOUNT_CURRENCY = "PAID_AMOUNT_CURRENCY"  # VARCHAR(16777216)
PAID_AMOUNT_VALUE_IN_CURRENCY = "PAID_AMOUNT_VALUE_IN_CURRENCY"  # FLOAT
PAYMENT_METHOD = "PAYMENT_METHOD"  # VARCHAR(16777216)
PAYMENT_METHOD_COUNTRY_CODE = "PAYMENT_METHOD_COUNTRY_CODE"  # VARCHAR(16777216)
PAYMENT_METHOD_DETAILS_ADDITIONAL_DATA = "PAYMENT_METHOD_DETAILS_ADDITIONAL_DATA"  # OBJECT
PAYMENT_METHOD_INTERNAL_IDENTIFIER = "PAYMENT_METHOD_INTERNAL_IDENTIFIER"  # VARCHAR(16777216)
PAYMENT_METHOD_TOKEN = "PAYMENT_METHOD_TOKEN"  # VARCHAR(16777216)
PAYPAL_LOCAL_PART_TO_NAME_DISTANCE = "PAYPAL_LOCAL_PART_TO_NAME_DISTANCE"  # FLOAT
PROCESSOR = "PROCESSOR"  # VARCHAR(16777216)
PROCESSOR_MERCHANT_IDENTIFIER = "PROCESSOR_MERCHANT_IDENTIFIER"  # VARCHAR(16777216)
PRODUCTION_PAYMENT_METHOD_TYPE = "PRODUCTION_PAYMENT_METHOD_TYPE"  # VARCHAR(16777216)
RAW_PROCESSOR_REQUEST = "RAW_PROCESSOR_REQUEST"  # VARIANT
RAW_PROCESSOR_REQUEST_SOURCE = "RAW_PROCESSOR_REQUEST_SOURCE"  # VARCHAR(16777216)
RAW_PROCESSOR_RESPONSE = "RAW_PROCESSOR_RESPONSE"  # VARIANT
RAW_PROCESSOR_RESPONSE_SOURCE = "RAW_PROCESSOR_RESPONSE_SOURCE"  # VARCHAR(16777216)
SEASONALITY_ATTUNED_BIN_RISKY_GMV__MODEL_FEATURE = "SEASONALITY_ATTUNED_BIN_RISKY_GMV__MODEL_FEATURE"  # FLOAT

# Network Fields (33 columns)
ALL_RECIPIENT_INFO = "ALL_RECIPIENT_INFO"  # ARRAY
ASN = "ASN"  # VARCHAR(16777216)
BUYER_NAME_TO_PIPL_NAME_DISTANCE = "BUYER_NAME_TO_PIPL_NAME_DISTANCE"  # FLOAT
COUNT_DISPUTES = "COUNT_DISPUTES"  # NUMBER(18,0)
DISPUTES = "DISPUTES"  # ARRAY
DISTANCE_IP_PRODUCT__MODEL_FEATURE = "DISTANCE_IP_PRODUCT__MODEL_FEATURE"  # FLOAT
FIPP_IS_INCOGNITO = "FIPP_IS_INCOGNITO"  # BOOLEAN
FIPP_VISITOR_ID = "FIPP_VISITOR_ID"  # VARCHAR(16777216)
FIRST_DISPUTE_DATETIME = "FIRST_DISPUTE_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_NON_FRAUD_DISPUTE_DATETIME = "FIRST_NON_FRAUD_DISPUTE_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_RECIPIENT_INFO = "FIRST_RECIPIENT_INFO"  # VARIANT
IP = "IP"  # VARCHAR(16777216)
IP_ADDRESS_INFO = "IP_ADDRESS_INFO"  # VARIANT
IP_COUNTRY_CODE = "IP_COUNTRY_CODE"  # VARCHAR(16777216)
ISP = "ISP"  # VARCHAR(16777216)
ISP_ARRAY = "ISP_ARRAY"  # VARIANT
IS_DISPUTED_NON_FRAUD_TX = "IS_DISPUTED_NON_FRAUD_TX"  # NUMBER(1,0)
IS_LAST_DISPUTE_FRAUD_RELATED_REASON = "IS_LAST_DISPUTE_FRAUD_RELATED_REASON"  # NUMBER(38,0)
IS_RULE_PARTICIPATING_IN_LFS_PO = "IS_RULE_PARTICIPATING_IN_LFS_PO"  # NUMBER(38,0)
LAST_DISPUTED_ITEM_BUYER_NOTES = "LAST_DISPUTED_ITEM_BUYER_NOTES"  # VARCHAR(16777216)
LAST_DISPUTE_AMOUNT = "LAST_DISPUTE_AMOUNT"  # VARIANT
LAST_DISPUTE_DATETIME = "LAST_DISPUTE_DATETIME"  # TIMESTAMP_NTZ(9)
LAST_DISPUTE_DECISION = "LAST_DISPUTE_DECISION"  # VARCHAR(16777216)
LAST_DISPUTE_REASON = "LAST_DISPUTE_REASON"  # VARCHAR(16777216)
LAST_DISPUTE_SELLER_BUYER_CHAT = "LAST_DISPUTE_SELLER_BUYER_CHAT"  # VARIANT
LAST_DISPUTE_SOURCE = "LAST_DISPUTE_SOURCE"  # VARIANT
LAST_DISPUTE_STATUS = "LAST_DISPUTE_STATUS"  # VARCHAR(16777216)
MAXMIND_IP_RISK_SCORE = "MAXMIND_IP_RISK_SCORE"  # FLOAT
PIPL_INFO_AGE = "PIPL_INFO_AGE"  # VARIANT
PIPL_INFO_PERSON = "PIPL_INFO_PERSON"  # VARIANT
PRODUCT_COUNTRY_CODES = "PRODUCT_COUNTRY_CODES"  # VARIANT
PROD_RECIPIENT_INFO = "PROD_RECIPIENT_INFO"  # VARIANT
RULE_DESCRIPTION = "RULE_DESCRIPTION"  # VARCHAR(16777216)

# Device Fields (13 columns)
APP_INSTALL_DATETIME = "APP_INSTALL_DATETIME"  # TIMESTAMP_NTZ(9)
DAYS_FROM_FIRST_APP_INSTALL_TO_TX = "DAYS_FROM_FIRST_APP_INSTALL_TO_TX"  # NUMBER(24,6)
DEVICE_APP_INSTALL_SDK_VERSION = "DEVICE_APP_INSTALL_SDK_VERSION"  # VARCHAR(16777216)
DEVICE_ID = "DEVICE_ID"  # VARCHAR(16777216)
DEVICE_MODEL = "DEVICE_MODEL"  # VARCHAR(16777216)
DEVICE_OS_VERSION = "DEVICE_OS_VERSION"  # VARCHAR(16777216)
DEVICE_TYPE = "DEVICE_TYPE"  # VARCHAR(16777216)
IS_DEVICE_ID_AUTHENTICATED = "IS_DEVICE_ID_AUTHENTICATED"  # NUMBER(38,0)
IS_ROUTER_DEVICE_ID_AUTHENTICATED = "IS_ROUTER_DEVICE_ID_AUTHENTICATED"  # BOOLEAN
PARSED_USER_AGENT = "PARSED_USER_AGENT"  # OBJECT
SESSION_INFO_ADDITIONAL_DATA = "SESSION_INFO_ADDITIONAL_DATA"  # OBJECT
SESSION_INFO_LANGUAGE = "SESSION_INFO_LANGUAGE"  # VARCHAR(16777216)
USER_AGENT = "USER_AGENT"  # VARCHAR(16777216)

# Risk Fields (15 columns)
DAYS_FROM_STORE_CREATION__MODEL_FEATURE = "DAYS_FROM_STORE_CREATION__MODEL_FEATURE"  # FLOAT
DAYS_FROM_STORE_FIRST_TX__MODEL_FEATURE = "DAYS_FROM_STORE_FIRST_TX__MODEL_FEATURE"  # FLOAT
DISTANCE_LOCAL_PRODUCT__MODEL_FEATURE = "DISTANCE_LOCAL_PRODUCT__MODEL_FEATURE"  # FLOAT
GROUP_MAX_MAXMIND_RISK_SCORE = "GROUP_MAX_MAXMIND_RISK_SCORE"  # FLOAT
ISSUER_RISKY_GMV__MODEL_FEATURE = "ISSUER_RISKY_GMV__MODEL_FEATURE"  # FLOAT
IS_FREE_MAIL__MODEL_FEATURE = "IS_FREE_MAIL__MODEL_FEATURE"  # NUMBER(38,0)
IS_NEW_BUYER__MODEL_FEATURE = "IS_NEW_BUYER__MODEL_FEATURE"  # NUMBER(38,0)
LAST_MAXMIND_MIN_FRAUD_ALERT_NEW_RISK_SCORE = "LAST_MAXMIND_MIN_FRAUD_ALERT_NEW_RISK_SCORE"  # FLOAT
MAXMIND_RISK_SCORE = "MAXMIND_RISK_SCORE"  # FLOAT
MODEL_APPROVAL_THRESHOLD = "MODEL_APPROVAL_THRESHOLD"  # FLOAT
MODEL_DECISION = "MODEL_DECISION"  # VARCHAR(16777216)
MODEL_SCORE = "MODEL_SCORE"  # FLOAT
MODEL_SOFT_APPROVAL_THRESHOLD = "MODEL_SOFT_APPROVAL_THRESHOLD"  # FLOAT
MODEL_VERSION = "MODEL_VERSION"  # VARCHAR(16777216)
PM_COUNTRY_RISKY_GMV__MODEL_FEATURE = "PM_COUNTRY_RISKY_GMV__MODEL_FEATURE"  # FLOAT

# Fraud Fields (23 columns)
COUNT_MERCHANT_DECISIONS = "COUNT_MERCHANT_DECISIONS"  # NUMBER(18,0)
COUNT_NSURE_DECISIONS = "COUNT_NSURE_DECISIONS"  # NUMBER(18,0)
COUNT_TRIGGERED_RULES = "COUNT_TRIGGERED_RULES"  # NUMBER(9,0)
FIRST_NSURE_TX_ATTEMPT_DATETIME = "FIRST_NSURE_TX_ATTEMPT_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_USER_TRIGGERED_KYC_DATETIME = "FIRST_USER_TRIGGERED_KYC_DATETIME"  # TIMESTAMP_NTZ(9)
IS_FRAUD_TX = "IS_FRAUD_TX"  # NUMBER(1,0)
IS_SENT_FOR_NSURE_REVIEW = "IS_SENT_FOR_NSURE_REVIEW"  # NUMBER(1,0)
IS_UNDER_NSURE_LIABILITY = "IS_UNDER_NSURE_LIABILITY"  # NUMBER(1,0)
MERCHANT_DECISIONS = "MERCHANT_DECISIONS"  # ARRAY
MERCHANT_LAST_DECISION = "MERCHANT_LAST_DECISION"  # VARCHAR(16777216)
MERCHANT_LAST_DECISION_DATETIME = "MERCHANT_LAST_DECISION_DATETIME"  # TIMESTAMP_NTZ(9)
NSURE_DECISIONS = "NSURE_DECISIONS"  # ARRAY
NSURE_FIRST_DECISION = "NSURE_FIRST_DECISION"  # VARCHAR(16777216)
NSURE_FIRST_DECISION_DATETIME = "NSURE_FIRST_DECISION_DATETIME"  # TIMESTAMP_NTZ(9)
NSURE_INITIATED_REFUND_DATETIME = "NSURE_INITIATED_REFUND_DATETIME"  # TIMESTAMP_NTZ(9)
NSURE_LAST_DECISION = "NSURE_LAST_DECISION"  # VARCHAR(16777216)
NSURE_LAST_DECISION_DATETIME = "NSURE_LAST_DECISION_DATETIME"  # TIMESTAMP_NTZ(9)
NSURE_SEGMENT_ID = "NSURE_SEGMENT_ID"  # VARCHAR(16777216)
RULE = "RULE"  # VARCHAR(16777216)
RULE_DECISION = "RULE_DECISION"  # VARCHAR(16777216)
SIMULATED_DECISION = "SIMULATED_DECISION"  # VARCHAR(16777216)
TRIGGERED_LFS_RULES = "TRIGGERED_LFS_RULES"  # ARRAY
TRIGGERED_RULES = "TRIGGERED_RULES"  # ARRAY

# Kyc Fields (18 columns)
FIRST_USER_COMPLETED_KYC_ADDRESS_COUNTRY_USER_INPUT = "FIRST_USER_COMPLETED_KYC_ADDRESS_COUNTRY_USER_INPUT"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_CREATE_DATE = "FIRST_USER_COMPLETED_KYC_CREATE_DATE"  # TIMESTAMP_NTZ(9)
FIRST_USER_COMPLETED_KYC_DOCUMENT_TYPE = "FIRST_USER_COMPLETED_KYC_DOCUMENT_TYPE"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_ID_COUNTRY_OF_BIRTH = "FIRST_USER_COMPLETED_KYC_ID_COUNTRY_OF_BIRTH"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_ID_ISSUING_COUNTRY_FROM_DOCS_ARRAY = "FIRST_USER_COMPLETED_KYC_ID_ISSUING_COUNTRY_FROM_DOCS_ARRAY"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_ID_POST_CODE_FROM_DOCS_ARRAY = "FIRST_USER_COMPLETED_KYC_ID_POST_CODE_FROM_DOCS_ARRAY"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_LEVEL_NAME = "FIRST_USER_COMPLETED_KYC_LEVEL_NAME"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_POST_CODE_USER_INPUT = "FIRST_USER_COMPLETED_KYC_POST_CODE_USER_INPUT"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_PROVIDER = "FIRST_USER_COMPLETED_KYC_PROVIDER"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_RESULT = "FIRST_USER_COMPLETED_KYC_RESULT"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_REVIEW_ANSWER_OR_STATUS = "FIRST_USER_COMPLETED_KYC_REVIEW_ANSWER_OR_STATUS"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_STATE_USER_INPUT = "FIRST_USER_COMPLETED_KYC_STATE_USER_INPUT"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_TOWN_USER_INPUT = "FIRST_USER_COMPLETED_KYC_TOWN_USER_INPUT"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_KYC_TYPE = "FIRST_USER_COMPLETED_KYC_TYPE"  # VARCHAR(16777216)
FIRST_USER_COMPLETED_NUM_OF_KYC_ATTEMPTS = "FIRST_USER_COMPLETED_NUM_OF_KYC_ATTEMPTS"  # VARCHAR(16777216)
FIRST_USER_FAILED_KYC_DATETIME = "FIRST_USER_FAILED_KYC_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATETIME = "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATETIME"  # TIMESTAMP_NTZ(9)
KYC_USER_AGE = "KYC_USER_AGE"  # NUMBER(19,6)

# Dispute Fields (10 columns)
COUNT_FRAUD_ALERTS = "COUNT_FRAUD_ALERTS"  # NUMBER(18,0)
COUNT_MAXMIND_MIN_FRAUD_ALERTS = "COUNT_MAXMIND_MIN_FRAUD_ALERTS"  # NUMBER(18,0)
FIRST_FRAUD_ALERT_DATETIME = "FIRST_FRAUD_ALERT_DATETIME"  # TIMESTAMP_NTZ(9)
FRAUD_ALERTS = "FRAUD_ALERTS"  # ARRAY
LAST_FRAUD_ALERT_DATETIME = "LAST_FRAUD_ALERT_DATETIME"  # TIMESTAMP_NTZ(9)
LAST_MAXMIND_MIN_FRAUD_ALERT_DATETIME = "LAST_MAXMIND_MIN_FRAUD_ALERT_DATETIME"  # TIMESTAMP_NTZ(9)
LAST_MAXMIND_MIN_FRAUD_ALERT_REASON_CODE = "LAST_MAXMIND_MIN_FRAUD_ALERT_REASON_CODE"  # VARCHAR(16777216)
MAXMIND_MIN_FRAUD_ALERTS = "MAXMIND_MIN_FRAUD_ALERTS"  # ARRAY
TX_REFUND_DATETIME = "TX_REFUND_DATETIME"  # TIMESTAMP_NTZ(9)
TX_REFUND_REASON = "TX_REFUND_REASON"  # VARCHAR(16777216)

# Hlr Fields (11 columns)
HLR_ADDITIONAL_DATA = "HLR_ADDITIONAL_DATA"  # OBJECT
HLR_CURRENT_NETWORK = "HLR_CURRENT_NETWORK"  # VARCHAR(16777216)
HLR_IS_MOBILE = "HLR_IS_MOBILE"  # NUMBER(38,0)
HLR_IS_PORTED = "HLR_IS_PORTED"  # NUMBER(38,0)
HLR_IS_ROAMING = "HLR_IS_ROAMING"  # NUMBER(38,0)
HLR_IS_VALID = "HLR_IS_VALID"  # NUMBER(38,0)
HLR_NUMBER_TYPE = "HLR_NUMBER_TYPE"  # VARCHAR(16777216)
HLR_NUMBER_VALID = "HLR_NUMBER_VALID"  # NUMBER(38,0)
HLR_ORIGIN_NETWORK = "HLR_ORIGIN_NETWORK"  # VARCHAR(16777216)
HLR_PORTED_NETWORK = "HLR_PORTED_NETWORK"  # VARCHAR(16777216)
HLR_STATUS = "HLR_STATUS"  # VARCHAR(16777216)

# Crypto Fields (4 columns)
DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NATIVE_TX = "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NATIVE_TX"  # FLOAT
DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NON_NATIVE_TX = "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NON_NATIVE_TX"  # FLOAT
DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NATIVE_TX = "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NATIVE_TX"  # FLOAT
DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NON_NATIVE_TX = "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NON_NATIVE_TX"  # FLOAT

# Cart Fields (19 columns)
CART = "CART"  # VARIANT
CART_BRANDS = "CART_BRANDS"  # ARRAY
CART_DELIVERY_METHODS = "CART_DELIVERY_METHODS"  # ARRAY
CART_ITEMS_ARE_GIFTS = "CART_ITEMS_ARE_GIFTS"  # ARRAY
CART_ITEMS_FULFILLMENT = "CART_ITEMS_FULFILLMENT"  # ARRAY
CART_ITEMS_TYPES = "CART_ITEMS_TYPES"  # ARRAY
CART_SKUS = "CART_SKUS"  # ARRAY
CART_USD = "CART_USD"  # VARIANT
CART_WITHOUT_FEE_ITEMS = "CART_WITHOUT_FEE_ITEMS"  # ARRAY
GMV = "GMV"  # FLOAT
GROUP_NEW_BUYERS_GMV_IN_LAST_DAY = "GROUP_NEW_BUYERS_GMV_IN_LAST_DAY"  # FLOAT
GROUP_TX_FAILURE_GMV = "GROUP_TX_FAILURE_GMV"  # FLOAT
MOST_EXPENSIVE_CART_USD_ITEM = "MOST_EXPENSIVE_CART_USD_ITEM"  # VARIANT
PARTNER_MAIN_PRODUCT_TYPE = "PARTNER_MAIN_PRODUCT_TYPE"  # VARCHAR(16777216)
PRODUCT = "PRODUCT"  # VARCHAR(16777216)
PRODUCT_GAMETITLE = "PRODUCT_GAMETITLE"  # VARCHAR(16777216)
PRODUCT_PLATFORM = "PRODUCT_PLATFORM"  # VARCHAR(16777216)
PRODUCT_REGIONS = "PRODUCT_REGIONS"  # VARIANT
PRODUCT_TYPE = "PRODUCT_TYPE"  # VARCHAR(16777216)

# Temporal Fields (11 columns)
CALCULATED_PROPS_CREATED_DATETIME = "CALCULATED_PROPS_CREATED_DATETIME"  # TIMESTAMP_NTZ(9)
DAYS_FROM_FIRST_MERCHANT_ACCEPTANCE_TO_TX = "DAYS_FROM_FIRST_MERCHANT_ACCEPTANCE_TO_TX"  # FLOAT
DAYS_FROM_FIRST_TX_ATTEMPT_TO_TX = "DAYS_FROM_FIRST_TX_ATTEMPT_TO_TX"  # NUMBER(24,6)
DAYS_FROM_FIRST_USER_ACCOUNT_ACTIVITY_DATE_TO_TX = "DAYS_FROM_FIRST_USER_ACCOUNT_ACTIVITY_DATE_TO_TX"  # NUMBER(24,6)
DAYS_FROM_VISITOR_ID_AGE = "DAYS_FROM_VISITOR_ID_AGE"  # FLOAT
FIRST_FRAUD_STATUS_DATETIME = "FIRST_FRAUD_STATUS_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_MERCHANT_ACCEPTED_DATETIME = "FIRST_MERCHANT_ACCEPTED_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_TX_ATTEMPT_DATETIME = "FIRST_TX_ATTEMPT_DATETIME"  # TIMESTAMP_NTZ(9)
FIRST_USER_ACCOUNT_ACTIVITY_DATE = "FIRST_USER_ACCOUNT_ACTIVITY_DATE"  # TIMESTAMP_NTZ(9)
FIRST_USER_TX_EVENT_DATETIME = "FIRST_USER_TX_EVENT_DATETIME"  # TIMESTAMP_NTZ(9)
TX_RECEIVED_DATETIME = "TX_RECEIVED_DATETIME"  # TIMESTAMP_NTZ(9)

# Business Fields (9 columns)
ADDITIONAL_SEGMENTS = "ADDITIONAL_SEGMENTS"  # VARIANT
APP_ID = "APP_ID"  # VARCHAR(16777216)
MERCHANT_KPI_UPDATE_ID = "MERCHANT_KPI_UPDATE_ID"  # VARCHAR(16777216)
MERCHANT_NAME = "MERCHANT_NAME"  # VARCHAR(16777216)
MERCHANT_SEGMENT_ID = "MERCHANT_SEGMENT_ID"  # VARCHAR(16777216)
PARTNER_ID = "PARTNER_ID"  # VARCHAR(16777216)
PARTNER_INDUSTRY = "PARTNER_INDUSTRY"  # VARCHAR(16777216)
PARTNER_NAME = "PARTNER_NAME"  # VARCHAR(16777216)
SIMULATED_SEGMENT_ID = "SIMULATED_SEGMENT_ID"  # VARCHAR(16777216)

# Features Fields (4 columns)
GROUP_NEW_BUYERS_TXS_IN_LAST_DAY = "GROUP_NEW_BUYERS_TXS_IN_LAST_DAY"  # FLOAT
GROUP_TX_FAILURE_COUNT = "GROUP_TX_FAILURE_COUNT"  # FLOAT
PM_ACCEPTED_TXS_COUNT = "PM_ACCEPTED_TXS_COUNT"  # FLOAT
USER_GRAPH_SIZE = "USER_GRAPH_SIZE"  # FLOAT

# Other Fields (44 columns)
AVS = "AVS"  # VARCHAR(16777216)
BILLING_ADDRESS = "BILLING_ADDRESS"  # VARIANT
BUYER_AGE = "BUYER_AGE"  # FLOAT
CALCULATED_PROPS_ID = "CALCULATED_PROPS_ID"  # VARCHAR(16777216)
CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"  # VARCHAR(16777216)
CREDIT_USE = "CREDIT_USE"  # VARIANT
CUSTODIAL_TYPE = "CUSTODIAL_TYPE"  # VARCHAR(16777216)
FAILURE_CATEGORY = "FAILURE_CATEGORY"  # VARCHAR(16777216)
FAILURE_REASON = "FAILURE_REASON"  # VARCHAR(16777216)
FIRST_SIGN_IN_IDENTITY_PROVIDER = "FIRST_SIGN_IN_IDENTITY_PROVIDER"  # VARCHAR(16777216)
IS_ANONYMOUS = "IS_ANONYMOUS"  # NUMBER(1,0)
IS_BTCC_TEST_TX_NOT_REVIEWED_BY_NSURE = "IS_BTCC_TEST_TX_NOT_REVIEWED_BY_NSURE"  # BOOLEAN
IS_DELIVERY_METHOD_CONTAINING_ON_SCREEN = "IS_DELIVERY_METHOD_CONTAINING_ON_SCREEN"  # NUMBER(1,0)
IS_DIGITAL = "IS_DIGITAL"  # NUMBER(1,0)
IS_FAILED_TX = "IS_FAILED_TX"  # NUMBER(1,0)
IS_GIFTING = "IS_GIFTING"  # NUMBER(1,0)
IS_REASSESSED_TX = "IS_REASSESSED_TX"  # NUMBER(38,0)
IS_RECURRING_USER = "IS_RECURRING_USER"  # NUMBER(38,0)
IS_REVIEWED = "IS_REVIEWED"  # NUMBER(1,0)
IS_SOFT_APPROVAL_CANDIDATE = "IS_SOFT_APPROVAL_CANDIDATE"  # VARIANT
IS_SOFT_APPROVED = "IS_SOFT_APPROVED"  # NUMBER(1,0)
IS_SUSPICIOUS_AMOUNT = "IS_SUSPICIOUS_AMOUNT"  # NUMBER(2,0)
IS_THREE_D_SECURE_VERIFIED = "IS_THREE_D_SECURE_VERIFIED"  # NUMBER(38,0)
IS_UNDER_THREE_D_SECURE = "IS_UNDER_THREE_D_SECURE"  # NUMBER(38,0)
IS_USER_FIRST_TX_ATTEMPT = "IS_USER_FIRST_TX_ATTEMPT"  # NUMBER(1,0)
IS_USER_FIRST_TX_EVENT = "IS_USER_FIRST_TX_EVENT"  # NUMBER(1,0)
LAST_REPORTED_ATTACK_ID = "LAST_REPORTED_ATTACK_ID"  # VARCHAR(16777216)
LOCAL_PART_TO_NAME_DISTANCE = "LOCAL_PART_TO_NAME_DISTANCE"  # FLOAT
MILLISECONDS_FROM_SOFT_APPROVED_TO_REASSESSMENT_RESPONSE = "MILLISECONDS_FROM_SOFT_APPROVED_TO_REASSESSMENT_RESPONSE"  # NUMBER(38,0)
NORMALIZED_AVS_RESULT_CODE = "NORMALIZED_AVS_RESULT_CODE"  # VARCHAR(16777216)
NOT_REVIEWED_REASON = "NOT_REVIEWED_REASON"  # VARCHAR(16777216)
PERSONAL_INFO_ADDITIONAL_DATA = "PERSONAL_INFO_ADDITIONAL_DATA"  # OBJECT
PROCESSING_FEE_CURRENCY = "PROCESSING_FEE_CURRENCY"  # VARCHAR(16777216)
PROCESSING_FEE_VALUE_IN_CURRENCY = "PROCESSING_FEE_VALUE_IN_CURRENCY"  # FLOAT
REASSESSMENT_REJECTION_REASON = "REASSESSMENT_REJECTION_REASON"  # VARCHAR(16777216)
REASSESSMENT_RESULT = "REASSESSMENT_RESULT"  # VARCHAR(16777216)
REFUSAL_REASON = "REFUSAL_REASON"  # VARCHAR(16777216)
REJECTION_REASON = "REJECTION_REASON"  # VARCHAR(16777216)
RISK_MODE = "RISK_MODE"  # VARCHAR(16777216)
SELLER_ID = "SELLER_ID"  # VARCHAR(16777216)
SOFT_APPROVAL_POPULATIONS_LIST = "SOFT_APPROVAL_POPULATIONS_LIST"  # VARIANT
THREE_D_SECURE_RESULT = "THREE_D_SECURE_RESULT"  # VARCHAR(16777216)
TRANSACTION_DETAILS_ADDITIONAL_DATA = "TRANSACTION_DETAILS_ADDITIONAL_DATA"  # OBJECT
TX_ADDITIONAL_DATA = "TX_ADDITIONAL_DATA"  # OBJECT


# ============================================================================
# UTILITY MAPPINGS AND FUNCTIONS
# ============================================================================

# NO FIELD MAPPINGS - SCHEMA-LOCKED MODE
# Only valid schema columns allowed - no aliases or mappings permitted

# All column names as a set for validation
ALL_COLUMN_NAMES: Set[str] = {
    "ADDITIONAL_SEGMENTS",
    "ALL_RECIPIENT_EMAILS",
    "ALL_RECIPIENT_EMAILS_NORMALIZED",
    "ALL_RECIPIENT_INFO",
    "APP_ID",
    "APP_INSTALL_DATETIME",
    "ASN",
    "AUTHORIZATION_STAGE",
    "AVS",
    "BILLING_ADDRESS",
    "BIN",
    "BIN_ADDITIONAL_DATA",
    "BIN_COUNTRY_CODE",
    "BIN_CREATED_TIME",
    "BIN_RISKY_GMV",
    "BIN_UPLOADED_TO_SNOWFLAKE",
    "BUYER_AGE",
    "BUYER_EMAIL_DOMAIN",
    "BUYER_EMAIL_SMTPV_RESPONSE",
    "BUYER_NAME_TO_PIPL_NAME_DISTANCE",
    "BUYER_RETRY_TX_ID",
    "CALCULATED_PROPS_CREATED_DATETIME",
    "CALCULATED_PROPS_ID",
    "CALCULATED_PROPS_UPLOADED_TO_SNOWFLAKE",
    "CARD_BRAND",
    "CARD_CATEGORY",
    "CARD_HOLDER_NAME",
    "CARD_ISSUER",
    "CARD_ISSUER_NORMALIZED",
    "CARD_TYPE",
    "CART",
    "CART_BRANDS",
    "CART_DELIVERY_METHODS",
    "CART_ITEMS_ARE_GIFTS",
    "CART_ITEMS_FULFILLMENT",
    "CART_ITEMS_TYPES",
    "CART_SKUS",
    "CART_USD",
    "CART_WITHOUT_FEE_ITEMS",
    "CLIENT_REQUEST_ID",
    "COUNT_DISPUTES",
    "COUNT_FRAUD_ALERTS",
    "COUNT_MAXMIND_MIN_FRAUD_ALERTS",
    "COUNT_MERCHANT_DECISIONS",
    "COUNT_NSURE_DECISIONS",
    "COUNT_TRIGGERED_RULES",
    "CREDIT_USE",
    "CUSTODIAL_TYPE",
    "DATE_OF_BIRTH",
    "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NATIVE_TX",
    "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NON_NATIVE_TX",
    "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NATIVE_TX",
    "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NON_NATIVE_TX",
    "DAYS_FROM_FIRST_APP_INSTALL_TO_TX",
    "DAYS_FROM_FIRST_EMAIL_SEEN_TO_TX",
    "DAYS_FROM_FIRST_MERCHANT_ACCEPTANCE_TO_TX",
    "DAYS_FROM_FIRST_PAYMENT_METHOD_ATTEMPT_TO_TX",
    "DAYS_FROM_FIRST_PAYPAL_EMAIL_SEEN_TO_TX",
    "DAYS_FROM_FIRST_RECIPIENT_EMAIL_SEEN_TO_TX",
    "DAYS_FROM_FIRST_TX_ATTEMPT_TO_TX",
    "DAYS_FROM_FIRST_USER_ACCOUNT_ACTIVITY_DATE_TO_TX",
    "DAYS_FROM_STORE_CREATION__MODEL_FEATURE",
    "DAYS_FROM_STORE_FIRST_TX__MODEL_FEATURE",
    "DAYS_FROM_VISITOR_ID_AGE",
    "DEVICE_APP_INSTALL_SDK_VERSION",
    "DEVICE_ID",
    "DEVICE_MODEL",
    "DEVICE_OS_VERSION",
    "DEVICE_TYPE",
    "DISPUTES",
    "DISTANCE_IP_PRODUCT__MODEL_FEATURE",
    "DISTANCE_LOCAL_PRODUCT__MODEL_FEATURE",
    "DISTANCE_PAYMENT_METHOD_PRODUCT__MODEL_FEATURE",
    "DISTANCE_PHONE_PRODUCT__MODEL_FEATURE",
    "EMAIL",
    "EMAIL_DATA_THIRD_PARTY_RISK_SCORE",
    "EMAIL_FIRST_SEEN",
    "EMAIL_NORMALIZED",
    "EMAIL_VALIDATION_ADDITIONAL_DATA",
    "EMAIL_VALIDATION_CREATED",
    "EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE",
    "ENRICHED_TXS_UPLOADED_TO_SNOWFLAKE",
    "EVENT_TYPE",
    "FAILURE_CATEGORY",
    "FAILURE_REASON",
    "FIPP_IS_INCOGNITO",
    "FIPP_VISITOR_ID",
    "FIRST_DISPUTE_DATETIME",
    "FIRST_FRAUD_ALERT_DATETIME",
    "FIRST_FRAUD_STATUS_DATETIME",
    "FIRST_MERCHANT_ACCEPTED_DATETIME",
    "FIRST_NAME",
    "FIRST_NON_FRAUD_DISPUTE_DATETIME",
    "FIRST_NSURE_TX_ATTEMPT_DATETIME",
    "FIRST_PAYMENT_METHOD_ATTEMPT_DATETIME",
    "FIRST_RECIPIENT_EMAIL",
    "FIRST_RECIPIENT_INFO",
    "FIRST_RECIPIENT_PHONE",
    "FIRST_SIGN_IN_IDENTITY_PROVIDER",
    "FIRST_TX_ATTEMPT_DATETIME",
    "FIRST_USER_ACCOUNT_ACTIVITY_DATE",
    "FIRST_USER_COMPLETED_KYC_ADDRESS_COUNTRY_USER_INPUT",
    "FIRST_USER_COMPLETED_KYC_CREATE_DATE",
    "FIRST_USER_COMPLETED_KYC_DOCUMENT_TYPE",
    "FIRST_USER_COMPLETED_KYC_FIRST_NAME",
    "FIRST_USER_COMPLETED_KYC_ID_COUNTRY_OF_BIRTH",
    "FIRST_USER_COMPLETED_KYC_ID_ISSUING_COUNTRY_FROM_DOCS_ARRAY",
    "FIRST_USER_COMPLETED_KYC_ID_POST_CODE_FROM_DOCS_ARRAY",
    "FIRST_USER_COMPLETED_KYC_LAST_NAME",
    "FIRST_USER_COMPLETED_KYC_LEVEL_NAME",
    "FIRST_USER_COMPLETED_KYC_POST_CODE_USER_INPUT",
    "FIRST_USER_COMPLETED_KYC_PROVIDER",
    "FIRST_USER_COMPLETED_KYC_RESULT",
    "FIRST_USER_COMPLETED_KYC_REVIEW_ANSWER_OR_STATUS",
    "FIRST_USER_COMPLETED_KYC_STATE_USER_INPUT",
    "FIRST_USER_COMPLETED_KYC_TOWN_USER_INPUT",
    "FIRST_USER_COMPLETED_KYC_TYPE",
    "FIRST_USER_COMPLETED_NUM_OF_KYC_ATTEMPTS",
    "FIRST_USER_FAILED_KYC_DATETIME",
    "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATETIME",
    "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATE_OF_BIRTH",
    "FIRST_USER_TRIGGERED_KYC_DATETIME",
    "FIRST_USER_TX_EVENT_DATETIME",
    "FRAUD_ALERTS",
    "GMV",
    "GROUP_MAX_MAXMIND_RISK_SCORE",
    "GROUP_NEW_BUYERS_GMV_IN_LAST_DAY",
    "GROUP_NEW_BUYERS_TXS_IN_LAST_DAY",
    "GROUP_NEW_PAYMENT_METHODS_GMV_IN_LAST_DAY",
    "GROUP_NEW_PAYMENT_METHODS_TXS_IN_LAST_DAY",
    "GROUP_TX_FAILURE_COUNT",
    "GROUP_TX_FAILURE_GMV",
    "HLR_ADDITIONAL_DATA",
    "HLR_CREATED_TIME",
    "HLR_CURRENT_NETWORK",
    "HLR_IS_MOBILE",
    "HLR_IS_PORTED",
    "HLR_IS_ROAMING",
    "HLR_IS_VALID",
    "HLR_NUMBER_TYPE",
    "HLR_NUMBER_VALID",
    "HLR_ORIGIN_NETWORK",
    "HLR_PHONE_COUNTRY_CODE",
    "HLR_PORTED_NETWORK",
    "HLR_STATUS",
    "HLR_UPLOADED_TO_SNOWFLAKE",
    "IP",
    "IP_ADDRESS_INFO",
    "IP_COUNTRY_CODE",
    "ISP",
    "ISP_ARRAY",
    "ISSUER_RISKY_GMV__MODEL_FEATURE",
    "IS_ANONYMOUS",
    "IS_BTCC_TEST_TX_NOT_REVIEWED_BY_NSURE",
    "IS_CARD_COMMERCIAL",
    "IS_CARD_PREPAID",
    "IS_DELIVERY_METHOD_CONTAINING_ON_SCREEN",
    "IS_DELIVERY_METHOD_EMAIL_ONLY",
    "IS_DEVICE_ID_AUTHENTICATED",
    "IS_DIGITAL",
    "IS_DISPOSABLE_EMAIL",
    "IS_DISPUTED_NON_FRAUD_TX",
    "IS_EMAIL_VERIFIED_BY_THIRD_PARTY",
    "IS_EMAIL_VERIFIED__MODEL_FEATURE",
    "IS_FAILED_TX",
    "IS_FRAUD_TX",
    "IS_FREEMAIL",
    "IS_FREE_MAIL__MODEL_FEATURE",
    "IS_GIFTING",
    "IS_LAST_DISPUTE_FRAUD_RELATED_REASON",
    "IS_NEW_BUYER__MODEL_FEATURE",
    "IS_NEW_PAYMENT_METHOD__MODEL_FEATURE",
    "IS_PAYPAL_ADDRESS_CONFIRMED",
    "IS_PERSONAL_EMAIL",
    "IS_PROCESSOR_REJECTED_DUE_TO_FRAUD",
    "IS_PROCESSOR_REPORTED_STOLEN_CARD",
    "IS_REASSESSED_TX",
    "IS_RECIPIENT_EMAIL_DISPOSABLE",
    "IS_RECIPIENT_EMAIL_FREEMAIL",
    "IS_RECIPIENT_EMAIL_PERSONAL",
    "IS_RECIPIENT_EMAIL_VALID",
    "IS_RECIPIENT_EMAIL_VERIFIED_BY_THIRD_PARTY",
    "IS_RECURRING_USER",
    "IS_REVIEWED",
    "IS_ROUTER_DEVICE_ID_AUTHENTICATED",
    "IS_RULE_PARTICIPATING_IN_LFS_PO",
    "IS_SENT_FOR_NSURE_REVIEW",
    "IS_SOFT_APPROVAL_CANDIDATE",
    "IS_SOFT_APPROVED",
    "IS_SUSPICIOUS_AMOUNT",
    "IS_THREE_D_SECURE_VERIFIED",
    "IS_UNDER_NSURE_LIABILITY",
    "IS_UNDER_THREE_D_SECURE",
    "IS_USER_FIRST_TX_ATTEMPT",
    "IS_USER_FIRST_TX_EVENT",
    "IS_VALID_EMAIL",
    "KYC_USER_AGE",
    "LAST_DISPUTED_ITEM_BUYER_NOTES",
    "LAST_DISPUTE_AMOUNT",
    "LAST_DISPUTE_DATETIME",
    "LAST_DISPUTE_DECISION",
    "LAST_DISPUTE_REASON",
    "LAST_DISPUTE_SELLER_BUYER_CHAT",
    "LAST_DISPUTE_SOURCE",
    "LAST_DISPUTE_STATUS",
    "LAST_DISPUTE_UPLOADED_TO_SNOWFLAKE",
    "LAST_FOUR",
    "LAST_FRAUD_ALERT_DATETIME",
    "LAST_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE",
    "LAST_MAXMIND_MIN_FRAUD_ALERT_DATETIME",
    "LAST_MAXMIND_MIN_FRAUD_ALERT_NEW_RISK_SCORE",
    "LAST_MAXMIND_MIN_FRAUD_ALERT_REASON_CODE",
    "LAST_MAXMIND_MIN_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE",
    "LAST_NAME",
    "LAST_NSURE_INITIATED_REFUND_UPLOADED_TO_SNOWFLAKE",
    "LAST_REPORTED_ATTACK_ID",
    "LAST_REPORTED_ATTACK_UPLOADED_TO_SNOWFLAKE",
    "LAST_RETRY_UPLOADED_TO_SNOWFLAKE",
    "LOCAL_PART_TO_NAME_DISTANCE",
    "MAXMIND_CREATED_TIME",
    "MAXMIND_IP_RISK_SCORE",
    "MAXMIND_MIN_FRAUD_ALERTS",
    "MAXMIND_RISK_SCORE",
    "MAXMIND_UPLOADED_TO_SNOWFLAKE",
    "MERCHANT_DECISIONS",
    "MERCHANT_KPI_UPDATE_ID",
    "MERCHANT_LAST_DECISION",
    "MERCHANT_LAST_DECISION_DATETIME",
    "MERCHANT_LAST_DECISION_UPLOADED_TO_SNOWFLAKE",
    "MERCHANT_NAME",
    "MERCHANT_SEGMENT_ID",
    "MILLISECONDS_FROM_SOFT_APPROVED_TO_REASSESSMENT_RESPONSE",
    "MODEL_APPROVAL_THRESHOLD",
    "MODEL_DECISION",
    "MODEL_MANAGER_TX_FEATURES_UPLOADED_TO_SNOWFLAKE",
    "MODEL_SCORE",
    "MODEL_SOFT_APPROVAL_THRESHOLD",
    "MODEL_VERSION",
    "MOST_EXPENSIVE_CART_USD_ITEM",
    "NORMALIZED_AVS_RESULT_CODE",
    "NOT_REVIEWED_REASON",
    "NSURE_DECISIONS",
    "NSURE_FIRST_DECISION",
    "NSURE_FIRST_DECISION_DATETIME",
    "NSURE_INITIATED_REFUND_DATETIME",
    "NSURE_LAST_DECISION",
    "NSURE_LAST_DECISION_DATETIME",
    "NSURE_LAST_DECISION_UPLOADED_TO_SNOWFLAKE",
    "NSURE_RETRY_TX_ID",
    "NSURE_SEGMENT_ID",
    "NSURE_UNIQUE_TX_ID",
    "ORIGINAL_TX_ID",
    "PAID_AMOUNT_CURRENCY",
    "PAID_AMOUNT_VALUE_IN_CURRENCY",
    "PARSED_USER_AGENT",
    "PARTNER_ID",
    "PARTNER_INDUSTRY",
    "PARTNER_MAIN_PRODUCT_TYPE",
    "PARTNER_NAME",
    "PAYMENT_METHOD",
    "PAYMENT_METHOD_COUNTRY_CODE",
    "PAYMENT_METHOD_DETAILS_ADDITIONAL_DATA",
    "PAYMENT_METHOD_INTERNAL_IDENTIFIER",
    "PAYMENT_METHOD_TOKEN",
    "PAYPAL_EMAIL",
    "PAYPAL_EMAIL_FIRST_SEEN",
    "PAYPAL_LOCAL_PART_TO_NAME_DISTANCE",
    "PERSONAL_INFO_ADDITIONAL_DATA",
    "PERSONAL_INFO_EMAIL_TO_RECIPIENT_EMAIL_LOCAL_PARTS_DISTANCE",
    "PHONE_COUNTRY_CODE",
    "PHONE_NUMBER",
    "PIPL_INFO_AGE",
    "PIPL_INFO_PERSON",
    "PM_ACCEPTED_TXS_COUNT",
    "PM_COUNTRY_RISKY_GMV__MODEL_FEATURE",
    "PROCESSING_FEE_CURRENCY",
    "PROCESSING_FEE_VALUE_IN_CURRENCY",
    "PROCESSOR",
    "PROCESSOR_MERCHANT_IDENTIFIER",
    "PRODUCT",
    "PRODUCTION_PAYMENT_METHOD_TYPE",
    "PRODUCT_COUNTRY_CODES",
    "PRODUCT_GAMETITLE",
    "PRODUCT_PLATFORM",
    "PRODUCT_REGIONS",
    "PRODUCT_TYPE",
    "PROD_RECIPIENT_INFO",
    "RAW_PROCESSOR_REQUEST",
    "RAW_PROCESSOR_REQUEST_SOURCE",
    "RAW_PROCESSOR_RESPONSE",
    "RAW_PROCESSOR_RESPONSE_SOURCE",
    "REASSESSMENT_REJECTION_REASON",
    "REASSESSMENT_RESULT",
    "RECIPIENT_EMAIL_FIRST_SEEN",
    "RECIPIENT_EMAIL_VALIDATION_ADDITIONAL_DATA",
    "RECIPIENT_EMAIL_VALIDATION_CREATED",
    "RECIPIENT_EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE",
    "REFUSAL_REASON",
    "REJECTION_REASON",
    "RISK_MODE",
    "RULE",
    "RULE_DECISION",
    "RULE_DESCRIPTION",
    "SEASONALITY_ATTUNED_BIN_RISKY_GMV__MODEL_FEATURE",
    "SELLER_ID",
    "SESSION_INFO_ADDITIONAL_DATA",
    "SESSION_INFO_LANGUAGE",
    "SIMULATED_DECISION",
    "SIMULATED_SEGMENT_ID",
    "SMTPV_BUYER_EMAIL_CREATED_TIME",
    "SMTPV_BUYER_EMAIL_UPLOADED_TO_SNOWFLAKE",
    "SOFT_APPROVAL_POPULATIONS_LIST",
    "STORE_FIRST_TX_TIMESTAMP",
    "STORE_ID",
    "SURROGATE_APP_TX_ID",
    "TABLE_RECORD_CREATED_AT",
    "TABLE_RECORD_UPDATED_AT",
    "THREE_D_SECURE_RESULT",
    "TRANSACTION_DETAILS_ADDITIONAL_DATA",
    "TRIGGERED_LFS_RULES",
    "TRIGGERED_RULES",
    "TX_ADDITIONAL_DATA",
    "TX_DATETIME",
    "TX_ID_KEY",
    "TX_RECEIVED_DATETIME",
    "TX_REFUND_DATETIME",
    "TX_REFUND_REASON",
    "TX_REFUND_UPLOADED_TO_SNOWFLAKE",
    "TX_TIMESTAMP_MS",
    "TX_UPLOADED_TO_SNOWFLAKE",
    "UNIQUE_USER_ID",
    "USER_AGENT",
    "USER_GRAPH_SIZE"
}

def get_column_type(column_name: str) -> str:
    """
    Get the Snowflake type for a given column name.

    Args:
        column_name: The column name to look up

    Returns:
        The Snowflake type string, or 'UNKNOWN' if not found
    """
    column_types = {
        "TABLE_RECORD_CREATED_AT": "VARCHAR(26)",
        "TABLE_RECORD_UPDATED_AT": "VARCHAR(26)",
        "EVENT_TYPE": "VARCHAR(16777216)",
        "ORIGINAL_TX_ID": "VARCHAR(16777216)",
        "STORE_ID": "VARCHAR(16777216)",
        "CLIENT_REQUEST_ID": "VARCHAR(16777216)",
        "APP_ID": "VARCHAR(16777216)",
        "TX_ID_KEY": "VARCHAR(16777216)",
        "SURROGATE_APP_TX_ID": "VARCHAR(16777216)",
        "NSURE_UNIQUE_TX_ID": "VARCHAR(16777216)",
        "UNIQUE_USER_ID": "VARCHAR(16777216)",
        "TX_DATETIME": "TIMESTAMP_NTZ(9)",
        "TX_RECEIVED_DATETIME": "TIMESTAMP_NTZ(9)",
        "TX_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "TX_TIMESTAMP_MS": "NUMBER(38,0)",
        "IS_SENT_FOR_NSURE_REVIEW": "NUMBER(1,0)",
        "AUTHORIZATION_STAGE": "VARCHAR(16777216)",
        "EMAIL": "VARCHAR(16777216)",
        "EMAIL_NORMALIZED": "VARCHAR(16777216)",
        "FIRST_NAME": "VARCHAR(16777216)",
        "LAST_NAME": "VARCHAR(16777216)",
        "PHONE_COUNTRY_CODE": "VARCHAR(16777216)",
        "PHONE_NUMBER": "VARCHAR(16777216)",
        "DATE_OF_BIRTH": "TIMESTAMP_NTZ(9)",
        "PERSONAL_INFO_ADDITIONAL_DATA": "OBJECT",
        "MERCHANT_SEGMENT_ID": "VARCHAR(16777216)",
        "BILLING_ADDRESS": "VARIANT",
        "CART": "VARIANT",
        "CART_ITEMS_TYPES": "ARRAY",
        "PRODUCT": "VARCHAR(16777216)",
        "CART_SKUS": "ARRAY",
        "CART_BRANDS": "ARRAY",
        "CART_ITEMS_ARE_GIFTS": "ARRAY",
        "CART_ITEMS_FULFILLMENT": "ARRAY",
        "CREDIT_USE": "VARIANT",
        "PAID_AMOUNT_CURRENCY": "VARCHAR(16777216)",
        "PAID_AMOUNT_VALUE_IN_CURRENCY": "FLOAT",
        "PROCESSING_FEE_CURRENCY": "VARCHAR(16777216)",
        "PROCESSING_FEE_VALUE_IN_CURRENCY": "FLOAT",
        "BIN": "VARCHAR(16777216)",
        "LAST_FOUR": "VARCHAR(16777216)",
        "PAYMENT_METHOD": "VARCHAR(16777216)",
        "PROCESSOR": "VARCHAR(16777216)",
        "PROCESSOR_MERCHANT_IDENTIFIER": "VARCHAR(16777216)",
        "PAYMENT_METHOD_TOKEN": "VARCHAR(16777216)",
        "PAYMENT_METHOD_INTERNAL_IDENTIFIER": "VARCHAR(16777216)",
        "CARD_HOLDER_NAME": "VARCHAR(16777216)",
        "IS_THREE_D_SECURE_VERIFIED": "NUMBER(38,0)",
        "THREE_D_SECURE_RESULT": "VARCHAR(16777216)",
        "IS_UNDER_THREE_D_SECURE": "NUMBER(38,0)",
        "PAYPAL_EMAIL": "VARCHAR(16777216)",
        "PAYMENT_METHOD_DETAILS_ADDITIONAL_DATA": "OBJECT",
        "IS_ANONYMOUS": "NUMBER(1,0)",
        "FAILURE_REASON": "VARCHAR(16777216)",
        "TRANSACTION_DETAILS_ADDITIONAL_DATA": "OBJECT",
        "DEVICE_ID": "VARCHAR(16777216)",
        "IP": "VARCHAR(16777216)",
        "USER_AGENT": "VARCHAR(16777216)",
        "SESSION_INFO_LANGUAGE": "VARCHAR(16777216)",
        "SESSION_INFO_ADDITIONAL_DATA": "OBJECT",
        "FIRST_RECIPIENT_INFO": "VARIANT",
        "FIRST_RECIPIENT_EMAIL": "VARCHAR(16777216)",
        "FIRST_RECIPIENT_PHONE": "VARCHAR(16777216)",
        "ALL_RECIPIENT_INFO": "ARRAY",
        "ALL_RECIPIENT_EMAILS": "ARRAY",
        "ALL_RECIPIENT_EMAILS_NORMALIZED": "ARRAY",
        "IS_GIFTING": "NUMBER(1,0)",
        "CART_DELIVERY_METHODS": "ARRAY",
        "IS_DELIVERY_METHOD_EMAIL_ONLY": "NUMBER(1,0)",
        "IS_DELIVERY_METHOD_CONTAINING_ON_SCREEN": "NUMBER(1,0)",
        "PARTNER_ID": "VARCHAR(16777216)",
        "RISK_MODE": "VARCHAR(16777216)",
        "TX_ADDITIONAL_DATA": "OBJECT",
        "CALCULATED_PROPS_ID": "VARCHAR(16777216)",
        "CALCULATED_PROPS_CREATED_DATETIME": "TIMESTAMP_NTZ(9)",
        "CALCULATED_PROPS_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "CART_USD": "VARIANT",
        "GMV": "FLOAT",
        "IS_EMAIL_VERIFIED_BY_THIRD_PARTY": "NUMBER(38,0)",
        "IS_RECIPIENT_EMAIL_VERIFIED_BY_THIRD_PARTY": "NUMBER(38,0)",
        "EMAIL_FIRST_SEEN": "TIMESTAMP_NTZ(9)",
        "PAYPAL_EMAIL_FIRST_SEEN": "TIMESTAMP_NTZ(9)",
        "RECIPIENT_EMAIL_FIRST_SEEN": "TIMESTAMP_NTZ(9)",
        "EMAIL_DATA_THIRD_PARTY_RISK_SCORE": "FLOAT",
        "IP_COUNTRY_CODE": "VARCHAR(16777216)",
        "IS_DEVICE_ID_AUTHENTICATED": "NUMBER(38,0)",
        "IS_PAYPAL_ADDRESS_CONFIRMED": "NUMBER(38,0)",
        "PIPL_INFO_AGE": "VARIANT",
        "PIPL_INFO_PERSON": "VARIANT",
        "IS_PROCESSOR_REPORTED_STOLEN_CARD": "NUMBER(38,0)",
        "IS_PROCESSOR_REJECTED_DUE_TO_FRAUD": "NUMBER(38,0)",
        "IP_ADDRESS_INFO": "VARIANT",
        "ISP": "VARCHAR(16777216)",
        "ISP_ARRAY": "VARIANT",
        "ASN": "VARCHAR(16777216)",
        "DAYS_FROM_FIRST_EMAIL_SEEN_TO_TX": "NUMBER(24,6)",
        "DAYS_FROM_FIRST_PAYPAL_EMAIL_SEEN_TO_TX": "NUMBER(24,6)",
        "DAYS_FROM_FIRST_RECIPIENT_EMAIL_SEEN_TO_TX": "NUMBER(24,6)",
        "MERCHANT_NAME": "VARCHAR(16777216)",
        "PARTNER_NAME": "VARCHAR(16777216)",
        "NSURE_DECISIONS": "ARRAY",
        "COUNT_NSURE_DECISIONS": "NUMBER(18,0)",
        "NSURE_FIRST_DECISION": "VARCHAR(16777216)",
        "NSURE_FIRST_DECISION_DATETIME": "TIMESTAMP_NTZ(9)",
        "NSURE_LAST_DECISION": "VARCHAR(16777216)",
        "NSURE_LAST_DECISION_DATETIME": "TIMESTAMP_NTZ(9)",
        "NSURE_LAST_DECISION_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "IS_REASSESSED_TX": "NUMBER(38,0)",
        "TRIGGERED_RULES": "ARRAY",
        "COUNT_TRIGGERED_RULES": "NUMBER(9,0)",
        "RULE": "VARCHAR(16777216)",
        "RULE_DECISION": "VARCHAR(16777216)",
        "RULE_DESCRIPTION": "VARCHAR(16777216)",
        "IS_RULE_PARTICIPATING_IN_LFS_PO": "NUMBER(38,0)",
        "TRIGGERED_LFS_RULES": "ARRAY",
        "MODEL_DECISION": "VARCHAR(16777216)",
        "MODEL_SCORE": "FLOAT",
        "MODEL_VERSION": "VARCHAR(16777216)",
        "MODEL_APPROVAL_THRESHOLD": "FLOAT",
        "MODEL_SOFT_APPROVAL_THRESHOLD": "FLOAT",
        "REJECTION_REASON": "VARCHAR(16777216)",
        "NOT_REVIEWED_REASON": "VARCHAR(16777216)",
        "SIMULATED_DECISION": "VARCHAR(16777216)",
        "SIMULATED_SEGMENT_ID": "VARCHAR(16777216)",
        "NSURE_SEGMENT_ID": "VARCHAR(16777216)",
        "ADDITIONAL_SEGMENTS": "VARIANT",
        "MERCHANT_LAST_DECISION_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "MERCHANT_DECISIONS": "ARRAY",
        "COUNT_MERCHANT_DECISIONS": "NUMBER(18,0)",
        "MERCHANT_LAST_DECISION": "VARCHAR(16777216)",
        "MERCHANT_LAST_DECISION_DATETIME": "TIMESTAMP_NTZ(9)",
        "IS_FAILED_TX": "NUMBER(1,0)",
        "IS_REVIEWED": "NUMBER(1,0)",
        "RAW_PROCESSOR_RESPONSE": "VARIANT",
        "RAW_PROCESSOR_RESPONSE_SOURCE": "VARCHAR(16777216)",
        "RAW_PROCESSOR_REQUEST": "VARIANT",
        "RAW_PROCESSOR_REQUEST_SOURCE": "VARCHAR(16777216)",
        "IS_UNDER_NSURE_LIABILITY": "NUMBER(1,0)",
        "IS_SOFT_APPROVED": "NUMBER(1,0)",
        "APP_INSTALL_DATETIME": "TIMESTAMP_NTZ(9)",
        "DEVICE_TYPE": "VARCHAR(16777216)",
        "DEVICE_MODEL": "VARCHAR(16777216)",
        "DEVICE_OS_VERSION": "VARCHAR(16777216)",
        "DEVICE_APP_INSTALL_SDK_VERSION": "VARCHAR(16777216)",
        "FIPP_VISITOR_ID": "VARCHAR(16777216)",
        "FIPP_IS_INCOGNITO": "BOOLEAN",
        "DAYS_FROM_FIRST_APP_INSTALL_TO_TX": "NUMBER(24,6)",
        "CARD_BRAND": "VARCHAR(16777216)",
        "CARD_CATEGORY": "VARCHAR(16777216)",
        "CARD_TYPE": "VARCHAR(16777216)",
        "IS_CARD_COMMERCIAL": "NUMBER(38,0)",
        "IS_CARD_PREPAID": "NUMBER(38,0)",
        "CARD_ISSUER": "VARCHAR(16777216)",
        "BIN_COUNTRY_CODE": "VARCHAR(16777216)",
        "CARD_ISSUER_NORMALIZED": "VARCHAR(16777216)",
        "BIN_ADDITIONAL_DATA": "OBJECT",
        "BIN_CREATED_TIME": "TIMESTAMP_NTZ(9)",
        "BIN_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "HLR_PHONE_COUNTRY_CODE": "VARCHAR(16777216)",
        "HLR_IS_VALID": "NUMBER(38,0)",
        "HLR_NUMBER_VALID": "NUMBER(38,0)",
        "HLR_IS_MOBILE": "NUMBER(38,0)",
        "HLR_IS_PORTED": "NUMBER(38,0)",
        "HLR_IS_ROAMING": "NUMBER(38,0)",
        "HLR_NUMBER_TYPE": "VARCHAR(16777216)",
        "HLR_ORIGIN_NETWORK": "VARCHAR(16777216)",
        "HLR_STATUS": "VARCHAR(16777216)",
        "HLR_CURRENT_NETWORK": "VARCHAR(16777216)",
        "HLR_PORTED_NETWORK": "VARCHAR(16777216)",
        "HLR_ADDITIONAL_DATA": "OBJECT",
        "HLR_CREATED_TIME": "TIMESTAMP_NTZ(9)",
        "HLR_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "MAXMIND_IP_RISK_SCORE": "FLOAT",
        "MAXMIND_RISK_SCORE": "FLOAT",
        "MAXMIND_CREATED_TIME": "TIMESTAMP_NTZ(9)",
        "MAXMIND_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "BUYER_EMAIL_SMTPV_RESPONSE": "VARIANT",
        "SMTPV_BUYER_EMAIL_CREATED_TIME": "TIMESTAMP_NTZ(9)",
        "SMTPV_BUYER_EMAIL_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "EMAIL_VALIDATION_CREATED": "TIMESTAMP_NTZ(9)",
        "EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "IS_DISPOSABLE_EMAIL": "NUMBER(38,0)",
        "IS_FREEMAIL": "NUMBER(38,0)",
        "IS_PERSONAL_EMAIL": "NUMBER(38,0)",
        "IS_VALID_EMAIL": "NUMBER(38,0)",
        "EMAIL_VALIDATION_ADDITIONAL_DATA": "OBJECT",
        "RECIPIENT_EMAIL_VALIDATION_CREATED": "TIMESTAMP_NTZ(9)",
        "RECIPIENT_EMAIL_VALIDATION_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "IS_RECIPIENT_EMAIL_DISPOSABLE": "NUMBER(38,0)",
        "IS_RECIPIENT_EMAIL_FREEMAIL": "NUMBER(38,0)",
        "IS_RECIPIENT_EMAIL_PERSONAL": "NUMBER(38,0)",
        "IS_RECIPIENT_EMAIL_VALID": "NUMBER(38,0)",
        "RECIPIENT_EMAIL_VALIDATION_ADDITIONAL_DATA": "OBJECT",
        "DISPUTES": "ARRAY",
        "COUNT_DISPUTES": "NUMBER(18,0)",
        "FIRST_DISPUTE_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_DISPUTE_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_DISPUTE_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "LAST_DISPUTE_AMOUNT": "VARIANT",
        "LAST_DISPUTE_STATUS": "VARCHAR(16777216)",
        "LAST_DISPUTE_DECISION": "VARCHAR(16777216)",
        "IS_LAST_DISPUTE_FRAUD_RELATED_REASON": "NUMBER(38,0)",
        "LAST_DISPUTE_REASON": "VARCHAR(16777216)",
        "LAST_DISPUTE_SOURCE": "VARIANT",
        "FIRST_NON_FRAUD_DISPUTE_DATETIME": "TIMESTAMP_NTZ(9)",
        "FRAUD_ALERTS": "ARRAY",
        "COUNT_FRAUD_ALERTS": "NUMBER(18,0)",
        "FIRST_FRAUD_ALERT_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_FRAUD_ALERT_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "NSURE_INITIATED_REFUND_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_NSURE_INITIATED_REFUND_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "TX_REFUND_REASON": "VARCHAR(16777216)",
        "TX_REFUND_DATETIME": "TIMESTAMP_NTZ(9)",
        "TX_REFUND_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "LAST_MAXMIND_MIN_FRAUD_ALERT_DATETIME": "TIMESTAMP_NTZ(9)",
        "LAST_MAXMIND_MIN_FRAUD_ALERT_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "LAST_MAXMIND_MIN_FRAUD_ALERT_NEW_RISK_SCORE": "FLOAT",
        "LAST_MAXMIND_MIN_FRAUD_ALERT_REASON_CODE": "VARCHAR(16777216)",
        "MAXMIND_MIN_FRAUD_ALERTS": "ARRAY",
        "COUNT_MAXMIND_MIN_FRAUD_ALERTS": "NUMBER(18,0)",
        "BUYER_RETRY_TX_ID": "VARCHAR(16777216)",
        "NSURE_RETRY_TX_ID": "VARCHAR(16777216)",
        "LAST_RETRY_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "FIRST_NSURE_TX_ATTEMPT_DATETIME": "TIMESTAMP_NTZ(9)",
        "FIRST_USER_TX_EVENT_DATETIME": "TIMESTAMP_NTZ(9)",
        "IS_USER_FIRST_TX_EVENT": "NUMBER(1,0)",
        "FIRST_USER_ACCOUNT_ACTIVITY_DATE": "TIMESTAMP_NTZ(9)",
        "FIRST_SIGN_IN_IDENTITY_PROVIDER": "VARCHAR(16777216)",
        "FIRST_USER_FAILED_KYC_DATETIME": "TIMESTAMP_NTZ(9)",
        "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATETIME": "TIMESTAMP_NTZ(9)",
        "FIRST_USER_TRIGGERED_KYC_DATETIME": "TIMESTAMP_NTZ(9)",
        "MODEL_MANAGER_TX_FEATURES_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "FIRST_MERCHANT_ACCEPTED_DATETIME": "TIMESTAMP_NTZ(9)",
        "FIRST_PAYMENT_METHOD_ATTEMPT_DATETIME": "TIMESTAMP_NTZ(9)",
        "FIRST_TX_ATTEMPT_DATETIME": "TIMESTAMP_NTZ(9)",
        "DAYS_FROM_FIRST_TX_ATTEMPT_TO_TX": "NUMBER(24,6)",
        "DAYS_FROM_FIRST_USER_ACCOUNT_ACTIVITY_DATE_TO_TX": "NUMBER(24,6)",
        "FIRST_FRAUD_STATUS_DATETIME": "TIMESTAMP_NTZ(9)",
        "IS_FRAUD_TX": "NUMBER(1,0)",
        "IS_DISPUTED_NON_FRAUD_TX": "NUMBER(1,0)",
        "PAYMENT_METHOD_COUNTRY_CODE": "VARCHAR(16777216)",
        "DAYS_FROM_FIRST_MERCHANT_ACCEPTANCE_TO_TX": "FLOAT",
        "DAYS_FROM_FIRST_PAYMENT_METHOD_ATTEMPT_TO_TX": "FLOAT",
        "LOCAL_PART_TO_NAME_DISTANCE": "FLOAT",
        "BUYER_NAME_TO_PIPL_NAME_DISTANCE": "FLOAT",
        "PAYPAL_LOCAL_PART_TO_NAME_DISTANCE": "FLOAT",
        "PERSONAL_INFO_EMAIL_TO_RECIPIENT_EMAIL_LOCAL_PARTS_DISTANCE": "FLOAT",
        "GROUP_NEW_BUYERS_GMV_IN_LAST_DAY": "FLOAT",
        "GROUP_NEW_PAYMENT_METHODS_GMV_IN_LAST_DAY": "FLOAT",
        "GROUP_NEW_BUYERS_TXS_IN_LAST_DAY": "FLOAT",
        "GROUP_NEW_PAYMENT_METHODS_TXS_IN_LAST_DAY": "FLOAT",
        "GROUP_MAX_MAXMIND_RISK_SCORE": "FLOAT",
        "GROUP_TX_FAILURE_COUNT": "FLOAT",
        "GROUP_TX_FAILURE_GMV": "FLOAT",
        "PM_ACCEPTED_TXS_COUNT": "FLOAT",
        "USER_GRAPH_SIZE": "FLOAT",
        "BIN_RISKY_GMV": "FLOAT",
        "BUYER_AGE": "FLOAT",
        "DAYS_FROM_VISITOR_ID_AGE": "FLOAT",
        "IS_RECURRING_USER": "NUMBER(38,0)",
        "IS_NEW_BUYER__MODEL_FEATURE": "NUMBER(38,0)",
        "IS_NEW_PAYMENT_METHOD__MODEL_FEATURE": "NUMBER(38,0)",
        "IS_FREE_MAIL__MODEL_FEATURE": "NUMBER(38,0)",
        "IS_EMAIL_VERIFIED__MODEL_FEATURE": "NUMBER(38,0)",
        "ISSUER_RISKY_GMV__MODEL_FEATURE": "FLOAT",
        "PM_COUNTRY_RISKY_GMV__MODEL_FEATURE": "FLOAT",
        "SEASONALITY_ATTUNED_BIN_RISKY_GMV__MODEL_FEATURE": "FLOAT",
        "CART_WITHOUT_FEE_ITEMS": "ARRAY",
        "IS_DIGITAL": "NUMBER(1,0)",
        "IS_SUSPICIOUS_AMOUNT": "NUMBER(2,0)",
        "DAYS_FROM_STORE_FIRST_TX__MODEL_FEATURE": "FLOAT",
        "DAYS_FROM_STORE_CREATION__MODEL_FEATURE": "FLOAT",
        "AVS": "VARCHAR(16777216)",
        "PARSED_USER_AGENT": "OBJECT",
        "PROD_RECIPIENT_INFO": "VARIANT",
        "FIRST_USER_COMPLETED_KYC_RESULT": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_TYPE": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_PROVIDER": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_NUM_OF_KYC_ATTEMPTS": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_CREATE_DATE": "TIMESTAMP_NTZ(9)",
        "FIRST_USER_COMPLETED_KYC_REVIEW_ANSWER_OR_STATUS": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_LEVEL_NAME": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_DOCUMENT_TYPE": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_FIRST_NAME": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_LAST_NAME": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_ADDRESS_COUNTRY_USER_INPUT": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_STATE_USER_INPUT": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_TOWN_USER_INPUT": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_POST_CODE_USER_INPUT": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_ID_POST_CODE_FROM_DOCS_ARRAY": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_ID_COUNTRY_OF_BIRTH": "VARCHAR(16777216)",
        "FIRST_USER_COMPLETED_KYC_ID_ISSUING_COUNTRY_FROM_DOCS_ARRAY": "VARCHAR(16777216)",
        "CUSTODIAL_TYPE": "VARCHAR(16777216)",
        "SOFT_APPROVAL_POPULATIONS_LIST": "VARIANT",
        "IS_SOFT_APPROVAL_CANDIDATE": "VARIANT",
        "IS_ROUTER_DEVICE_ID_AUTHENTICATED": "BOOLEAN",
        "REASSESSMENT_REJECTION_REASON": "VARCHAR(16777216)",
        "MILLISECONDS_FROM_SOFT_APPROVED_TO_REASSESSMENT_RESPONSE": "NUMBER(38,0)",
        "LAST_DISPUTE_SELLER_BUYER_CHAT": "VARIANT",
        "LAST_DISPUTED_ITEM_BUYER_NOTES": "VARCHAR(16777216)",
        "BUYER_EMAIL_DOMAIN": "VARCHAR(16777216)",
        "REFUSAL_REASON": "VARCHAR(16777216)",
        "ENRICHED_TXS_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "PRODUCT_TYPE": "VARCHAR(16777216)",
        "FIRST_USER_SUCCESSFULLY_FULFILLED_KYC_DATE_OF_BIRTH": "VARCHAR(16777216)",
        "KYC_USER_AGE": "NUMBER(19,6)",
        "STORE_FIRST_TX_TIMESTAMP": "NUMBER(38,0)",
        "FAILURE_CATEGORY": "VARCHAR(16777216)",
        "REASSESSMENT_RESULT": "VARCHAR(16777216)",
        "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NATIVE_TX": "FLOAT",
        "DAYS_FROM_CRYPTO_WALLET_FIRST_INCOMING_NON_NATIVE_TX": "FLOAT",
        "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NATIVE_TX": "FLOAT",
        "DAYS_FROM_CRYPTO_WALLET_FIRST_OUTGOING_NON_NATIVE_TX": "FLOAT",
        "NORMALIZED_AVS_RESULT_CODE": "VARCHAR(16777216)",
        "PRODUCTION_PAYMENT_METHOD_TYPE": "VARCHAR(16777216)",
        "SELLER_ID": "VARCHAR(16777216)",
        "MERCHANT_KPI_UPDATE_ID": "VARCHAR(16777216)",
        "PRODUCT_COUNTRY_CODES": "VARIANT",
        "DISTANCE_IP_PRODUCT__MODEL_FEATURE": "FLOAT",
        "DISTANCE_LOCAL_PRODUCT__MODEL_FEATURE": "FLOAT",
        "DISTANCE_PAYMENT_METHOD_PRODUCT__MODEL_FEATURE": "FLOAT",
        "DISTANCE_PHONE_PRODUCT__MODEL_FEATURE": "FLOAT",
        "MOST_EXPENSIVE_CART_USD_ITEM": "VARIANT",
        "PRODUCT_REGIONS": "VARIANT",
        "PRODUCT_PLATFORM": "VARCHAR(16777216)",
        "PRODUCT_GAMETITLE": "VARCHAR(16777216)",
        "LAST_REPORTED_ATTACK_ID": "VARCHAR(16777216)",
        "LAST_REPORTED_ATTACK_UPLOADED_TO_SNOWFLAKE": "TIMESTAMP_NTZ(9)",
        "IS_BTCC_TEST_TX_NOT_REVIEWED_BY_NSURE": "BOOLEAN",
        "PARTNER_MAIN_PRODUCT_TYPE": "VARCHAR(16777216)",
        "PARTNER_INDUSTRY": "VARCHAR(16777216)",
        "IS_USER_FIRST_TX_ATTEMPT": "NUMBER(1,0)",
    }
    return column_types.get(column_name, "UNKNOWN")

def is_valid_column(column_name: str) -> bool:
    """
    Check if a column name exists in the schema.

    Args:
        column_name: The column name to validate

    Returns:
        True if column exists, False otherwise
    """
    return column_name in ALL_COLUMN_NAMES

def get_correct_column_name(old_name: str) -> str:
    """
    SCHEMA-LOCKED MODE: No field mappings allowed.
    Only valid schema column names are permitted.

    Args:
        old_name: Column name to validate

    Returns:
        The input name if valid, raises error if invalid
    """
    if old_name in ALL_COLUMN_NAMES:
        return old_name
    raise ValueError(f"Invalid column name '{old_name}' - not found in schema. Only valid schema columns allowed.")

def build_safe_select_columns(columns: list) -> str:
    """
    Build a safe SELECT clause with validated column names.

    Args:
        columns: List of column names to include in SELECT

    Returns:
        Comma-separated string of validated column references
    """
    safe_columns = []
    for col in columns:
        correct_name = get_correct_column_name(col)
        if is_valid_column(correct_name):
            safe_columns.append(correct_name)
        else:
            # For non-existent columns, use NULL with alias
            safe_columns.append(f"NULL AS {col}")

    return ", ".join(safe_columns)

# Column count validation
EXPECTED_COLUMN_COUNT = 333
ACTUAL_COLUMN_COUNT = len(ALL_COLUMN_NAMES)

if ACTUAL_COLUMN_COUNT != EXPECTED_COLUMN_COUNT:
    raise ValueError(
        f"Schema validation failed: Expected {EXPECTED_COLUMN_COUNT} columns, "
        f"but found {ACTUAL_COLUMN_COUNT} columns"
    )

# Schema validation passed - show which table this validates against
import os as _os
db_provider = _os.getenv('DATABASE_PROVIDER', 'snowflake').lower()
if db_provider == 'snowflake':
    database = _os.getenv('SNOWFLAKE_DATABASE', 'DBT')
    schema = _os.getenv('SNOWFLAKE_SCHEMA', 'DBT_PROD')
    table = _os.getenv('SNOWFLAKE_TRANSACTIONS_TABLE', 'TXS')
    table_name = f"{database}.{schema}.{table}"
else:
    pg_schema = _os.getenv('POSTGRES_SCHEMA', 'public')
    pg_table = _os.getenv('POSTGRES_TRANSACTIONS_TABLE', 'transactions_enriched')
    table_name = f"{pg_schema}.{pg_table}"

print(f"✅ Schema constants loaded: {ACTUAL_COLUMN_COUNT} columns validated for {table_name} ({db_provider.upper()})")


def get_required_env_var(var_name: str) -> str:
    """Get required environment variable or raise error if missing."""
    import os
    value = os.getenv(var_name)
    if not value:
        raise ValueError(f"❌ Required environment variable {var_name} not found in .env file!")
    return value


def get_full_table_name(database: str = None, schema: str = None, table_name: str = None) -> str:
    """
    Get the full qualified table name using environment variables.

    Args:
        database: Database name override (defaults to SNOWFLAKE_DATABASE)
        schema: Schema name override (defaults to SNOWFLAKE_SCHEMA)
        table_name: Table name override (defaults to SNOWFLAKE_TRANSACTIONS_TABLE)

    Returns:
        Full qualified table name: database.schema.table

    Raises:
        ValueError: If required environment variables are missing from .env file
    """
    db = database or get_required_env_var('SNOWFLAKE_DATABASE')
    sch = schema or get_required_env_var('SNOWFLAKE_SCHEMA')
    tbl = table_name or get_required_env_var('SNOWFLAKE_TRANSACTIONS_TABLE')

    return f"{db}.{sch}.{tbl}"
