# Dredd API Contract Testing Configuration
#
# Constitutional Compliance:
# - Backend URL from environment variable (no hardcoded URL)
# - Test configuration driven by environment
# - OpenAPI schema as single source of truth
#
# Usage:
#   dredd dredd.yml
#   BACKEND_URL=http://localhost:8090 dredd dredd.yml

# Dredd version
# Use a specific version for reproducible tests
dry-run: null
hookfiles: ./test/contract/hooks.ts
language: typescript
require: ts-node/register

# Reporter configuration
reporter:
  - html
  - markdown
output:
  - ./test/contract/reports/dredd-report.html
  - ./test/contract/reports/dredd-report.md

# Logging configuration
loglevel: info
color: true
timestamp: true

# Test behavior
sorted: true
names: false
only: []
skip: []

# Network configuration
# Constitutional Compliance: Backend URL from environment
# Default: http://localhost:8090 (can be overridden via BACKEND_URL env var)
endpoint: http://localhost:8090

# OpenAPI specification
# Constitutional Compliance: OpenAPI schema downloaded from backend
blueprint: ./src/api/generated/openapi.json

# Test execution settings
method: []
header: []
user: null
inline-errors: false
details: true
no-color: false

# Request/Response settings
hookfiles: ./test/contract/hooks.ts

# Timeout settings (Constitutional Compliance: configurable timeouts)
timeout: 30000

# Connection settings
# Constitutional Compliance: No hardcoded connection limits
max-connections: 10

# SSL settings
insecure: false
ssl-cert: null
ssl-key: null
ssl-ca: null

# Retry settings (Constitutional Compliance: configurable retry)
retry: 3
retry-delay: 1000
