package tv.bayit.plus.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Response from GET /api/v1/content/{id}/stream or /api/v1/live/{id}/stream */
@Serializable
data class StreamInfo(
    val url: String? = null,
    @SerialName("direct_url") val directUrl: String? = null,
    @SerialName("stream_url") val streamUrl: String? = null,
    val type: String? = null,
    @SerialName("stream_type") val streamType: String? = null,
    val quality: String? = null,
    @SerialName("available_qualities") val availableQualities: List<QualityVariant>? = null,
    @SerialName("is_drm_protected") val isDrmProtected: Boolean? = null,
    @SerialName("drm_key_id") val drmKeyId: String? = null,
    @SerialName("is_transcoded") val isTranscoded: Boolean? = null,
    val platform: String? = null,
    @SerialName("duration_hint") val durationHint: Double? = null,
) {
    /** Resolved URL - checks url, stream_url, then direct_url. */
    val resolvedUrl: String? get() = url ?: streamUrl ?: directUrl
}

/** Quality variant for stream selection. */
@Serializable
data class QualityVariant(
    val quality: String,
    @SerialName("resolution_height") val resolutionHeight: Int? = null,
    @SerialName("content_id") val contentId: String? = null,
)

/** Response from GET /api/v1/radio/{id}/stream */
@Serializable
data class RadioStreamInfo(
    val url: String? = null,
    val type: String? = null,
)

/** Audio track metadata for player track selection. */
@Serializable
data class AudioTrack(
    val id: String,
    val label: String,
    val language: String? = null,
)

/** A subtitle cue with timing and optional word-level data. */
@Serializable
data class SubtitleCue(
    val id: String? = null,
    @SerialName("start_time") val startTime: Double? = null,
    @SerialName("end_time") val endTime: Double? = null,
    val text: String? = null,
    @SerialName("text_nikud") val textNikud: String? = null,
    @SerialName("text_shoresh") val textShoresh: String? = null,
    @SerialName("text_heblish") val textHeblish: String? = null,
    @SerialName("text_engrew") val textEngrew: String? = null,
    val words: List<SubtitleWord>? = null,
    @SerialName("has_shoresh_version") val hasShoreshVersion: Boolean? = null,
    @SerialName("has_heblish_version") val hasHeblishVersion: Boolean? = null,
    @SerialName("has_engrew_version") val hasEngrewVersion: Boolean? = null,
    @SerialName("is_auto_generated") val isAutoGenerated: Boolean? = null,
    val source: String? = null,
) {
    val stableId: String get() = id ?: "${startTime ?: 0.0}-${endTime ?: 0.0}"
}

/** A single word within a subtitle cue for tap-to-translate. */
@Serializable
data class SubtitleWord(
    val id: String? = null,
    val word: String? = null,
    val start: Double? = null,
    val end: Double? = null,
    @SerialName("is_hebrew") val isHebrew: Boolean? = null,
) {
    val stableId: String get() = id ?: "${word.orEmpty()}-${start ?: 0.0}"
}

/** Response from GET /api/v1/content/{id}/subtitles/cues */
@Serializable
data class SubtitleCuesResponse(
    val cues: List<SubtitleCue>? = null,
    val language: String? = null,
    @SerialName("has_nikud") val hasNikud: Boolean? = null,
)

/** Translation result for a tapped subtitle word. */
@Serializable
data class TranslationResult(
    val word: String? = null,
    val translation: String? = null,
    val transliteration: String? = null,
    @SerialName("part_of_speech") val partOfSpeech: String? = null,
    val example: String? = null,
    @SerialName("example_translation") val exampleTranslation: String? = null,
)

/** Hebrew subtitle display modes. */
@Serializable
enum class SubtitleHebrewMode {
    @SerialName("standard") STANDARD,
    @SerialName("nikud") NIKUD,
    @SerialName("shoresh") SHORESH,
    @SerialName("heblish") HEBLISH,
}

/** English subtitle display modes. */
@Serializable
enum class SubtitleEnglishMode {
    @SerialName("standard") STANDARD,
    @SerialName("engrew") ENGREW,
}
