package tv.bayit.plus.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** A subtitle track available for a piece of content. */
@Serializable
data class SubtitleTrack(
    val id: String,
    @SerialName("content_id") val contentId: String,
    val language: String,
    @SerialName("language_name") val languageName: String? = null,
    val format: String? = null,
    @SerialName("has_nikud_version") val hasNikudVersion: Boolean = false,
    @SerialName("has_shoresh_version") val hasShoreshVersion: Boolean = false,
    @SerialName("has_heblish_version") val hasHeblishVersion: Boolean = false,
    @SerialName("has_engrew_version") val hasEngrewVersion: Boolean = false,
    @SerialName("is_default") val isDefault: Boolean = false,
    @SerialName("is_auto_generated") val isAutoGenerated: Boolean = false,
    @SerialName("cue_count") val cueCount: Int? = null,
)

/** User preferences for subtitle display, scoped to a content item or global. */
@Serializable
data class SubtitlePreferencesInfo(
    @SerialName("content_id") val contentId: String? = null,
    @SerialName("preferred_language") val preferredLanguage: String? = null,
    @SerialName("hebrew_mode") val hebrewMode: String? = null,
    @SerialName("english_mode") val englishMode: String? = null,
    @SerialName("font_size") val fontSize: Float? = null,
    @SerialName("show_background") val showBackground: Boolean? = null,
    @SerialName("last_used_at") val lastUsedAt: String? = null,
)

/** Typed parameter for updating subtitle preferences. */
data class SubtitlePreferencesUpdate(
    val language: String? = null,
    val hebrewMode: SubtitleHebrewMode? = null,
    val englishMode: SubtitleEnglishMode? = null,
    val fontSize: Float? = null,
    val showBackground: Boolean? = null,
)
