"""Comprehension Mode schemas - LLM structured-output contracts + embedded models.

Shared source of truth for RubricScore, TriggerDecision, FollowUpQuestion and the
enums they depend on. Used by:
  - app/models/comprehension_session.py (ScoredExchange embeds RubricScore)
  - app/models/film_memory.py (ExchangeType tag on FilmMemoryExchange)
  - app/services/olorin/comprehension/* (LLM calls - trigger/qgen/scorer)
  - app/api/* (DTO projection)

Decisions enforced here:
  - D-03: numeric 0-3 score with derived band enum (low/med/high)
  - D-04: rationale <=240 chars (one-sentence ceiling)
  - D-11: Pydantic schema -> Anthropic tool-use structured output
  - D-02: ExchangeType tag distinguishes grader-origin from chat-origin exchanges
  - D-12/D-13: AdaptLevel 4-state machine (initial/harder/simpler_retry/answer_reveal)
"""
from enum import Enum

from pydantic import BaseModel, Field, computed_field


class ScoreBand(str, Enum):
    """Derived band for B2B SDK + UI (never exposed numerically to students). Per D-03.

    Students see only the character's in-voice reaction (D-14); partners see the
    band projection; teachers see the numeric score via the override UI (Phase 3).
    """

    LOW = "low"    # score 0 (wrong) or 1 (partial)
    MED = "med"    # score 2 (right)
    HIGH = "high"  # score 3 (insightful)


class ExchangeType(str, Enum):
    """Tag on FilmMemoryExchange distinguishing grader from chat origin. Per D-02.

    The grader NEVER reads this field - it exists solely so the character's LLM
    call can project only CHARACTER_CHAT exchanges when composing its
    conversational memory. Dual-write safety: grader-origin exchanges still land
    in VODFilmMemory so the character remembers what was asked, but are tagged
    separately so projection can filter them when building chat context.
    """

    CHARACTER_CHAT = "character_chat"
    COMPREHENSION_GRADER = "comprehension_grader"


class AdaptLevel(str, Enum):
    """2-level adapt state machine. Per D-12, D-13.

    State transitions:
      INITIAL -> HARDER (score >= 2)
      INITIAL -> SIMPLER_RETRY (score <= 1)
      SIMPLER_RETRY -> INITIAL/HARDER (score >= 2 on retry)
      SIMPLER_RETRY -> ANSWER_REVEAL (score <= 1 on retry - D-13 fall-through)
    """

    INITIAL = "initial"
    HARDER = "harder"
    SIMPLER_RETRY = "simpler_retry"
    ANSWER_REVEAL = "answer_reveal"  # D-13 retry fall-through terminal


class RubricScore(BaseModel):
    """Stateless grader output. Per D-03, D-04, D-10, D-11.

    Numeric 0-3 internal; band derived via computed_field; rationale <=240 chars
    (D-04 one-sentence ceiling). Pydantic schema is passed to Anthropic tool-use
    for structured output enforcement (D-11). Scorer LLM is stateless - receives
    rubric + scene_context + question + student_answer only (D-10) - so this
    schema carries no session history or prior-score context.
    """

    score: int = Field(
        ...,
        ge=0,
        le=3,
        description="0=wrong, 1=partial, 2=right, 3=insightful",
    )
    rationale: str = Field(
        ...,
        max_length=500,
        description="Brief explanation of the score",
    )

    @computed_field
    @property
    def band(self) -> ScoreBand:
        """Map numeric score to band per D-03. Derived, not stored."""
        if self.score >= 3:
            return ScoreBand.HIGH
        if self.score == 2:
            return ScoreBand.MED
        return ScoreBand.LOW


class TriggerDecision(BaseModel):
    """GPT-4o-mini trigger classifier output. Per D-06, D-07.

    Input context at call site: current scene_context + full recent_exchanges
    window from VODFilmMemory + time-since-last-trigger (D-06). Hard rate limit
    of 1 trigger per 90s playback is enforced at the service layer, not here.
    """

    should_trigger: bool = Field(
        ...,
        description="Whether to ask a comprehension question now",
    )
    reason: str = Field(
        ...,
        max_length=240,
        description="Brief rationale for trigger or skip",
    )


class FollowUpQuestion(BaseModel):
    """Adaptive follow-up question from the character. Per D-08, D-09, D-12.

    Generated by Claude 3.5 Haiku with VODFilmMemory.summary + last 3 exchanges
    + current scene_context + rubric + adapt_level (D-08). Character voice from
    CharacterProfile.personality_traits (D-09). adapt_level reflects the 2-level
    state machine D-12 + D-13 fall-through.
    """

    question_text: str = Field(
        ...,
        max_length=500,
        description="The question as the character would phrase it",
    )
    adapt_level: AdaptLevel = Field(
        ...,
        description="Difficulty direction relative to the prior turn",
    )
    in_character_phrasing: str = Field(
        ...,
        max_length=500,
        description="Character-voice reaction line preceding the question",
    )
