import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  card: {
    backgroundColor: 'rgba(30,30,46,0.95)',
    borderRadius: 20,
    padding: 28,
    maxWidth: 480,
    width: '90%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  timerRow: { marginBottom: 20 },
  timerCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(97,175,239,0.2)',
    borderWidth: 2,
    borderColor: '#61AFEF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerText: { color: '#61AFEF', fontSize: 22, fontWeight: '700' },
  promptText: { color: '#fff', fontSize: 26, fontWeight: '600', textAlign: 'center', marginBottom: 8 },
  rtlText: { writingDirection: 'rtl' },
  transliterationText: { color: '#ABB2BF', fontSize: 16, fontStyle: 'italic', textAlign: 'center', marginBottom: 4 },
  translationText: { color: '#ABB2BF', fontSize: 14, textAlign: 'center', marginBottom: 16 },
  hintContainer: { backgroundColor: 'rgba(229,192,123,0.15)', borderRadius: 10, padding: 12, marginBottom: 16, width: '100%' },
  hintText: { color: '#E5C07B', fontSize: 14, textAlign: 'center' },
  feedbackRow: { marginBottom: 12 },
  feedbackText: { color: '#E06C75', fontSize: 14, textAlign: 'center' },
  actionsRow: { marginTop: 8, alignItems: 'center' },
  listeningContainer: { alignItems: 'center' },
  listeningText: { color: '#EF4444', fontSize: 14, marginTop: 8 },
});
