# Cloud Build configuration for Station-AI Backend
# Deploys Python FastAPI backend to Cloud Run

steps:
  # Build Docker image (use root context to access packages/)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    id: 'build-image'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:$BUILD_ID'
    id: 'push-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'station-ai-backend'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--port=8080'
      - '--set-env-vars=ENVIRONMENT=production,LOG_LEVEL=INFO,MONGODB_DB_NAME=israeli_radio'
      - '--set-secrets=MONGODB_URI=bayit-mongodb-url:latest'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image']

# Substitution variables
substitutions:
  _REGION: 'us-east1'

# Timeout for entire build
timeout: '1200s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Images to push to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/station-ai/backend:latest'
