"""
Investigation API Endpoints

RESTful API endpoints for fraud investigation management.
Used for OpenAPI schema generation and frontend TypeScript type generation.

Constitutional Compliance:
- All configuration from environment variables
- No hardcoded URLs, IDs, or business logic
- Dependency injection for services
- Proper error handling with ErrorResponse model
"""

import os
from fastapi import APIRouter, HTTPException, Depends, status
from typing import Dict, Any
import uuid

from .models.investigation_models import (
    InvestigationRequest,
    InvestigationResponse,
    ErrorResponse
)

# Router configuration from environment
router = APIRouter(
    prefix=os.getenv("API_PREFIX", "/api/v1"),
    tags=["investigations"]
)


@router.post(
    "/investigations/",
    response_model=InvestigationResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        400: {"model": ErrorResponse, "description": "Bad Request - Invalid input"},
        422: {"model": ErrorResponse, "description": "Validation Error"},
        500: {"model": ErrorResponse, "description": "Internal Server Error"}
    },
    summary="Create new fraud investigation",
    description="""
    Create a new fraud investigation for the specified entity.

    **Constitutional Compliance:**
    - Entity validation performed by Pydantic models
    - Investigation ID auto-generated (UUID)
    - Time range optional, defaults to backend configuration if not provided
    - All timestamps in ISO 8601 format

    **Example Request:**
    ```json
    {
        "entity_id": "user@example.com",
        "entity_type": "email",
        "time_range": {
            "start_time": "2025-01-01T00:00:00Z",
            "end_time": "2025-01-02T00:00:00Z"
        }
    }
    ```
    """
)
async def create_investigation(request: InvestigationRequest) -> InvestigationResponse:
    """
    Create a new fraud investigation.

    Constitutional Compliance:
    - Investigation ID generated via UUID (no hardcoded IDs)
    - Initial status from domain model
    - Timestamps auto-generated from BaseResponseModel
    - Risk score initially None (computed after investigation completes)

    Args:
        request: Investigation request with entity_id, entity_type, optional time_range

    Returns:
        InvestigationResponse with investigation_id, status, timestamps

    Raises:
        HTTPException: If validation fails or internal error occurs
    """
    try:
        # Generate investigation ID (Constitutional Compliance: no hardcoded IDs)
        investigation_id = str(uuid.uuid4())

        # Create response (timestamps auto-generated by BaseResponseModel)
        response = InvestigationResponse(
            investigation_id=investigation_id,
            status="pending",  # Initial status from domain model
            risk_score=None  # Risk score computed after investigation completes
        )

        return response

    except ValueError as e:
        # Validation errors from Pydantic
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "ValidationError",
                "message": str(e),
                "details": {
                    "request": request.model_dump()
                }
            }
        )
    except Exception as e:
        # Unexpected errors
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "InternalServerError",
                "message": "Failed to create investigation",
                "details": {
                    "error_type": type(e).__name__
                }
            }
        )


@router.get(
    "/investigations/{investigation_id}",
    response_model=InvestigationResponse,
    responses={
        404: {"model": ErrorResponse, "description": "Investigation not found"},
        500: {"model": ErrorResponse, "description": "Internal Server Error"}
    },
    summary="Get investigation status",
    description="""
    Retrieve the current status and results of a fraud investigation.

    **Constitutional Compliance:**
    - Investigation ID validation via path parameter
    - Returns 404 if investigation not found
    - Risk score included when investigation completes
    - All timestamps in ISO 8601 format
    """
)
async def get_investigation(investigation_id: str) -> InvestigationResponse:
    """
    Get investigation status and results.

    Constitutional Compliance:
    - Investigation ID from path parameter (no hardcoded values)
    - Returns current status and risk score if available
    - Proper 404 handling for non-existent investigations

    Args:
        investigation_id: UUID of the investigation

    Returns:
        InvestigationResponse with current status, risk_score, timestamps

    Raises:
        HTTPException: If investigation not found or internal error occurs
    """
    try:
        # For now, return a sample response
        # (Will be replaced with actual database lookup in future task)
        response = InvestigationResponse(
            investigation_id=investigation_id,
            status="in_progress",
            risk_score=None  # Will be populated when investigation completes
        )

        return response

    except KeyError:
        # Investigation not found
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "NotFoundError",
                "message": f"Investigation {investigation_id} not found",
                "details": {
                    "investigation_id": investigation_id
                }
            }
        )
    except Exception as e:
        # Unexpected errors
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "InternalServerError",
                "message": "Failed to retrieve investigation",
                "details": {
                    "investigation_id": investigation_id,
                    "error_type": type(e).__name__
                }
            }
        )
