#!/bin/bash

# Docker Secrets Loader for Olorin
# This script loads secrets from Firebase Secret Manager and creates Docker environment files

set -e

# Configuration
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-"olorin-ai"}
ENVIRONMENT=${APP_ENV:-"development"}
OUTPUT_FILE=${OUTPUT_FILE:-".env.docker.secrets"}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Check if gcloud is installed
check_gcloud() {
    if ! command -v gcloud &> /dev/null; then
        print_error "gcloud CLI is not installed. Please install Google Cloud SDK."
        echo "Visit: https://cloud.google.com/sdk/docs/install"
        exit 1
    fi
}

# Authenticate with Google Cloud
authenticate_gcloud() {
    print_info "Checking Google Cloud authentication..."
    
    if ! gcloud auth application-default print-access-token &> /dev/null; then
        print_warning "Not authenticated with Google Cloud"
        echo "Please run: gcloud auth application-default login"
        exit 1
    fi
    
    print_status "Google Cloud authentication verified"
}

# Function to get secret from Firebase Secret Manager
get_secret() {
    local secret_name=$1
    local env_var=$2
    local default_value=$3
    
    # Try environment-specific secret first
    local env_secret_path="${ENVIRONMENT}/olorin/${secret_name}"
    local base_secret_path="olorin/${secret_name}"
    
    # Try to get the secret
    local secret_value=""
    
    # Try environment-specific path
    if gcloud secrets versions access latest --secret="$env_secret_path" --project="$FIREBASE_PROJECT_ID" 2>/dev/null; then
        secret_value=$(gcloud secrets versions access latest --secret="$env_secret_path" --project="$FIREBASE_PROJECT_ID" 2>/dev/null)
        print_status "Loaded secret: $env_secret_path"
    # Try base path
    elif gcloud secrets versions access latest --secret="$base_secret_path" --project="$FIREBASE_PROJECT_ID" 2>/dev/null; then
        secret_value=$(gcloud secrets versions access latest --secret="$base_secret_path" --project="$FIREBASE_PROJECT_ID" 2>/dev/null)
        print_status "Loaded secret: $base_secret_path"
    # Check environment variable
    elif [ -n "${!env_var}" ]; then
        secret_value="${!env_var}"
        print_info "Using environment variable: $env_var"
    # Use default
    elif [ -n "$default_value" ]; then
        secret_value="$default_value"
        print_warning "Using default value for: $secret_name"
    else
        print_warning "No value found for: $secret_name"
        return 1
    fi
    
    echo "$secret_value"
}

# Load all Docker environment secrets
load_docker_secrets() {
    print_info "Loading secrets for Docker environment..."
    
    # Start creating the env file
    cat > "$OUTPUT_FILE" << 'EOF'
# Docker Environment Secrets
# Generated by docker-secrets-loader.sh
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

EOF
    
    # Database Configuration
    echo "# Database Configuration" >> "$OUTPUT_FILE"
    echo "POSTGRES_DB=${POSTGRES_DB:-fraud_detection}" >> "$OUTPUT_FILE"
    echo "POSTGRES_USER=${POSTGRES_USER:-postgres}" >> "$OUTPUT_FILE"
    
    local db_password=$(get_secret "database_password" "POSTGRES_PASSWORD" "postgres")
    echo "POSTGRES_PASSWORD=$db_password" >> "$OUTPUT_FILE"
    echo "DB_PASSWORD=$db_password" >> "$OUTPUT_FILE"
    
    echo "POSTGRES_PORT=${POSTGRES_PORT:-5432}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Redis Configuration
    echo "# Redis Configuration" >> "$OUTPUT_FILE"
    local redis_password=$(get_secret "redis_password" "REDIS_PASSWORD" "")
    echo "REDIS_PASSWORD=$redis_password" >> "$OUTPUT_FILE"
    echo "REDIS_PORT=${REDIS_PORT:-6379}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Application Configuration
    echo "# Application Configuration" >> "$OUTPUT_FILE"
    echo "BACKEND_PORT=${BACKEND_PORT:-8000}" >> "$OUTPUT_FILE"
    echo "FRONTEND_PORT=${FRONTEND_PORT:-3000}" >> "$OUTPUT_FILE"
    echo "PORTAL_PORT=${PORTAL_PORT:-3001}" >> "$OUTPUT_FILE"
    echo "LOG_LEVEL=${LOG_LEVEL:-INFO}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # JWT Configuration
    echo "# JWT Configuration" >> "$OUTPUT_FILE"
    local jwt_secret=$(get_secret "jwt_secret_key" "JWT_SECRET_KEY" "default_jwt_secret_key_minimum_32_characters")
    echo "JWT_SECRET_KEY=$jwt_secret" >> "$OUTPUT_FILE"
    echo "JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}" >> "$OUTPUT_FILE"
    echo "JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS:-24}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # API Keys
    echo "# API Keys" >> "$OUTPUT_FILE"
    
    local openai_key=$(get_secret "openai_api_key" "OPENAI_API_KEY" "")
    if [ -n "$openai_key" ]; then
        echo "OPENAI_API_KEY=$openai_key" >> "$OUTPUT_FILE"
    fi
    
    local anthropic_key=$(get_secret "anthropic_api_key" "ANTHROPIC_API_KEY" "")
    if [ -n "$anthropic_key" ]; then
        echo "ANTHROPIC_API_KEY=$anthropic_key" >> "$OUTPUT_FILE"
    fi
    
    local gaia_key=$(get_secret "gaia_api_key" "GAIA_API_KEY" "")
    if [ -n "$gaia_key" ]; then
        echo "GAIA_API_KEY=$gaia_key" >> "$OUTPUT_FILE"
    fi
    
    local olorin_key=$(get_secret "olorin_api_key" "OLORIN_API_KEY" "")
    if [ -n "$olorin_key" ]; then
        echo "OLORIN_API_KEY=$olorin_key" >> "$OUTPUT_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
    
    # Splunk Configuration
    echo "# Splunk Configuration" >> "$OUTPUT_FILE"
    echo "SPLUNK_HOST=${SPLUNK_HOST:-localhost}" >> "$OUTPUT_FILE"
    echo "SPLUNK_PORT=${SPLUNK_PORT:-8089}" >> "$OUTPUT_FILE"
    
    local splunk_token=$(get_secret "splunk_token" "SPLUNK_TOKEN" "")
    if [ -n "$splunk_token" ]; then
        echo "SPLUNK_TOKEN=$splunk_token" >> "$OUTPUT_FILE"
    fi
    
    local splunk_username=$(get_secret "splunk_username" "SPLUNK_USERNAME" "")
    if [ -n "$splunk_username" ]; then
        echo "SPLUNK_USERNAME=$splunk_username" >> "$OUTPUT_FILE"
    fi
    
    local splunk_password=$(get_secret "splunk_password" "SPLUNK_PASSWORD" "")
    if [ -n "$splunk_password" ]; then
        echo "SPLUNK_PASSWORD=$splunk_password" >> "$OUTPUT_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
    
    # CORS Configuration
    echo "# CORS Configuration" >> "$OUTPUT_FILE"
    echo "CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:3001}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Firebase Configuration
    echo "# Firebase Configuration" >> "$OUTPUT_FILE"
    echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> "$OUTPUT_FILE"
    echo "APP_ENV=$ENVIRONMENT" >> "$OUTPUT_FILE"
    
    # Set secure file permissions (owner read/write only)
    chmod 600 "$OUTPUT_FILE"
    
    print_status "Docker secrets loaded to $OUTPUT_FILE with secure permissions (600)"
}

# Create docker-compose override file
create_docker_compose_override() {
    local override_file="docker-compose.secrets.yml"
    
    print_info "Creating Docker Compose override file..."
    
    cat > "$override_file" << 'EOF'
# Docker Compose Override for Secrets
# This file extends docker-compose.yml with secret configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up

version: '3.8'

services:
  olorin-server:
    env_file:
      - .env.docker.secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./service-account.json}:/app/service-account.json:ro
  
  postgres:
    env_file:
      - .env.docker.secrets
  
  redis:
    env_file:
      - .env.docker.secrets
    command: >
      sh -c '
      if [ -n "$$REDIS_PASSWORD" ]; then
        redis-server --requirepass $$REDIS_PASSWORD
      else
        redis-server
      fi
      '
  
  olorin-front:
    env_file:
      - .env.docker.secrets
  
  olorin-web-portal:
    env_file:
      - .env.docker.secrets
EOF
    
    # Set secure file permissions
    chmod 600 "$override_file"
    
    print_status "Docker Compose override file created: $override_file with secure permissions (600)"
}

# Update .gitignore
update_gitignore() {
    if [ -f ".gitignore" ]; then
        if ! grep -q "^\.env\.docker\.secrets$" .gitignore; then
            echo "" >> .gitignore
            echo "# Firebase Secret Manager generated files" >> .gitignore
            echo ".env.docker.secrets" >> .gitignore
            echo "docker-compose.secrets.yml" >> .gitignore
            print_status "Updated .gitignore"
        fi
    fi
}

# Main execution
main() {
    echo "🐳 Docker Secrets Loader for Olorin"
    echo "===================================="
    echo ""
    
    print_info "Environment: $ENVIRONMENT"
    print_info "Firebase Project: $FIREBASE_PROJECT_ID"
    echo ""
    
    # Check prerequisites
    check_gcloud
    authenticate_gcloud
    
    # Load secrets
    load_docker_secrets
    
    # Create Docker Compose override
    create_docker_compose_override
    
    # Update .gitignore
    update_gitignore
    
    echo ""
    echo "📋 Next Steps:"
    echo "1. Ensure you have service account credentials:"
    echo "   export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json"
    echo ""
    echo "2. Start Docker services with secrets:"
    echo "   docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up"
    echo ""
    echo "3. Or source the secrets file directly:"
    echo "   source .env.docker.secrets"
    echo "   docker-compose up"
    echo ""
    print_status "Docker secrets setup complete!"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --env)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --project)
            FIREBASE_PROJECT_ID="$2"
            shift 2
            ;;
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --env ENV           Environment (development, staging, production)"
            echo "  --project PROJECT   Firebase project ID (default: olorin-ai)"
            echo "  --output FILE       Output file for secrets (default: .env.docker.secrets)"
            echo "  --help              Show this help message"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Run main function
main