#!/bin/bash
#
# TypeScript Type Generation Script
#
# Generates TypeScript types from backend OpenAPI schema for type-safe API consumption.
#
# Constitutional Compliance:
# - Backend URL from environment variable (no hardcoded URLs)
# - Output directory from configuration
# - Fail-fast behavior on errors
# - No mocks or stubs in generated types
#
# Usage:
#   ./scripts/generate-api-types.sh [backend_url]
#
# Environment Variables:
#   REACT_APP_API_BASE_URL - Backend API base URL (default: http://localhost:8090)
#   GENERATED_TYPES_DIR - Output directory (default: src/api/generated)
#

set -e  # Exit on error (fail-fast)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get backend URL from environment or argument
BACKEND_URL="${1:-${REACT_APP_API_BASE_URL:-http://localhost:8090}}"
OPENAPI_ENDPOINT="${BACKEND_URL}/openapi.json"

# Output directory from environment or default
OUTPUT_DIR="${GENERATED_TYPES_DIR:-src/api/generated}"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}TypeScript Type Generation${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${YELLOW}Backend URL:${NC} ${BACKEND_URL}"
echo -e "${YELLOW}OpenAPI Endpoint:${NC} ${OPENAPI_ENDPOINT}"
echo -e "${YELLOW}Output Directory:${NC} ${OUTPUT_DIR}"
echo ""

# Check if backend is running
echo -e "${YELLOW}Checking backend availability...${NC}"
if ! curl -f -s "${BACKEND_URL}/health" > /dev/null 2>&1; then
    echo -e "${RED}ERROR: Backend is not running at ${BACKEND_URL}${NC}"
    echo -e "${RED}Please start the backend server first:${NC}"
    echo -e "  cd ../olorin-server && poetry run python -m app.local_server"
    exit 1
fi
echo -e "${GREEN}✓ Backend is running${NC}"
echo ""

# Create output directory if it doesn't exist
echo -e "${YELLOW}Creating output directory...${NC}"
mkdir -p "${OUTPUT_DIR}"
echo -e "${GREEN}✓ Output directory ready: ${OUTPUT_DIR}${NC}"
echo ""

# Download OpenAPI schema
echo -e "${YELLOW}Downloading OpenAPI schema...${NC}"
SCHEMA_FILE="${OUTPUT_DIR}/openapi.json"
if curl -f -s "${OPENAPI_ENDPOINT}" -o "${SCHEMA_FILE}"; then
    echo -e "${GREEN}✓ OpenAPI schema downloaded${NC}"
    echo -e "  File: ${SCHEMA_FILE}"
    echo -e "  Size: $(wc -c < "${SCHEMA_FILE}") bytes"
else
    echo -e "${RED}ERROR: Failed to download OpenAPI schema from ${OPENAPI_ENDPOINT}${NC}"
    exit 1
fi
echo ""

# Validate schema is valid JSON
echo -e "${YELLOW}Validating OpenAPI schema...${NC}"
if ! python3 -m json.tool "${SCHEMA_FILE}" > /dev/null 2>&1; then
    echo -e "${RED}ERROR: Invalid JSON in OpenAPI schema${NC}"
    exit 1
fi
echo -e "${GREEN}✓ OpenAPI schema is valid JSON${NC}"
echo ""

# Generate TypeScript types using openapi-typescript
echo -e "${YELLOW}Generating TypeScript types...${NC}"
if npx openapi-typescript "${SCHEMA_FILE}" --output "${OUTPUT_DIR}/models.ts" --alphabetize; then
    echo -e "${GREEN}✓ TypeScript types generated${NC}"
    echo -e "  File: ${OUTPUT_DIR}/models.ts"
    echo -e "  Size: $(wc -l < "${OUTPUT_DIR}/models.ts") lines"
else
    echo -e "${RED}ERROR: Failed to generate TypeScript types${NC}"
    exit 1
fi
echo ""

# Generate API client using openapi-typescript-codegen
echo -e "${YELLOW}Generating API client...${NC}"
if npx openapi-typescript-codegen --input "${SCHEMA_FILE}" --output "${OUTPUT_DIR}" --client axios; then
    echo -e "${GREEN}✓ API client generated${NC}"
    echo -e "  Directory: ${OUTPUT_DIR}"
else
    echo -e "${RED}ERROR: Failed to generate API client${NC}"
    exit 1
fi
echo ""

# Add header comment to generated files
echo -e "${YELLOW}Adding generation metadata...${NC}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
HEADER="/**
 * Auto-generated TypeScript types from OpenAPI schema
 *
 * Generated: ${TIMESTAMP}
 * Source: ${OPENAPI_ENDPOINT}
 *
 * Constitutional Compliance:
 * - Types generated from backend OpenAPI schema (single source of truth)
 * - No manual edits allowed (regenerate instead)
 * - No hardcoded values in generated types
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate-api-types' to regenerate
 */

"
echo "${HEADER}" | cat - "${OUTPUT_DIR}/models.ts" > "${OUTPUT_DIR}/models.ts.tmp"
mv "${OUTPUT_DIR}/models.ts.tmp" "${OUTPUT_DIR}/models.ts"
echo -e "${GREEN}✓ Generation metadata added${NC}"
echo ""

# Run TypeScript compiler check
echo -e "${YELLOW}Verifying TypeScript compilation...${NC}"
if npx tsc --noEmit "${OUTPUT_DIR}/models.ts"; then
    echo -e "${GREEN}✓ Generated types compile successfully${NC}"
else
    echo -e "${RED}WARNING: Generated types have TypeScript errors${NC}"
    echo -e "${YELLOW}This may indicate issues with the OpenAPI schema${NC}"
fi
echo ""

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Type Generation Complete! ✓${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Generated files:"
echo -e "  ${OUTPUT_DIR}/models.ts - TypeScript type definitions"
echo -e "  ${OUTPUT_DIR}/api.ts - API client functions"
echo ""
echo -e "Next steps:"
echo -e "  1. Import types: ${YELLOW}import { InvestigationRequest } from '@/api/generated/models'${NC}"
echo -e "  2. Use API client: ${YELLOW}import { investigationsApi } from '@/api/generated/api'${NC}"
echo -e "  3. Re-generate after backend changes: ${YELLOW}npm run generate-api-types${NC}"
echo ""
