#!/usr/bin/env python3
"""
Simple test to see the SQL query generated by the analyzer
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv

load_dotenv()

# Set logging to DEBUG to see SQL queries
os.environ["LOG_LEVEL"] = "DEBUG"

import asyncio

from app.service.analytics.risk_analyzer import RiskAnalyzer


async def main():
    analyzer = RiskAnalyzer()

    print("Testing analyzer query generation...")
    print()

    # Call get_top_risk_entities which will log the SQL query
    # Force refresh to bypass any caching
    result = await analyzer.get_top_risk_entities(
        time_window="24h",
        group_by="EMAIL",
        top_percentage=10,
        force_refresh=True,  # Bypass cache
    )

    print()
    print(f"Result status: {result.get('status')}")
    print(f"Entities returned: {len(result.get('entities', []))}")

    if result.get("entities"):
        print()
        print("First 3 entities:")
        for i, entity in enumerate(result.get("entities", [])[:3], 1):
            print(
                f"{i}. {entity.get('entity')}: avg_score={entity.get('avg_risk_score', 0):.3f}, txs={entity.get('transaction_count')}"
            )


if __name__ == "__main__":
    asyncio.run(main())
