apiVersion: v1
kind: Pod
metadata:
  name: PAWS_METADATANAME
  annotations:
    iam.amazonaws.com/role: "${JENKINS_SLAVE_IAM_ROLE}"
spec:
  containers:
  - name: podman
    image: quay.io/podman/stable:latest
    tty: true
    command: ["cat"]
    imagePullPolicy: Always
    volumeMounts:
    - name: container-storage
      mountPath: /var/lib/containers
    resources:
      limits:
        github.com/fuse: 1
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        add: ["SYS_ADMIN", "SYS_RESOURCE"]
  - name: tools
    image: alpine:latest
    tty: true
    command: ["cat"]
    imagePullPolicy: Always
  - name: cdtools
    image: argoproj/argocd:stable
    tty: true
    command: ["cat"]
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
  - name: utility
    image: alpine:latest
    tty: true
    command: ["cat"]
    imagePullPolicy: Always
  - name: api-tools-container
    image: curlimages/curl:latest
    tty: true
    command:
    - cat
    imagePullPolicy: Always
  volumes:
  - name: container-storage
    emptyDir: {}
