import { StyleSheet } from 'react-native';
import { colors, spacing } from '@olorin/design-tokens';

export const styles = StyleSheet.create({
  modal: {
    width: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[4],
    padding: spacing[8],
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  warningIcon: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FCA5A5',
    width: 60,
    height: 60,
    lineHeight: 60,
    textAlign: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    overflow: 'hidden',
  },
  headerText: { flex: 1 },
  title: { fontSize: 36, fontWeight: 'bold', color: colors.white },
  subtitle: { fontSize: 24, color: '#FCA5A5', marginTop: 4 },
  detailsCard: {
    margin: spacing[8],
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: spacing[6],
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  featureText: { fontSize: 26, color: 'rgba(255,255,255,0.8)', marginBottom: spacing[4] },
  creditRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 6 },
  creditLabel: { fontSize: 26, color: 'rgba(255,255,255,0.6)' },
  creditValueWhite: { fontSize: 28, fontWeight: '600', color: colors.white },
  creditValueRed: { fontSize: 28, fontWeight: '600', color: '#FCA5A5' },
  creditValueOrange: { fontSize: 28, fontWeight: 'bold', color: '#FDBA74' },
  divider: { height: 1, backgroundColor: 'rgba(255,255,255,0.1)', marginVertical: spacing[3] },
  infoBox: {
    marginHorizontal: spacing[8],
    marginBottom: spacing[6],
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    borderRadius: 16,
    padding: spacing[6],
  },
  infoTitle: { fontSize: 26, fontWeight: '600', color: '#93C5FD', marginBottom: 6 },
  infoText: { fontSize: 24, color: '#93C5FD', lineHeight: 34 },
  actions: { paddingHorizontal: spacing[8], gap: spacing[4] },
  upgradeButton: {
    backgroundColor: '#7C3AED',
    paddingVertical: spacing[5],
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'transparent',
  },
  secondaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: spacing[5],
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  cancelButton: {
    paddingVertical: spacing[4],
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'transparent',
    borderRadius: 16,
  },
  buttonFocused: {
    borderColor: '#A855F7',
    transform: [{ scale: 1.03 }],
    backgroundColor: 'rgba(168, 85, 247, 0.2)',
  },
  upgradeButtonText: { fontSize: 30, fontWeight: '600', color: colors.white },
  secondaryButtonText: { fontSize: 28, fontWeight: '500', color: colors.white },
  cancelButtonText: { fontSize: 26, color: 'rgba(255, 255, 255, 0.6)' },
  helpText: {
    fontSize: 22,
    color: 'rgba(255, 255, 255, 0.4)',
    textAlign: 'center',
    padding: spacing[6],
  },
});
