# Cloud Build Configuration for Olorin Backend - Cloud Run Deployment
# Replaces Firebase App Hosting with Cloud Run
# Author: Gil Klainert (Updated for Cloud Run)
# Date: 2026-01-15

steps:
  # Note: Tests and quality checks run in GitHub Actions CI
  # Cloud Build focuses on Docker build and deployment

  # ======================================
  # Step 1: Build Docker image with cache optimization
  # ======================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:$BUILD_ID'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '--build-arg'
      - 'APP_ENV=${_APP_ENV}'
      - '--cache-from'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:latest'
      - '.'
    waitFor: ['-']

  # ======================================
  # Step 2: Push Docker image to Artifact Registry
  # ======================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend'
    waitFor: ['build-image']

  # ======================================
  # Step 3: Deploy to Cloud Run
  # ======================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Cloud Run (${_ENVIRONMENT})..."

        # Check if secrets file exists
        if [ -f "cloudrun-secrets.txt" ]; then
          SECRETS_ARG="--set-secrets=$(cat cloudrun-secrets.txt)"
        else
          echo "⚠️ cloudrun-secrets.txt not found, skipping secrets"
          SECRETS_ARG=""
        fi

        gcloud run deploy olorin-fraud-detection-${_ENVIRONMENT} \
          --image=us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:$BUILD_ID \
          --region=${_REGION} \
          --platform=managed \
          --port=8090 \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --concurrency=${_CONCURRENCY} \
          --timeout=${_TIMEOUT} \
          --service-account=${_SERVICE_ACCOUNT} \
          --ingress=all \
          --allow-unauthenticated \
          --execution-environment=gen2 \
          --no-cpu-throttling \
          --set-env-vars="$(cat cloudrun-env-vars.${_ENVIRONMENT}.txt)" \
          $$SECRETS_ARG \
          --project=$PROJECT_ID \
          --quiet

        echo "✅ Deployment to Cloud Run completed"
    waitFor: ['push-image']

  # ======================================
  # Step 4: Verify deployment health
  # ======================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify-health'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏥 Verifying deployment health..."

        # Get service URL
        SVC_URL=$$(gcloud run services describe olorin-fraud-detection-${_ENVIRONMENT} \
          --region=${_REGION} \
          --format='value(status.url)' \
          --project=$PROJECT_ID)

        echo "Service URL: $$SVC_URL"

        # Wait for service to be ready (max 3 minutes)
        for i in {1..18}; do
          HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$$SVC_URL/health" || echo "000")
          if [ "$$HTTP_CODE" = "200" ]; then
            echo "✅ Health check passed (HTTP $$HTTP_CODE)"
            exit 0
          fi
          echo "⏳ Waiting for service... Attempt $$i/18 (HTTP $$HTTP_CODE)"
          sleep 10
        done

        echo "❌ Health check failed after 3 minutes"
        exit 1
    waitFor: ['deploy-cloud-run']

  # ======================================
  # Step 5: Tag image as deployed
  # ======================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-deployed'
    args:
      - 'tag'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:$BUILD_ID'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:deployed-${_ENVIRONMENT}'
    waitFor: ['verify-health']

  # ======================================
  # Step 6: Push deployed tag
  # ======================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-deployed-tag'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:deployed-${_ENVIRONMENT}'
    waitFor: ['tag-deployed']

# Substitution variables (can be overridden in trigger)
substitutions:
  _ENVIRONMENT: 'staging'
  _REGION: 'us-east1'
  _MEMORY: '4Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'
  _TIMEOUT: '300s'
  _SERVICE_ACCOUNT: 'olorin-detection@olorin-fraud-detection.iam.gserviceaccount.com'
  _APP_ENV: 'production'

# Build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Enable more disk space for dependencies
  diskSizeGb: 100

  # Logging configuration
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

  # Substitution option
  substitutionOption: ALLOW_LOOSE

# Build timeout (30 minutes for Docker builds and deployment)
timeout: '1800s'

# Artifacts to store
artifacts:
  images:
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:$BUILD_ID'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:latest'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/olorin/backend:deployed-${_ENVIRONMENT}'
