/**
 * DEMO-ONLY: Demo live TV channel data for testing live streaming features.
 * Not used in production.
 */

import { LiveChannel } from './types';

export const demoChannels: LiveChannel[] = [
  {
    id: 'kan11',
    name: 'כאן 11',
    name_en: 'Kan 11',
    name_es: 'Kan 11',
    logo: 'https://picsum.photos/200/200?random=301',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'general',
    epg_id: 'kan11.il',
    current_program: 'חדשות הבוקר',
    current_program_en: 'Morning News',
    current_program_es: 'Noticias de la Manana',
    is_hd: true,
  },
  {
    id: 'keshet12',
    name: 'קשת 12',
    name_en: 'Keshet 12',
    name_es: 'Keshet 12',
    logo: 'https://picsum.photos/200/200?random=302',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'general',
    epg_id: 'keshet12.il',
    current_program: 'פאודה - פרק 5',
    current_program_en: 'Fauda - Episode 5',
    current_program_es: 'Fauda - Episodio 5',
    is_hd: true,
  },
  {
    id: 'reshet13',
    name: 'רשת 13',
    name_en: 'Reshet 13',
    name_es: 'Reshet 13',
    logo: 'https://picsum.photos/200/200?random=303',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'general',
    epg_id: 'reshet13.il',
    current_program: 'חדשות 13',
    current_program_en: 'News 13',
    current_program_es: 'Noticias 13',
    is_hd: true,
  },
  {
    id: 'channel14',
    name: 'ערוץ 14',
    name_en: 'Channel 14',
    name_es: 'Canal 14',
    logo: 'https://picsum.photos/200/200?random=304',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'news',
    epg_id: 'ch14.il',
    current_program: 'פגוש את העיתונות',
    current_program_en: 'Meet the Press',
    current_program_es: 'Encuentro con la Prensa',
    is_hd: false,
  },
  {
    id: 'sport5',
    name: 'ספורט 5',
    name_en: 'Sport 5',
    name_es: 'Deporte 5',
    logo: 'https://picsum.photos/200/200?random=305',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'sports',
    epg_id: 'sport5.il',
    current_program: 'משחק הליגה',
    current_program_en: 'League Match',
    current_program_es: 'Partido de Liga',
    is_hd: true,
  },
  {
    id: 'yes_drama',
    name: 'yes דרמה',
    name_en: 'Yes Drama',
    name_es: 'Yes Drama',
    logo: 'https://picsum.photos/200/200?random=306',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'entertainment',
    epg_id: 'yesdrama.il',
    current_program: 'שטיסל - עונה 3',
    current_program_en: 'Shtisel - Season 3',
    current_program_es: 'Shtisel - Temporada 3',
    is_hd: true,
  },
];
