/**
 * DEMO-ONLY: Demo movie data for testing VOD features.
 * Not used in production.
 */

import { ContentItem } from './types';

export const demoMovies: ContentItem[] = [
  {
    id: 'movie-1',
    title: 'וואלס עם באשיר',
    title_en: 'Waltz with Bashir',
    title_es: 'Vals con Bashir',
    description: 'סרט אנימציה דוקומנטרי על מלחמת לבנון הראשונה',
    description_en: 'Animated documentary about the First Lebanon War',
    description_es: 'Documental animado sobre la Primera Guerra del Líbano',
    type: 'movie',
    genre: 'documentary',
    year: 2008,
    duration: 90,
    rating: 'R',
    thumbnail: 'https://picsum.photos/400/600?random=101',
    backdrop: 'https://picsum.photos/1280/720?random=201',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'movie-2',
    title: 'לבנון',
    title_en: 'Lebanon',
    title_es: 'Líbano',
    description: 'דרמת מלחמה מתוך טנק בזמן מלחמת לבנון',
    description_en: 'War drama from inside a tank during the Lebanon War',
    description_es: 'Drama bélico desde dentro de un tanque durante la Guerra del Líbano',
    type: 'movie',
    genre: 'drama',
    year: 2009,
    duration: 93,
    rating: 'R',
    thumbnail: 'https://picsum.photos/400/600?random=102',
    backdrop: 'https://picsum.photos/1280/720?random=202',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'movie-3',
    title: 'פוקסטרוט',
    title_en: 'Foxtrot',
    title_es: 'Foxtrot',
    description: 'דרמה על משפחה ישראלית מתמודדת עם אובדן',
    description_en: 'Drama about an Israeli family coping with loss',
    description_es: 'Drama sobre una familia israelí enfrentando la pérdida',
    type: 'movie',
    genre: 'drama',
    year: 2017,
    duration: 113,
    rating: 'R',
    thumbnail: 'https://picsum.photos/400/600?random=103',
    backdrop: 'https://picsum.photos/1280/720?random=203',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'movie-4',
    title: 'הערת שוליים',
    title_en: 'Footnote',
    title_es: 'Nota al Pie',
    description: 'קומדיה דרמטית על שני חוקרי תלמוד',
    description_en: 'Dramatic comedy about two Talmud scholars',
    description_es: 'Comedia dramática sobre dos eruditos del Talmud',
    type: 'movie',
    genre: 'comedy',
    year: 2011,
    duration: 105,
    rating: 'PG-13',
    thumbnail: 'https://picsum.photos/400/600?random=104',
    backdrop: 'https://picsum.photos/1280/720?random=204',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'movie-5',
    title: 'גט',
    title_en: 'Gett: The Trial of Viviane Amsalem',
    title_es: 'Gett: El Juicio de Viviane Amsalem',
    description: 'דרמה על אישה נלחמת לקבל גט בבית הדין הרבני',
    description_en: 'Drama about a woman fighting for divorce in rabbinical court',
    description_es: 'Drama sobre una mujer luchando por el divorcio en un tribunal rabínico',
    type: 'movie',
    genre: 'drama',
    year: 2014,
    duration: 115,
    rating: 'PG-13',
    thumbnail: 'https://picsum.photos/400/600?random=105',
    backdrop: 'https://picsum.photos/1280/720?random=205',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
];
