/**
 * DEMO-ONLY: Demo podcast data for testing audio content features.
 * Not used in production.
 */

import { Podcast } from './types';

export const demoPodcastCategories = [
  { id: 'history', name: 'היסטוריה', name_en: 'History', name_es: 'Historia' },
  { id: 'entertainment', name: 'בידור', name_en: 'Entertainment', name_es: 'Entretenimiento' },
  { id: 'business', name: 'עסקים', name_en: 'Business', name_es: 'Negocios' },
  { id: 'news', name: 'חדשות', name_en: 'News', name_es: 'Noticias' },
  { id: 'comedy', name: 'קומדיה', name_en: 'Comedy', name_es: 'Comedia' },
  { id: 'tech', name: 'טכנולוגיה', name_en: 'Technology', name_es: 'Tecnologia' },
];

export const demoPodcasts: Podcast[] = [
  {
    id: 'podcast-1',
    title: 'עושים היסטוריה',
    title_en: 'Making History',
    title_es: 'Haciendo Historia',
    host: 'רן לוי',
    host_en: 'Ran Levi',
    host_es: 'Ran Levi',
    description: 'פודקאסט היסטוריה פופולרי בעברית',
    description_en: 'Popular Hebrew history podcast',
    description_es: 'Podcast de historia popular en hebreo',
    thumbnail: 'https://picsum.photos/400/400?random=501',
    category: 'history',
    episodes: [
      {
        id: 'ep-1-1',
        title: 'מלחמת העולם הראשונה',
        description: 'סיפורה של המלחמה הגדולה',
        duration: 3600,
        published_at: '2024-01-15',
        audio_url: 'https://example.com/podcast.mp3',
      },
      {
        id: 'ep-1-2',
        title: 'המהפכה הצרפתית',
        description: 'איך נפלה המלוכה בצרפת',
        duration: 2700,
        published_at: '2024-01-08',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
  {
    id: 'podcast-2',
    title: 'הפודקאסט של דוד והדר',
    title_en: 'David and Hadar Podcast',
    title_es: 'El Podcast de David y Hadar',
    host: 'דוד והדר',
    host_en: 'David and Hadar',
    host_es: 'David y Hadar',
    description: 'שיחות על החיים, הקולנוע והכל',
    description_en: 'Conversations about life, cinema and everything',
    description_es: 'Conversaciones sobre la vida, el cine y todo',
    thumbnail: 'https://picsum.photos/400/400?random=502',
    category: 'entertainment',
    episodes: [
      {
        id: 'ep-2-1',
        title: 'סרטי 2024',
        description: 'סיכום שנת הקולנוע',
        duration: 4200,
        published_at: '2024-01-20',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
  {
    id: 'podcast-3',
    title: 'כלכליסט',
    title_en: 'Calcalist',
    title_es: 'Calcalist',
    host: 'אבירם אלעד',
    host_en: 'Aviram Elad',
    host_es: 'Aviram Elad',
    description: 'פודקאסט הכלכלה המוביל',
    description_en: 'The leading economy podcast',
    description_es: 'El podcast de economia lider',
    thumbnail: 'https://picsum.photos/400/400?random=503',
    category: 'business',
    episodes: [
      {
        id: 'ep-3-1',
        title: 'שוק ההייטק 2024',
        description: 'מגמות בהייטק הישראלי',
        duration: 1800,
        published_at: '2024-01-22',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
  {
    id: 'podcast-4',
    title: 'סדנא לחדשות',
    title_en: 'News Workshop',
    title_es: 'Taller de Noticias',
    host: 'ירדן בכר',
    host_en: 'Yarden Bachar',
    host_es: 'Yarden Bachar',
    description: 'מאחורי הקלעים של החדשות',
    description_en: 'Behind the scenes of the news',
    description_es: 'Detras de las escenas de las noticias',
    thumbnail: 'https://picsum.photos/400/400?random=504',
    category: 'news',
    episodes: [
      {
        id: 'ep-4-1',
        title: 'שנה של בחירות',
        description: 'מבט מאחורי הקלעים',
        duration: 2400,
        published_at: '2024-01-18',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
  {
    id: 'podcast-5',
    title: 'הקצה',
    title_en: 'The Edge',
    title_es: 'El Borde',
    host: 'גיא מרוז',
    host_en: 'Guy Maroz',
    host_es: 'Guy Maroz',
    description: 'פודקאסט קומדיה סטנדאפ',
    description_en: 'Stand-up comedy podcast',
    description_es: 'Podcast de comedia stand-up',
    thumbnail: 'https://picsum.photos/400/400?random=505',
    category: 'comedy',
    episodes: [
      {
        id: 'ep-5-1',
        title: 'סטנדאפ חי',
        description: 'הקלטה מהופעה חיה',
        duration: 3600,
        published_at: '2024-01-25',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
  {
    id: 'podcast-6',
    title: 'גיקטיים',
    title_en: 'Geektime',
    title_es: 'Geektime',
    host: 'צוות גיקטיים',
    host_en: 'Geektime Team',
    host_es: 'Equipo Geektime',
    description: 'חדשות הייטק וסטארטאפים',
    description_en: 'Tech and startup news',
    description_es: 'Noticias de tecnologia y startups',
    thumbnail: 'https://picsum.photos/400/400?random=506',
    category: 'tech',
    episodes: [
      {
        id: 'ep-6-1',
        title: 'AI בישראל',
        description: 'המהפכה של הבינה המלאכותית',
        duration: 2700,
        published_at: '2024-01-28',
        audio_url: 'https://example.com/podcast.mp3',
      },
    ],
  },
];
