/**
 * DEMO-ONLY: Demo TV series data for testing VOD features.
 * Not used in production.
 */

import { ContentItem } from './types';

export const demoSeries: ContentItem[] = [
  {
    id: 'series-1',
    title: 'פאודה',
    title_en: 'Fauda',
    title_es: 'Fauda',
    description: 'סדרת מתח על יחידה מסתערבים',
    description_en: 'Thriller series about an undercover unit',
    description_es: 'Serie de suspenso sobre una unidad encubierta',
    type: 'series',
    genre: 'action',
    year: 2015,
    duration: 45,
    rating: 'TV-MA',
    thumbnail: 'https://picsum.photos/400/600?random=111',
    backdrop: 'https://picsum.photos/1280/720?random=211',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 4,
    episodes: 48,
  },
  {
    id: 'series-2',
    title: 'שטיסל',
    title_en: 'Shtisel',
    title_es: 'Shtisel',
    description: 'דרמה על משפחה חרדית בירושלים',
    description_en: 'Drama about an ultra-Orthodox family in Jerusalem',
    description_es: 'Drama sobre una familia ultraortodoxa en Jerusalén',
    type: 'series',
    genre: 'drama',
    year: 2013,
    duration: 45,
    rating: 'TV-14',
    thumbnail: 'https://picsum.photos/400/600?random=112',
    backdrop: 'https://picsum.photos/1280/720?random=212',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 3,
    episodes: 33,
  },
  {
    id: 'series-3',
    title: 'טהרן',
    title_en: 'Tehran',
    title_es: 'Teherán',
    description: 'סדרת ריגול על סוכנת מוסד באיראן',
    description_en: 'Spy series about a Mossad agent in Iran',
    description_es: 'Serie de espionaje sobre una agente del Mossad en Irán',
    type: 'series',
    genre: 'thriller',
    year: 2020,
    duration: 50,
    rating: 'TV-MA',
    thumbnail: 'https://picsum.photos/400/600?random=113',
    backdrop: 'https://picsum.photos/1280/720?random=213',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 2,
    episodes: 16,
  },
  {
    id: 'series-4',
    title: 'הבורר',
    title_en: 'The Arbitrator',
    title_es: 'El Árbitro',
    description: 'קומדיה על בורר בסכסוכים בשכונה',
    description_en: 'Comedy about a neighborhood dispute arbitrator',
    description_es: 'Comedia sobre un árbitro de disputas vecinales',
    type: 'series',
    genre: 'comedy',
    year: 2010,
    duration: 30,
    rating: 'TV-14',
    thumbnail: 'https://picsum.photos/400/600?random=114',
    backdrop: 'https://picsum.photos/1280/720?random=214',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 3,
    episodes: 36,
  },
  {
    id: 'series-5',
    title: 'עבודה ערבית',
    title_en: 'Arab Labor',
    title_es: 'Trabajo Árabe',
    description: 'קומדיה סאטירית על יחסי יהודים-ערבים',
    description_en: 'Satirical comedy about Jewish-Arab relations',
    description_es: 'Comedia satírica sobre las relaciones judeo-árabes',
    type: 'series',
    genre: 'comedy',
    year: 2007,
    duration: 25,
    rating: 'TV-14',
    thumbnail: 'https://picsum.photos/400/600?random=115',
    backdrop: 'https://picsum.photos/1280/720?random=215',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 4,
    episodes: 52,
  },
  {
    id: 'series-6',
    title: 'בית לחם',
    title_en: 'Bethlehem',
    description: 'דרמת מתח על יחסי מפעיל ומקור',
    type: 'series',
    genre: 'thriller',
    year: 2013,
    duration: 50,
    rating: 'TV-MA',
    thumbnail: 'https://picsum.photos/400/600?random=116',
    backdrop: 'https://picsum.photos/1280/720?random=216',
    stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    seasons: 1,
    episodes: 10,
  },
];
