package tv.bayit.plus.core.data.repository.impl

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.PUT
import retrofit2.http.Path
import retrofit2.http.Query
import tv.bayit.plus.core.model.ExternalSubtitleImportResponse
import tv.bayit.plus.core.model.SubtitleCuesResponse
import tv.bayit.plus.core.model.TranslationResult

/**
 * Retrofit service for all subtitle-related API endpoints.
 */
internal interface SubtitleService {

    @GET("api/v1/subtitles/{contentId}")
    suspend fun getAvailableTracks(
        @Path("contentId") contentId: String,
    ): SubtitleTracksResponse

    @GET("api/v1/subtitles/{contentId}")
    suspend fun getSubtitleTrack(
        @Path("contentId") contentId: String,
        @Query("language") language: String,
    ): SubtitleTrackDetail

    @GET("api/v1/subtitles/preferences")
    suspend fun getSubtitlePreferences(): SubtitlePreferencesResponse

    @PUT("api/v1/subtitles/preferences")
    suspend fun updateSubtitlePreferences(
        @Body body: SubtitlePreferencesBody,
    ): SubtitlePreferencesResponse

    @POST("api/v1/subtitles/request")
    suspend fun requestSubtitle(
        @Body body: SubtitleRequestBody,
    ): SubtitleRequestResponse

    @GET("api/v1/subtitles/{contentId}/cues")
    suspend fun getCues(
        @Path("contentId") contentId: String,
        @Query("language") language: String,
        @Query("hebrew_mode") hebrewMode: String? = null,
        @Query("english_mode") englishMode: String? = null,
    ): SubtitleCuesResponse

    @POST("api/v1/subtitles/{contentId}/fetch-external")
    suspend fun fetchExternalSubtitles(
        @Path("contentId") contentId: String,
    ): ExternalSubtitleImportResponse

    @POST("api/v1/subtitles/translate")
    suspend fun translateWord(
        @Body body: TranslateBody,
    ): TranslationResult

    @POST("api/v1/subtitles/translate-phrase")
    suspend fun translatePhrase(
        @Body body: TranslateBody,
    ): TranslationResult

    @GET("api/v1/subtitles/preferences/{contentId}")
    suspend fun getContentPreferences(
        @Path("contentId") contentId: String,
    ): SubtitlePreferencesResponse

    @POST("api/v1/subtitles/preferences/{contentId}")
    suspend fun updateContentPreferences(
        @Path("contentId") contentId: String,
        @Body body: SubtitlePreferencesBody,
    ): SubtitlePreferencesResponse
}

@Serializable
internal data class SubtitleTracksResponse(
    val tracks: List<SubtitleTrackItem> = emptyList(),
)

@Serializable
internal data class SubtitleTrackItem(
    val id: String,
    @SerialName("content_id") val contentId: String,
    val language: String,
    @SerialName("language_name") val languageName: String? = null,
    val format: String? = null,
    @SerialName("has_nikud_version") val hasNikudVersion: Boolean? = null,
    @SerialName("has_shoresh_version") val hasShoreshVersion: Boolean? = null,
    @SerialName("has_heblish_version") val hasHeblishVersion: Boolean? = null,
    @SerialName("has_engrew_version") val hasEngrewVersion: Boolean? = null,
    @SerialName("is_default") val isDefault: Boolean? = null,
    @SerialName("is_auto_generated") val isAutoGenerated: Boolean? = null,
    @SerialName("cue_count") val cueCount: Int? = null,
)

@Serializable
internal data class SubtitleTrackDetail(
    val tracks: List<SubtitleTrackItem> = emptyList(),
)

@Serializable
internal data class SubtitlePreferencesResponse(
    val preferences: List<SubtitlePreferenceItem> = emptyList(),
    val total: Int? = null,
)

@Serializable
internal data class SubtitlePreferenceItem(
    @SerialName("content_id") val contentId: String,
    @SerialName("preferred_language") val preferredLanguage: String? = null,
    @SerialName("hebrew_mode") val hebrewMode: String? = null,
    @SerialName("last_used_at") val lastUsedAt: String? = null,
)

@Serializable
internal data class SubtitlePreferencesBody(
    val language: String? = null,
    @SerialName("hebrew_mode") val hebrewMode: String? = null,
    @SerialName("english_mode") val englishMode: String? = null,
    @SerialName("font_size") val fontSize: Float? = null,
    @SerialName("show_background") val showBackground: Boolean? = null,
)

@Serializable
internal data class SubtitleRequestBody(
    @SerialName("content_id") val contentId: String,
    val language: String,
)

@Serializable
internal data class SubtitleRequestResponse(
    val status: String? = null,
    val message: String? = null,
)

@Serializable
internal data class TranslateBody(
    val text: String,
    @SerialName("source_language") val sourceLanguage: String,
    @SerialName("target_language") val targetLanguage: String,
)
