package tv.bayit.plus.core.data.repository.impl

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
internal data class SubtitleTracksResponse(
    val tracks: List<SubtitleTrackItem> = emptyList(),
)

@Serializable
internal data class SubtitleTrackItem(
    val id: String,
    @SerialName("content_id") val contentId: String,
    val language: String,
    @SerialName("language_name") val languageName: String? = null,
    val format: String? = null,
    @SerialName("has_nikud_version") val hasNikudVersion: Boolean? = null,
    @SerialName("has_shoresh_version") val hasShoreshVersion: Boolean? = null,
    @SerialName("has_heblish_version") val hasHeblishVersion: Boolean? = null,
    @SerialName("has_engrew_version") val hasEngrewVersion: Boolean? = null,
    @SerialName("is_default") val isDefault: Boolean? = null,
    @SerialName("is_auto_generated") val isAutoGenerated: Boolean? = null,
    @SerialName("cue_count") val cueCount: Int? = null,
)

@Serializable
internal data class SubtitleTrackDetail(
    val tracks: List<SubtitleTrackItem> = emptyList(),
)

@Serializable
internal data class SubtitlePreferencesResponse(
    val preferences: List<SubtitlePreferenceItem> = emptyList(),
    val total: Int? = null,
)

@Serializable
internal data class SubtitlePreferenceItem(
    @SerialName("content_id") val contentId: String,
    @SerialName("preferred_language") val preferredLanguage: String? = null,
    @SerialName("hebrew_mode") val hebrewMode: String? = null,
    @SerialName("last_used_at") val lastUsedAt: String? = null,
)

@Serializable
internal data class SubtitlePreferencesBody(
    val language: String? = null,
    @SerialName("hebrew_mode") val hebrewMode: String? = null,
    @SerialName("english_mode") val englishMode: String? = null,
    @SerialName("font_size") val fontSize: Float? = null,
    @SerialName("show_background") val showBackground: Boolean? = null,
)

@Serializable
internal data class SubtitleDeletePreferenceResponse(
    val status: String? = null,
    @SerialName("content_id") val contentId: String? = null,
    val message: String? = null,
)

@Serializable
internal data class AIGenerationJobResponse(
    @SerialName("job_id") val jobId: String? = null,
    @SerialName("content_id") val contentId: String? = null,
    @SerialName("job_type") val jobType: String? = null,
    val status: String? = null,
    val progress: Double? = null,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("completed_at") val completedAt: String? = null,
    val message: String? = null,
    val error: String? = null,
)

@Serializable
internal data class CancelJobResponse(
    val message: String? = null,
    val job: AIGenerationJobResponse? = null,
)

@Serializable
internal data class ActiveJobsResponse(
    @SerialName("content_id") val contentId: String? = null,
    @SerialName("nikud_job") val nikudJob: AIGenerationJobResponse? = null,
    @SerialName("shoresh_job") val shoreshJob: AIGenerationJobResponse? = null,
    @SerialName("heblish_job") val heblishJob: AIGenerationJobResponse? = null,
    @SerialName("grammar_flip_job") val grammarFlipJob: AIGenerationJobResponse? = null,
    @SerialName("slang_synthesis_job") val slangSynthesisJob: AIGenerationJobResponse? = null,
    @SerialName("engrew_job") val engrewJob: AIGenerationJobResponse? = null,
)
