import BayitDesignSystem
import SwiftUI
import UIKit

/// Interactive subtitle overlay with word-level tap-to-translate and mode selection.
/// Supports shoresh highlighting, AI-generated indicators, and trivia-aware positioning.
struct InteractiveSubtitlesOverlay: View {
    @Bindable var viewModel: InteractiveSubtitlesViewModel
    let contentId: String
    let currentTime: Double
    let isTriviaActive: Bool
    var language: String?
    let repository: SubtitleRepository

    @State private var showModePicker = false
    @State private var showAISubtitlePicker = false

    var body: some View {
        VStack {
            Spacer()

            if let cue = viewModel.activeCue {
                cueView(cue)
                    .padding(.horizontal, DesignTokens.Spacing.lg)
                    .padding(.bottom, isTriviaActive ? 160 : 140)
            }
        }
        .overlay {
            if viewModel.showTranslation, let translation = viewModel.translation {
                TranslationPopoverView(
                    translation: translation,
                    onDismiss: { viewModel.dismissTranslation() }
                )
            }
        }
        .onChange(of: currentTime) { _, newTime in
            viewModel.updateActiveCue(currentTime: newTime)
        }
        .task {
            await viewModel.loadCues(contentId: contentId, language: language)
        }
        .sheet(isPresented: $showModePicker) {
            if let language = language {
                SubtitleModePicker(
                    language: language,
                    currentHebrewMode: viewModel.hebrewMode,
                    currentEnglishMode: viewModel.englishMode,
                    availableModes: viewModel.activeCue,
                    onHebrewModeSelect: { mode in
                        Task {
                            await viewModel.setHebrewMode(mode, contentId: contentId, language: language)
                        }
                    },
                    onEnglishModeSelect: { mode in
                        Task {
                            await viewModel.setEnglishMode(mode, contentId: contentId, language: language)
                        }
                    }
                )
            }
        }
        .sheet(isPresented: $showAISubtitlePicker) {
            if language == "he" {
                AISubtitlesPickerView(
                    contentId: contentId,
                    currentMode: viewModel.hebrewMode,
                    hasHebrew: true,
                    hasNikud: viewModel.hasNikud,
                    hasShoresh: viewModel.hasShoresh,
                    hasHeblish: viewModel.hasHeblish,
                    isAdmin: viewModel.isAdmin,
                    repository: repository,
                    onModeSelect: { mode in
                        Task {
                            await viewModel.setHebrewMode(mode, contentId: contentId, language: language ?? "he")
                        }
                    },
                    onGenerationComplete: {
                        Task {
                            await viewModel.loadCues(contentId: contentId, language: language)
                        }
                    }
                )
            }
        }
    }

    private func cueView(_ cue: SubtitleCue) -> some View {
        HStack {
            Spacer()

            VStack(spacing: DesignTokens.Spacing.xs) {
                HStack(spacing: DesignTokens.Spacing.xs) {
                    // AI-generated indicator
                    if cue.isAutoGenerated == true {
                        Image(systemName: "sparkles")
                            .font(.system(size: 10))
                            .foregroundColor(DesignTokens.Primary.p400)
                    }

                    subtitleContent(cue)

                    // Mode picker button (AI picker for Hebrew, regular picker for other languages)
                    Button {
                        if language == "he" {
                            showAISubtitlePicker = true
                        } else {
                            showModePicker = true
                        }
                    } label: {
                        Image(systemName: language == "he" ? "sparkles" : "gear")
                            .font(.system(size: 14))
                            .foregroundColor(language == "he" ? DesignTokens.Primary.p400 : DesignTokens.Text.muted)
                    }
                    .accessibilityLabel(language == "he" ? "AI subtitle mode settings" : "Subtitle mode settings")
                }
            }

            Spacer()
        }
    }

    private func subtitleContent(_ cue: SubtitleCue) -> some View {
        Group {
            if viewModel.hebrewMode == .shoresh && !viewModel.shoreshWords.isEmpty {
                ShoreshHighlightView(words: viewModel.shoreshWords)
            } else if let words = cue.words, !words.isEmpty {
                WrappingHStack(words: words) { word in
                    wordButton(word)
                }
                .frame(maxWidth: UIScreen.main.bounds.width * 0.9)
                .padding(.horizontal, DesignTokens.Spacing.md)
                .padding(.vertical, DesignTokens.Spacing.sm)
                .background(Color.black.opacity(0.6))
                .cornerRadius(DesignTokens.Radius.sm)
                .environment(\.layoutDirection, language == "he" ? .rightToLeft : .leftToRight)
            } else {
                Text(viewModel.activeText)
                    .font(.system(size: DesignTokens.FontSize.lg))
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: UIScreen.main.bounds.width * 0.9)
                    .padding(.horizontal, DesignTokens.Spacing.md)
                    .padding(.vertical, DesignTokens.Spacing.sm)
                    .background(Color.black.opacity(0.6))
                    .cornerRadius(DesignTokens.Radius.sm)
                    .environment(\.layoutDirection, language == "he" ? .rightToLeft : .leftToRight)
            }
        }
    }

    private func wordButton(_ word: SubtitleWord) -> some View {
        Button {
            if let wordText = word.word, word.isHebrew == true {
                let generator = UIImpactFeedbackGenerator(style: .light)
                generator.impactOccurred()
                Task { await viewModel.translateWord(wordText) }
            }
        } label: {
            Text(word.word ?? "")
                .font(.system(size: DesignTokens.FontSize.lg))
                .foregroundColor(
                    word.isHebrew == true ? DesignTokens.Primary.p300 : .white
                )
                .underline(word.isHebrew == true, color: DesignTokens.Primary.p300.opacity(0.4))
        }
        .buttonStyle(.plain)
        .disabled(viewModel.isTranslating)
        .accessibilityLabel("Translate \(word.word ?? "")")
    }
}

/// Wrapping layout for word-level subtitle display that properly handles multi-line text
private struct WrappingHStack<Content: View>: View {
    let words: [SubtitleWord]
    @ViewBuilder let content: (SubtitleWord) -> Content

    var body: some View {
        FlowLayout(spacing: 8) {
            ForEach(words, id: \.stableId) { word in
                content(word)
            }
        }
    }
}

/// Custom flow layout that wraps content to multiple lines
private struct FlowLayout: Layout {
    var spacing: CGFloat = 8

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) -> CGSize {
        let result = FlowResult(
            in: proposal.replacingUnspecifiedDimensions().width,
            subviews: subviews,
            spacing: spacing
        )
        return result.size
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) {
        let result = FlowResult(
            in: bounds.width,
            subviews: subviews,
            spacing: spacing
        )
        for (index, subview) in subviews.enumerated() {
            let position = result.positions[index]
            subview.place(
                at: CGPoint(x: bounds.minX + position.x, y: bounds.minY + position.y),
                proposal: ProposedViewSize(result.sizes[index])
            )
        }
    }

    struct FlowResult {
        var sizes: [CGSize] = []
        var positions: [CGPoint] = []
        var size: CGSize = .zero

        init(in maxWidth: CGFloat, subviews: Subviews, spacing: CGFloat) {
            var currentX: CGFloat = 0
            var currentY: CGFloat = 0
            var lineHeight: CGFloat = 0
            var maxWidth: CGFloat = maxWidth

            for subview in subviews {
                let size = subview.sizeThatFits(.unspecified)
                sizes.append(size)

                if currentX + size.width > maxWidth && currentX > 0 {
                    // Move to next line
                    currentX = 0
                    currentY += lineHeight + spacing
                    lineHeight = 0
                }

                positions.append(CGPoint(x: currentX, y: currentY))
                lineHeight = max(lineHeight, size.height)
                currentX += size.width + spacing
            }

            self.size = CGSize(
                width: maxWidth,
                height: currentY + lineHeight
            )
        }
    }
}
