import BayitDesignSystem
import SwiftUI
import UIKit

/// Interactive subtitle overlay with word-level tap-to-translate and mode selection.
/// Supports shoresh highlighting, AI-generated indicators, and trivia-aware positioning.
struct InteractiveSubtitlesOverlay: View {
    @Bindable var viewModel: InteractiveSubtitlesViewModel
    let contentId: String
    let currentTime: Double
    let isTriviaActive: Bool
    var language: String?

    @State private var showModePicker = false

    var body: some View {
        VStack {
            Spacer()

            if let cue = viewModel.activeCue {
                cueView(cue)
                    .padding(.horizontal, DesignTokens.Spacing.lg)
                    .padding(.bottom, isTriviaActive ? DesignTokens.Spacing.xxxl : DesignTokens.Spacing.xxxxl)
            }
        }
        .overlay {
            if viewModel.showTranslation, let translation = viewModel.translation {
                TranslationPopoverView(
                    translation: translation,
                    onDismiss: { viewModel.dismissTranslation() }
                )
            }
        }
        .onChange(of: currentTime) { _, newTime in
            viewModel.updateActiveCue(currentTime: newTime)
        }
        .task {
            await viewModel.loadCues(contentId: contentId, language: language)
        }
        .sheet(isPresented: $showModePicker) {
            if let language = language {
                SubtitleModePicker(
                    language: language,
                    currentHebrewMode: viewModel.hebrewMode,
                    currentEnglishMode: viewModel.englishMode,
                    availableModes: viewModel.activeCue,
                    onHebrewModeSelect: { mode in
                        Task {
                            await viewModel.setHebrewMode(mode, contentId: contentId, language: language)
                        }
                    },
                    onEnglishModeSelect: { mode in
                        Task {
                            await viewModel.setEnglishMode(mode, contentId: contentId, language: language)
                        }
                    }
                )
            }
        }
    }

    private func cueView(_ cue: SubtitleCue) -> some View {
        HStack {
            Spacer()

            VStack(spacing: DesignTokens.Spacing.xs) {
                HStack(spacing: DesignTokens.Spacing.xs) {
                    // AI-generated indicator
                    if cue.isAutoGenerated == true {
                        Image(systemName: "sparkles")
                            .font(.system(size: 10))
                            .foregroundColor(DesignTokens.Primary.p400)
                    }

                    subtitleContent(cue)

                    // Mode picker button
                    Button {
                        showModePicker = true
                    } label: {
                        Image(systemName: "gear")
                            .font(.system(size: 14))
                            .foregroundColor(DesignTokens.Text.muted)
                    }
                    .accessibilityLabel("Subtitle mode settings")
                }
            }

            Spacer()
        }
    }

    private func subtitleContent(_ cue: SubtitleCue) -> some View {
        Group {
            if viewModel.hebrewMode == .shoresh && !viewModel.shoreshWords.isEmpty {
                ShoreshHighlightView(words: viewModel.shoreshWords)
            } else if let words = cue.words, !words.isEmpty {
                WrappingHStack(words: words) { word in
                    wordButton(word)
                }
                .padding(.horizontal, DesignTokens.Spacing.md)
                .padding(.vertical, DesignTokens.Spacing.sm)
                .background(Color.black.opacity(0.6))
                .cornerRadius(DesignTokens.Radius.sm)
                .environment(\.layoutDirection, .rightToLeft)
            } else {
                Text(viewModel.activeText)
                    .font(.system(size: DesignTokens.FontSize.lg))
                    .foregroundColor(.white)
                    .padding(.horizontal, DesignTokens.Spacing.md)
                    .padding(.vertical, DesignTokens.Spacing.sm)
                    .background(Color.black.opacity(0.6))
                    .cornerRadius(DesignTokens.Radius.sm)
                    .environment(\.layoutDirection, language == "he" ? .rightToLeft : .leftToRight)
            }
        }
    }

    private func wordButton(_ word: SubtitleWord) -> some View {
        Button {
            if let wordText = word.word, word.isHebrew == true {
                let generator = UIImpactFeedbackGenerator(style: .light)
                generator.impactOccurred()
                Task { await viewModel.translateWord(wordText) }
            }
        } label: {
            Text(word.word ?? "")
                .font(.system(size: DesignTokens.FontSize.lg))
                .foregroundColor(
                    word.isHebrew == true ? DesignTokens.Primary.p300 : .white
                )
                .underline(word.isHebrew == true, color: DesignTokens.Primary.p300.opacity(0.4))
        }
        .buttonStyle(.plain)
        .disabled(viewModel.isTranslating)
        .accessibilityLabel("Translate \(word.word ?? "")")
    }
}

/// Simple wrapping horizontal layout for word-level subtitle display
private struct WrappingHStack<Content: View>: View {
    let words: [SubtitleWord]
    @ViewBuilder let content: (SubtitleWord) -> Content

    var body: some View {
        HStack(spacing: 4) {
            ForEach(words, id: \.stableId) { word in
                content(word)
            }
        }
    }
}
