#!/bin/bash
#
# Sync Google Cloud Secrets to .env files using secrets-manifest.json
# This script pulls secrets from Google Cloud Secret Manager and regenerates .env files
#
# Usage: ./scripts/backend/sync-gcloud-secrets.sh [--dry-run]
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MANIFEST_FILE="$PROJECT_ROOT/scripts/config/secrets-manifest.json"

DRY_RUN=false
if [[ "$1" == "--dry-run" ]]; then
  DRY_RUN=true
  echo "🔍 DRY RUN MODE - No files will be modified"
  echo ""
fi

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔐 Bayit+ Secrets Sync - Google Cloud Secret Manager${NC}"
echo "=================================================="
echo ""

# Check if jq is installed
if ! command -v jq &> /dev/null; then
  echo -e "${RED}❌ Error: jq is not installed${NC}"
  echo "Install with: brew install jq (macOS) or apt-get install jq (Linux)"
  exit 1
fi

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
  echo -e "${RED}❌ Error: gcloud CLI is not installed${NC}"
  echo "Install from: https://cloud.google.com/sdk/docs/install"
  exit 1
fi

# Check if manifest exists
if [[ ! -f "$MANIFEST_FILE" ]]; then
  echo -e "${RED}❌ Error: Secrets manifest not found at $MANIFEST_FILE${NC}"
  exit 1
fi

# Check if authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" &> /dev/null; then
  echo -e "${RED}❌ Error: Not authenticated with gcloud${NC}"
  echo "Run: gcloud auth login"
  exit 1
fi

# Get current project
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
if [[ -z "$PROJECT_ID" ]]; then
  echo -e "${RED}❌ Error: No GCloud project set${NC}"
  echo "Run: gcloud config set project PROJECT_ID"
  exit 1
fi

echo -e "${GREEN}✓ Project: $PROJECT_ID${NC}"
echo -e "${BLUE}✓ Manifest: $MANIFEST_FILE${NC}"
echo ""

# Function to get secret value
get_secret() {
  local secret_name=$1
  local value=$(gcloud secrets versions access latest --secret="$secret_name" 2>/dev/null)
  echo "$value"
}

# Function to check if secret exists
secret_exists() {
  local secret_name=$1
  gcloud secrets describe "$secret_name" &> /dev/null
  return $?
}

# Function to sync secrets for a platform
sync_platform() {
  local platform=$1
  local target_file=$(jq -r ".platforms.${platform}.target_file" "$MANIFEST_FILE")
  local full_path="$PROJECT_ROOT/$target_file"

  echo -e "${BLUE}📝 Generating $target_file${NC}"

  # Create header
  if [[ "$DRY_RUN" == false ]]; then
    cat > "$full_path" << 'ENV_EOF'
# Environment Variables
# Generated from Google Cloud Secret Manager via secrets-manifest.json
# DO NOT EDIT THIS FILE DIRECTLY - Use sync-gcloud-secrets.sh
#
# Last synced: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

ENV_EOF
  fi

  # Get all secret mappings for this platform
  local secrets=$(jq -r ".platforms.${platform}.secrets | to_entries[] | @base64" "$MANIFEST_FILE")

  local found_count=0
  local missing_count=0
  local empty_count=0

  for secret_entry in $secrets; do
    # Decode the base64 entry
    local gcloud_secret=$(echo "$secret_entry" | base64 --decode | jq -r '.key')
    local env_var=$(echo "$secret_entry" | base64 --decode | jq -r '.value')

    if secret_exists "$gcloud_secret"; then
      value=$(get_secret "$gcloud_secret")
      if [[ -n "$value" ]]; then
        echo -e "  ${GREEN}✓${NC} $gcloud_secret → $env_var"
        if [[ "$DRY_RUN" == false ]]; then
          # Use single quotes for JSON arrays/objects to preserve inner double quotes
          if [[ "$value" =~ ^\[.*\]$ ]] || [[ "$value" =~ ^\{.*\}$ ]]; then
            echo "$env_var='$value'" >> "$full_path"
          else
            echo "$env_var=\"$value\"" >> "$full_path"
          fi
        fi
        ((found_count++))
      else
        echo -e "  ${YELLOW}⚠${NC} $gcloud_secret → $env_var (empty value)"
        ((empty_count++))
      fi
    else
      echo -e "  ${YELLOW}⊘${NC} $gcloud_secret → $env_var (not found in GCloud)"
      ((missing_count++))
    fi
  done

  echo ""
  echo -e "  Summary: ${GREEN}$found_count found${NC}, ${YELLOW}$missing_count missing${NC}, ${YELLOW}$empty_count empty${NC}"
  echo ""
}

# Sync backend secrets
sync_platform "backend"

# Sync web secrets
sync_platform "web"

if [[ "$DRY_RUN" == false ]]; then
  echo -e "${GREEN}✅ Secrets synced successfully!${NC}"
  echo ""
  echo "Files generated:"
  echo "  - $PROJECT_ROOT/backend/.env"
  echo "  - $PROJECT_ROOT/web/.env"
  echo ""
  echo -e "${YELLOW}⚠  Restart services to apply changes${NC}"
else
  echo -e "${BLUE}ℹ  Dry run complete - no files were modified${NC}"
fi
