#!/bin/bash
#
# Sync Google Cloud Secrets to .env files
# This script pulls secrets from Google Cloud Secret Manager and regenerates .env files
#
# Usage: ./scripts/sync-gcloud-secrets.sh [--dry-run]
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

DRY_RUN=false
if [[ "$1" == "--dry-run" ]]; then
  DRY_RUN=true
  echo "🔍 DRY RUN MODE - No files will be modified"
  echo ""
fi

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔐 Bayit+ Secrets Sync - Google Cloud Secret Manager${NC}"
echo "=================================================="
echo ""

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
  echo -e "${RED}❌ Error: gcloud CLI is not installed${NC}"
  echo "Install from: https://cloud.google.com/sdk/docs/install"
  exit 1
fi

# Check if authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" &> /dev/null; then
  echo -e "${RED}❌ Error: Not authenticated with gcloud${NC}"
  echo "Run: gcloud auth login"
  exit 1
fi

# Get current project
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
if [[ -z "$PROJECT_ID" ]]; then
  echo -e "${RED}❌ Error: No GCloud project set${NC}"
  echo "Run: gcloud config set project PROJECT_ID"
  exit 1
fi

echo -e "${GREEN}✓ Project: $PROJECT_ID${NC}"
echo ""

# Function to get secret value
get_secret() {
  local secret_name=$1
  local value=$(gcloud secrets versions access latest --secret="$secret_name" 2>/dev/null)
  echo "$value"
}

# Function to check if secret exists
secret_exists() {
  local secret_name=$1
  gcloud secrets describe "$secret_name" &> /dev/null
  return $?
}

# Backend .env
echo -e "${BLUE}📝 Generating backend/.env${NC}"
BACKEND_ENV="$PROJECT_ROOT/backend/.env"

if [[ "$DRY_RUN" == false ]]; then
  cat > "$BACKEND_ENV" << 'ENV_EOF'
# Backend Environment Variables
# Generated from Google Cloud Secret Manager
# DO NOT EDIT THIS FILE DIRECTLY - Use sync-gcloud-secrets.sh

# Database
ENV_EOF
fi

# Add backend secrets
BACKEND_SECRETS=(
  "MONGODB_URI"
  "JWT_SECRET_KEY"
  "FIREBASE_CREDENTIALS_JSON"
  "SENDGRID_API_KEY"
  "OPENAI_API_KEY"
  "ANTHROPIC_API_KEY"
  "ELEVENLABS_API_KEY"
  "TMDB_API_KEY"
  "GOOGLE_APPLICATION_CREDENTIALS"
)

for secret in "${BACKEND_SECRETS[@]}"; do
  if secret_exists "$secret"; then
    value=$(get_secret "$secret")
    if [[ -n "$value" ]]; then
      echo -e "  ${GREEN}✓${NC} $secret"
      if [[ "$DRY_RUN" == false ]]; then
        echo "$secret=\"$value\"" >> "$BACKEND_ENV"
      fi
    else
      echo -e "  ${YELLOW}⚠${NC} $secret (empty)"
    fi
  else
    echo -e "  ${YELLOW}⊘${NC} $secret (not found in GCloud)"
  fi
done

echo ""

# Frontend .env
echo -e "${BLUE}📝 Generating web/.env${NC}"
WEB_ENV="$PROJECT_ROOT/web/.env"

if [[ "$DRY_RUN" == false ]]; then
  cat > "$WEB_ENV" << 'ENV_EOF'
# Frontend Environment Variables
# Generated from Google Cloud Secret Manager
# DO NOT EDIT THIS FILE DIRECTLY - Use sync-gcloud-secrets.sh

ENV_EOF
fi

# Add frontend secrets
FRONTEND_SECRETS=(
  "VITE_APP_BASE_URL"
  "VITE_SUPPORT_EMAIL"
  "VITE_FIREBASE_API_KEY"
  "VITE_FIREBASE_AUTH_DOMAIN"
  "VITE_FIREBASE_PROJECT_ID"
  "VITE_FIREBASE_STORAGE_BUCKET"
  "VITE_FIREBASE_MESSAGING_SENDER_ID"
  "VITE_FIREBASE_APP_ID"
  "VITE_FIREBASE_MEASUREMENT_ID"
)

for secret in "${FRONTEND_SECRETS[@]}"; do
  if secret_exists "$secret"; then
    value=$(get_secret "$secret")
    if [[ -n "$value" ]]; then
      echo -e "  ${GREEN}✓${NC} $secret"
      if [[ "$DRY_RUN" == false ]]; then
        echo "$secret=\"$value\"" >> "$WEB_ENV"
      fi
    else
      echo -e "  ${YELLOW}⚠${NC} $secret (empty)"
    fi
  else
    echo -e "  ${YELLOW}⊘${NC} $secret (not found in GCloud)"
  fi
done

echo ""

if [[ "$DRY_RUN" == false ]]; then
  echo -e "${GREEN}✅ Secrets synced successfully!${NC}"
  echo ""
  echo "Files generated:"
  echo "  - $BACKEND_ENV"
  echo "  - $WEB_ENV"
  echo ""
  echo -e "${YELLOW}⚠  Restart services to apply changes${NC}"
else
  echo -e "${BLUE}ℹ  Dry run complete - no files were modified${NC}"
fi
