#!/bin/bash
# Retrieve secrets from Google Cloud Secret Manager
# UPDATED: 2026-01-28 - Complete secrets inventory

PROJECT_ID="bayit-plus"

# Function to get secret value
get_secret() {
    local secret_name=$1
    gcloud secrets versions access latest --secret="$secret_name" --project="$PROJECT_ID" 2>/dev/null
}

echo "# Bayit+ Backend Configuration - Retrieved from GCP Secret Manager"
echo "# $(date)"
echo ""

echo "# ============================================"
echo "# CORE SECURITY"
echo "# ============================================"
echo "SECRET_KEY=$(get_secret bayit-secret-key)"
echo "ADMIN_EMAIL=$(get_secret bayit-admin-email)"
echo "ADMIN_PASSWORD=$(get_secret bayit-admin-password)"
echo "DEBUG=false"
echo "CSRF_ENABLED=$(get_secret bayit-csrf-enabled || echo 'false')"
echo "LOG_LEVEL=$(get_secret bayit-log-level || echo 'INFO')"
echo ""

echo "# ============================================"
echo "# BAYIT+ MONGODB DATABASE"
echo "# ============================================"
echo "MONGODB_URI=$(get_secret bayit-mongodb-uri)"
echo "MONGODB_DB_NAME=$(get_secret bayit-mongodb-db-name)"
echo ""

echo "# ============================================"
echo "# STATION AI MONGODB"
echo "# ============================================"
echo "STATION_AI_MONGODB_URI=$(get_secret station-ai-mongodb-uri)"
echo "STATION_AI_MONGODB_DB_NAME=station_ai"
echo ""

echo "# ============================================"
echo "# OLORIN FRAUD DETECTION MONGODB"
echo "# ============================================"
echo "OLORIN_MONGODB_URI=$(get_secret olorin-fraud-mongodb-uri)"
echo "OLORIN_MONGODB_DB_NAME=olorin"
echo "OLORIN_MONGODB_SOURCE_URI=$(get_secret olorin-fraud-mongodb-source-uri)"
echo ""

echo "# ============================================"
echo "# CVPLUS MONGODB"
echo "# ============================================"
echo "CVPLUS_MONGODB_URI=$(get_secret cvplus-mongodb-uri)"
echo "CVPLUS_MONGODB_DB_NAME=cvplus_production"
echo "CVPLUS_MONGODB_SOURCE_URI=$(get_secret cvplus-mongodb-source-uri)"
echo ""

echo "# ============================================"
echo "# GOOGLE CLOUD PLATFORM"
echo "# ============================================"
echo "GCP_PROJECT_ID=$(get_secret bayit-gcp-project-id)"
echo "GCS_BUCKET_NAME=$(get_secret bayit-gcs-bucket-name)"
echo "BACKEND_CORS_ORIGINS=$(get_secret bayit-cors-origins)"
echo ""

echo "# ============================================"
echo "# GOOGLE OAUTH"
echo "# ============================================"
echo "GOOGLE_CLIENT_ID=$(get_secret bayit-google-client-id)"
echo "GOOGLE_CLIENT_SECRET=$(get_secret bayit-google-client-secret)"
echo "GOOGLE_REDIRECT_URI=$(get_secret bayit-google-redirect-uri)"
echo ""

echo "# ============================================"
echo "# STRIPE PAYMENTS"
echo "# ============================================"
echo "STRIPE_API_KEY=$(get_secret bayit-stripe-api-key)"
echo "STRIPE_SECRET_KEY=$(get_secret bayit-stripe-secret-key)"
echo "STRIPE_WEBHOOK_SECRET=$(get_secret bayit-stripe-webhook-secret)"
echo "STRIPE_PRICE_BASIC=$(get_secret bayit-stripe-price-basic)"
echo "STRIPE_PRICE_PREMIUM=$(get_secret bayit-stripe-premium)"
echo "STRIPE_PRICE_FAMILY=$(get_secret bayit-stripe-price-family)"
echo ""

echo "# ============================================"
echo "# AI SERVICES"
echo "# ============================================"
echo "OPENAI_API_KEY=$(get_secret bayit-openai-api-key)"
echo "ANTHROPIC_API_KEY=$(get_secret bayit-anthropic-api-key)"
echo "ELEVENLABS_API_KEY=$(get_secret bayit-elevenlabs-api-key)"
echo "ELEVENLABS_WEBHOOK_SECRET=$(get_secret bayit-elevenlabs-webhook-secret)"
echo "ELEVENLABS_HEBREW_VOICE_ID=$(get_secret bayit-elevenlabs-hebrew-voice-id)"
echo "ELEVENLABS_ENGLISH_VOICE_ID=$(get_secret bayit-elevenlabs-english-voice-id)"
echo ""

echo "# ============================================"
echo "# TMDB (The Movie Database)"
echo "# ============================================"
echo "TMDB_API_KEY=$(get_secret tmdb-api-key)"
echo "TMDB_API_TOKEN=$(get_secret tmdb-api-token)"
echo ""

echo "# ============================================"
echo "# TWILIO COMMUNICATIONS"
echo "# ============================================"
echo "TWILIO_ACCOUNT_SID=$(get_secret bayit-twilio-account-sid)"
echo "TWILIO_AUTH_TOKEN=$(get_secret bayit-twilio-auth-token)"
echo "TWILIO_PHONE_NUMBER=$(get_secret bayit-twilio-phone-number)"
echo ""

echo "# ============================================"
echo "# OTHER EXTERNAL SERVICES"
echo "# ============================================"
echo "OPENSUBTITLES_API_KEY=$(get_secret opensubtitles-api-key)"
echo "PICOVOICE_ACCESS_KEY=$(get_secret picovoice-access-key)"
echo "SENTRY_DSN=$(get_secret bayit-sentry-dsn)"
echo "TURBO_TOKEN=$(get_secret bayit-turbo-token)"
echo ""

echo "# ============================================"
echo "# APPLE SERVICES"
echo "# ============================================"
echo "APPLE_KEY_ID=$(get_secret bayit-apple-key-id)"
echo "APPLE_TEAM_ID=$(get_secret bayit-apple-team-id)"
echo "APPLE_BUNDLE_ID_IOS=$(get_secret bayit-apple-bundle-id-ios)"
echo "APPLE_BUNDLE_ID_TVOS=$(get_secret bayit-apple-bundle-id-tvos)"
echo ""

echo "# ============================================"
echo "# OLORIN PLATFORM"
echo "# ============================================"
echo "PINECONE_API_KEY=$(get_secret olorin-pinecone-api-key)"
echo "PARTNER_API_KEY_SALT=$(get_secret olorin-partner-api-key-salt)"
echo ""

echo "# ============================================"
echo "# GEOLOCATION SERVICES"
echo "# ============================================"
echo "GEONAMES_USERNAME=$(get_secret bayit-geonames-username)"
echo "GEONAMES_API_BASE_URL=$(get_secret bayit-geonames-api-base-url || echo 'https://secure.geonames.org')"
echo "GEONAMES_TIMEOUT_SECONDS=$(get_secret bayit-geonames-timeout-seconds || echo '10')"
echo "LOCATION_ENCRYPTION_KEY=$(get_secret bayit-location-encryption-key)"
echo "LOCATION_CACHE_TTL_HOURS=$(get_secret bayit-location-cache-ttl-hours || echo '24')"
echo "LOCATION_REVERSE_GEOCODE_RATE_LIMIT=$(get_secret bayit-location-reverse-geocode-rate-limit || echo '30')"
echo "LOCATION_CONTENT_RATE_LIMIT=$(get_secret bayit-location-content-rate-limit || echo '60')"
echo ""

echo "# ============================================"
echo "# SSRF PROTECTION - Domain Whitelists"
echo "# ============================================"
echo "ALLOWED_IMAGE_DOMAINS=$(get_secret bayit-allowed-image-domains)"
echo "ALLOWED_AUDIO_DOMAINS=$(get_secret bayit-allowed-audio-domains)"
echo "ALLOWED_SUBTITLE_DOMAINS=$(get_secret bayit-allowed-subtitle-domains)"
echo "ALLOWED_EPG_DOMAINS=$(get_secret bayit-allowed-epg-domains)"
echo "ALLOWED_SCRAPER_DOMAINS=$(get_secret bayit-allowed-scraper-domains)"
echo ""

echo "# ============================================"
echo "# LIBRARIAN AUDIT RECOVERY"
echo "# ============================================"
echo "AUDIT_STUCK_TIMEOUT_MINUTES=$(get_secret bayit-audit-stuck-timeout-minutes || echo '30')"
echo "AUDIT_NO_ACTIVITY_TIMEOUT_MINUTES=$(get_secret bayit-audit-no-activity-timeout-minutes || echo '15')"
echo "AUDIT_HEALTH_CHECK_INTERVAL_SECONDS=$(get_secret bayit-audit-health-check-interval-seconds || echo '300')"
echo ""

echo "# ============================================"
echo "# NON-SECRET CONFIGURATION"
echo "# ============================================"
echo "ENVIRONMENT=production"
echo "PODCAST_TRANSLATION_ENABLED=true"
