module.exports = {
  testEnvironment: 'jsdom',
  modulePaths: ['<rootDir>/node_modules'],
  moduleFileExtensions: ['web.tsx', 'web.ts', 'web.jsx', 'web.js', 'tsx', 'ts', 'jsx', 'js', 'json'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { configFile: './babel.config.cjs' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|@react-navigation|react-native-web|react-native-linear-gradient|react-native-web-linear-gradient|react-router-dom|nanoid|react-error-boundary|lucide-react|lucide-react-native|@expo/vector-icons|expo-font|expo-asset|expo-modules-core|expo-constants|expo-file-system|expo)/)',
  ],
  testMatch: [
    '<rootDir>/src/**/*.(test|spec).(ts|tsx|js|jsx)',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx,js,jsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/node_modules/**',
    '!src/main.jsx',
    '!src/vite-env.d.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 87,
      functions: 87,
      lines: 87,
      statements: 87,
    },
  },
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^react-native$': 'react-native-web',
    '^expo-modules-core$': '<rootDir>/src/utils/expoModulesCoreShim.js',
    '^expo-asset$': '<rootDir>/src/utils/expoAssetShim.js',
    '^react-native-svg$': '<rootDir>/../node_modules/react-native-svg/lib/commonjs/ReactNativeSVG.web.js',
    '^@olorin/design-tokens$': '<rootDir>/../packages/ui/design-tokens/src/index.ts',
    '^@olorin/shared-icons/(.*)$': '<rootDir>/../packages/ui/shared-icons/src/$1',
    '^@bayit/shared-utils/(.*)$': '<rootDir>/../shared/utils/$1',
    '^@bayit/glass$': '<rootDir>/__mocks__/@olorin/glass-ui.cjs',
    '^@bayit/shared$': '<rootDir>/../shared/components',
    '^@bayit/shared-services$': '<rootDir>/../shared/services/index.ts',
    '^@bayit/shared-services/(.*)$': '<rootDir>/../shared/services/$1',
    '^@bayit/shared-stores$': '<rootDir>/../shared/stores/index.ts',
    '^@bayit/shared-stores/(.*)$': '<rootDir>/../shared/stores/$1',
    '^@bayit/shared-hooks$': '<rootDir>/../shared/hooks/index.ts',
    '^@bayit/shared-hooks/(.*)$': '<rootDir>/../shared/hooks/$1',
    '^@bayit/shared-types/(.*)$': '<rootDir>/../shared/types/$1',
    '^@bayit/shared/ui$': '<rootDir>/../shared/components/ui',
    '^@bayit/shared/ui/(.*)$': '<rootDir>/../shared/components/ui/$1',
    '^@bayit/shared/quiz/(.*)$': '<rootDir>/../shared/components/quiz/$1',
    '^@bayit/shared/search$': '<rootDir>/../shared/components/search',
    '^@bayit/shared/(.*)$': '<rootDir>/../shared/$1',
    '^@bayit/glass-components$': '<rootDir>/__mocks__/@bayit/glass-components.cjs',
    '^@olorin/glass-ui$': '<rootDir>/__mocks__/@olorin/glass-ui.cjs',
    '^@olorin/glass-ui/stores$': '<rootDir>/../packages/ui/glass-components/src/stores/index.ts',
    '^@olorin/glass-ui/(.*)$': '<rootDir>/__mocks__/@olorin/glass-ui.cjs',
    '^recharts$': '<rootDir>/__mocks__/recharts.cjs',
    '^react-native-linear-gradient$': '<rootDir>/__mocks__/react-native-linear-gradient.js',
    '^react-native-web-linear-gradient$': '<rootDir>/__mocks__/react-native-linear-gradient.js',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|svg|ttf|woff|woff2)$': '<rootDir>/__mocks__/fileMock.js',
  },
};
